-- Mission data for acp — extracted from BG Wiki (https://www.bg-wiki.com)
-- Generated: 2026-03-30
-- Total missions: 12
--
-- Fields: start_npc, start_zone, start_pos, description, reward, fame,
--         fame_level, title, repeatable, previous, next, requirements,
--         walkthrough, notes
-- Auto-generated from BG Wiki data.
-- Do not edit manually.

return {
    ['A Crystalline Prophecy'] = {
        id = 0,
        start_npc = nil,
        start_zone = 'Lower Jeuno',
        start_pos = nil,
        description = 'For what purpose has the ancient crystal returned? A new adventure to unearth the secrets of Vana\'diel\'s past begins!',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = nil,
        next = {'The Echo Awakens'},
        requirements = nil,
        walkthrough = '1. Enter Lower Jeuno while level 10 or above for a cutscene.',
        notes = nil,
    },
    ['A Crystalline Prophecy (Fin.)'] = {
        id = 11,
        start_npc = nil,
        start_zone = 'Stellar Fulcrum',
        start_pos = nil,
        description = '?',
        reward = 'Ability to purchase [Key Item] Atma of Echoes\n:One of the following:\nMirke Wardecors \nNuevo Coselete \nRoyal Redingote',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Ode of Life Bestowing'},
        next = nil,
        requirements = nil,
        walkthrough = '1. Head to Tenshodo in Lower Jeuno and examine the Treasure Chest for your reward.\n   - The easiest way to repeat the fight to change your augmented item is to first toss it, then purchase the Omnis Stone from Squintrox Dryeyes in Port Jeuno for 2,000 gil and 20 Beastmen Seals. This will allow you to enter the BCNM in the Stellar Fulcrum. After the fight, you will immediately receive the keys.',
        notes = nil,
    },
    ['Banishing the Echo'] = {
        id = 9,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'To reach your final destination, you must recover the twelve remaining fragments of the mysterious crystal...',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Born of Her Nightmares'},
        next = {'Ode of Life Bestowing'},
        requirements = nil,
        walkthrough = '1. During this mission, you will have to examine Seed Fragments in each zone to receive a level cap status (level 30).  While under the effects of this level cap, you will be able to collect key items by touching Seed Afterglows.  You will not be able to be cured by people who are not under the level cap status, but you will also not lose Experience Points should you die.\n   - Trust Magic is not available during this level restriction effect.\n2. Prism Powders and Silent Oils are recommended if you solo this, as there can be monsters that aggro by magic around such as dolls and elementals. Seed Fragments tend to be surrounded by monsters that aggro by sight in most cases, so you\'ll want to drop your invisibility next to the Seed Fragment as soon as they are all facing away from you, examine it, and become invisible again as quickly as possible.\n3. Examine the Seed Fragment on the First Floor (H-10).\n   - Examine the Seed Afterglow on the First Floor (J-10) for the [Key Item] Amicitia Stone.\n   - Examine the Seed Afterglow on the Second Floor (H-7) for the [Key Item] Veritas Stone.\n   - Examine the Seed Afterglow on the Third Floor (I-9) for the [Key Item] Sapientia Stone.\nImage:Lower Delkfutt\'s Tower-map1.jpg|Lower Delkfutt\'s Tower - Map 1\nImage:Lower Delkfutt\'s Tower-map2.jpg|Lower Delkfutt\'s Tower - Map 2\nImage:Lower Delkfutt\'s Tower-map3.jpg|Lower Delkfutt\'s Tower - Map 3\n4. Examine the Seed Fragment on the Fourth Floor (G-6).\n   - Examine the Seed Afterglow on the Fourth Floor (H-10) for the [Key Item] Sanctitas Stone.\n   - Examine the Seed Afterglow on the Fifth Floor (G-7) for the [Key Item] Felicitas Stone.\n   - Examine the Seed Afterglow on the Sixth Floor (F-8) for the [Key Item] Divitia Stone.\n   - Examine the Seed Afterglow on the Seventh Floor (H-9) for the [Key Item] Studium Stone.\n   - Examine the Seed Afterglow on the Eighth Floor (I-8) for the [Key Item] Amoris Stone.\n   - Examine the Seed Afterglow On the Ninth Floor (G-8) for the [Key Item] Caritas Stone.\nImage:Middle Delkfutt\'s Tower-map1.jpg|Middle Delkfutt\'s Tower - Map 1\nImage:Middle Delkfutt\'s Tower-map2.jpg|Middle Delkfutt\'s Tower - Map 2\nImage:Middle Delkfutt\'s Tower-map3.jpg|Middle Delkfutt\'s Tower - Map 3\nImage:Middle Delkfutt\'s Tower-map4.jpg|Middle Delkfutt\'s Tower - Map 4\nImage:Middle Delkfutt\'s Tower-map5.jpg|Middle Delkfutt\'s Tower - Map 5\nImage:Middle Delkfutt\'s Tower-map6.jpg|Middle Delkfutt\'s Tower - Map 6\n5. Examine the Seed Fragment on the Tenth Floor (F-7).\n   - Examine the Seed Afterglow on the Tenth Floor (F-10) for the [Key Item] Constantia Stone.\n   - Examine the Seed Afterglow on the Eleventh Floor (H-7) for the [Key Item] Spei Stone.\n   - Examine the Seed Afterglow on the Twelfth Floor (H-7) for the [Key Item] Salus Stone.\nImage:Upper Delkfutt\'s Tower-map1.jpg|Upper Delkfutt\'s Tower - Map 1\nImage:Upper Delkfutt\'s Tower-map2.jpg|Upper Delkfutt\'s Tower - Map 2\nImage:Upper Delkfutt\'s Tower-map3.jpg|Upper Delkfutt\'s Tower - Map 3\n6. Examine the Seed Fragment in Stellar Fulcrum with all 12 stone key items to receive an [Key Item] Omnis Stone.',
        notes = nil,
    },
    ['Born of Her Nightmares'] = {
        id = 8,
        start_npc = nil,
        start_zone = 'Lower Delkfutt\'s Tower',
        start_pos = nil,
        description = 'The mysterious child Aldo claims that the answer to the mystery sleeps within Delkfutt\'s Tower. Have you the courage to face the truth?',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Remember Me in Your Dreams'},
        next = {'Banishing the Echo'},
        requirements = nil,
        walkthrough = '1. Enter Lower Delkfutt\'s Tower for a cutscene.',
        notes = nil,
    },
    ['Gatherer of Light (I)'] = {
        id = 2,
        start_npc = 'Qufim Island',
        start_zone = nil,
        start_pos = nil,
        description = 'When the echo runs amok, the key to Vana\'diel\'s salvation lies with three unusual stones that have found their way into the hands of some overly curious Goblins...',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'The Echo Awakens'},
        next = {'Gatherer of Light (II)'},
        requirements = nil,
        walkthrough = '1. You need to retrieve three key items used to pop Goblin Notorious Monsters.  Any characters on (or past) this mission can receive the goblin food key items as long as they are in the same party/alliance.\n   - These key items have a 10% obtainment rate.  If you are in a party/alliance, 1 character at random will be chosen to receive it (if they don\'t have it already).\nNOTE: You must have the respective goblin food key item when the NM is killed in order to obtain the seedspall key item.\n2. Kill goblins in Batallia Downs to obtain the key item [Key Item]Bowl of bland Goblin salad.  Examine the ??? at (F-5) (middle) to pop Vegnix Greenthumb, and kill it to receive [Key Item]Seedspall Roseum.\n   - The ??? is on the upper level, which is connected to Beaucedine Glacier.\n     - If you\'ve unlocked the Lycopodium Warps in the past, trade a flower to the glowing spot at Batallia Downs (F-5) to teleport up.\n     - You can teleport to Beaucedine Glacier via Voidwatch NPC (requires level 75 and [Key Item]Adventurer\'s Certificate) or survival guide. Walking there requires going through Ranguemont Pass (requires [Key Item]Adventurer\'s Certificate).\n3. Kill goblins in Rolanberry Fields to obtain the key item [Key Item]jug of greasy Goblin juice.  Examine the ??? at (D-11) to pop Chuglix Berrypaws, and kill it to receive [Key Item]Seedspall Caerulum.\n   - The ??? is on the same level as Simurgh, which can be reached by Voidwatch NPC teleport (choose Jeuno > Crawlers\' Nest (entrance)), Unity Warp 125 to Rolanberry Fields, or by traveling through Crawlers\' Nest.\n4. Kill goblins in Sauromugue Champaign to obtain the key item [Key Item]chunk of smoked Goblin grub.  Examine the ??? at (I-9) (south-east corner) to pop Dribblix Greasemaw, and kill it to receive [Key Item]Seedspall Viridis.\n   - The ??? is on the same level as Roc, which can be reached by Voidwatch NPC teleport (choose Jeuno > Garlaige Citadel (entrance)), by survival guide > Sauromugue Champaign, or by traveling through Garlaige Citadel.\n5. Examine the ??? at (G-6) in Qufim Island with the three Seedspall key items for a cutscene.',
        notes = nil,
    },
    ['Gatherer of Light (II)'] = {
        id = 3,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'Was it all truly decided before the dawn of time...? When the crystal sends forth its dark minions, only you can put a stop to them!',
        reward = '[Key Item] Amber Key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Gatherer of Light (I)'},
        next = {'Those Who Lurk in Shadows (I)'},
        requirements = nil,
        walkthrough = '1. Prepare to battle. Trust Magic can not be used in this fight.\n   - You will keep your buffs and pets.\n2. Examine the ??? at (G-6) in Qufim Island to begin a battle.\n3. Several waves of Seed Mandragoras will spawn and swarm the characters.  Though 5 or 6 will come at a time, they are very weak and can be easily defeated with one melee strike or AoE magic.\n4. After killing several waves of Seed Mandragora (30 total, six waves of 5) you will receive a message that the mission has ended, and an [Key Item] Amber Key.\n5. Examine the ??? again for a cutscene.',
        notes = nil,
    },
    ['Ode of Life Bestowing'] = {
        id = 10,
        start_npc = nil,
        start_zone = 'Stellar Fulcrum',
        start_pos = nil,
        description = 'The final confrontation awaits you within the Stellar Fulcrum...',
        reward = 'Ebon Key\nPrismatic Key',
        fame = nil,
        fame_level = nil,
        title = 'Silencer of the Echo',
        repeatable = nil,
        previous = {'Banishing the Echo'},
        next = {'A Crystalline Prophecy (Fin.)'},
        requirements = nil,
        walkthrough = '1. Examine the Qe\'Iov Gate in Stellar Fulcrum for a cutscene.  Examine it again to begin the burning circle fight.\n2. Your opponent will be a Seed Crystal.  Instead of normal melee attacks, it has a ranged AoE magic-type attack.  It will also frequently Draw-In whoever holds primary hate.\n   - Has approximately 25,000 HP.\n   - Has both strong Physical and Magical Defense.\n   - Can cast: Stonega III, Waterga III, Aeroga III, Thundaga III, Firaga III, Blizzaga III\n   - Has Draw In.\n   - Special Attacks:\n     - Seed of Nihility: AoE Damage low damage.  It also causes all job ability timers on all party members to be set to their maximum recast within range of the move. This includes 2hr abilities.\n     - Seed of Deference: AoE Charm, any player charmed by this move is put in a Seed Mandragora costume.\n     - Seed of Deception: Makes a clone of targeted player called "Seed Thrall" and it will attack the player that has hate. Uses this move quite frequently during the fight.\n     - Seed of Judgment: Knock-back AoE high damage.',
        notes = nil,
    },
    ['Remember Me in Your Dreams'] = {
        id = 7,
        start_npc = nil,
        start_zone = 'Hall of the Gods',
        start_pos = nil,
        description = 'In the Hall of the Gods, the beginning of the end draws nigh. Will you succeed in changing the course of fate?',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Those Who Lurk in Shadows (III)'},
        next = {'Born of Her Nightmares'},
        requirements = nil,
        walkthrough = '1. Enter the Hall of the Gods from Ro\'Maeve for a cutscene.\n   - If you enter the Hall of the Gods from Ru\'Aun Gardens, you will have to exit to Ro\'Maeve and enter from there to proceed.',
        notes = nil,
    },
    ['The Echo Awakens'] = {
        id = 1,
        start_npc = 'Lower Jeuno',
        start_zone = 'Meriphataud Mountains',
        start_pos = 'G-11',
        description = 'The primordial crystal appeared over Jeuno, its otherworldly light raining down from the heavens upon the forests, marshlands, and mountains. A mysterious young boy would have you recover that light and bring it to Qufim Island. Will you heed the call?',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'A Crystalline Prophecy'},
        next = {'Gatherer of Light (I)'},
        requirements = nil,
        walkthrough = '1. Collect the following 3 items:\n   - Seedspall Lux from Orcs in Jugner Forest around (G-11).\n     - Closest Survival Guide is Davoi.\n   - Seedspall Luna from Quadavs in Pashhow Marshlands around (K-10).\n     - Closest Survival Guide is Beadeaux.\n   - Seedspall Astrum from Yagudos in Meriphataud Mountains around (K-8).\n     - Closest Survival Guide is Castle Oztroja.\n2. Trade the 3 Seedspalls to the ??? at (G-6) in Qufim Island for a cutscene.\n   - Mid-east section of (G-6), near 2 rock columns.',
        notes = nil,
    },
    ['Those Who Lurk in Shadows (I)'] = {
        id = 4,
        start_npc = nil,
        start_zone = 'Fei\'Yin',
        start_pos = nil,
        description = 'In the darkness of the ruined city Fei\'Yin, beastmen in the thrall of the crystal devise their nefarious plot...',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'Gatherer of Light (II)'},
        next = {'Those Who Lurk in Shadows (II)'},
        requirements = nil,
        walkthrough = '1. Enter Fei\'Yin for a cutscene.',
        notes = nil,
    },
    ['Those Who Lurk in Shadows (II)'] = {
        id = 5,
        start_npc = nil,
        start_zone = 'Fei\'Yin',
        start_pos = nil,
        description = 'Your quest takes you to Qu\'Bia Arena, but the otherworldly force of the crystal bars your path. Only by harnessing its power for yourself may you gain entry!',
        reward = 'Mark of Seed or Azure Key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'Yes',
        previous = {'Those Who Lurk in Shadows (I)'},
        next = {'Those Who Lurk in Shadows (III)'},
        requirements = nil,
        walkthrough = '1. You must find 9 Seed Afterglows in Fei\'Yin: with red, orange, yellow, green, cerulean, blue, golden, silver, and white radiance.\n   - You have 30 minutes earth time to gather the 9 Afterglows.  If you do not collect them all in 30 minutes zone out and back in to begin the process over again.\n   - The Seed Afterglows move periodically, but stay in the same general areas, refer to the maps below.\n   - If you can\'t find the yellow Seed Afterglow on the area indicated in the map above, check the circular room at H-9/I-9.\n2. Once you collect all 9, you will be given the option to get either [Key Item] Mark of Seed (to continue to the next mission) or an [Key Item] Azure Key for a reward.\n   - You may only repeat this process of gathering Seed Afterglows once per real-life day.\n   - Rewards are listed on the Add-on Scenario Rewards page.',
        notes = nil,
    },
    ['Those Who Lurk in Shadows (III)'] = {
        id = 6,
        start_npc = nil,
        start_zone = 'Qu\'Bia Arena',
        start_pos = nil,
        description = 'The beastman thralls of the Seed Crystal are threatening to commence their dark ritual. They must be stopped before it is too late!',
        reward = 'Ivory Key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Those Who Lurk in Shadows (II)'},
        next = {'Remember Me in Your Dreams'},
        requirements = nil,
        walkthrough = '1. Examine the Burning Circle (Qu\'Bia Arena) for a cutscene, examine it again to begin the fight.\n   - Trusts can be called in this fight as of October 11, 2016.\n2. You will face 4 opponents in the BC:\n   - Seed Yagudo- WHM\n     - Has a special ability called Phantasmal Dance, which causes AoE damage, Knockback, and Bind.\n   - Seed Quadav- RDM\n     - Has a special ability called Feather Maelstrom, which causes Amnesia and Bio.\n   - Seed Orc- WAR, initally shares hate with the Yagudo, then the Quadav after the Yagudo is defeated.\n     - Has a special ability called Thunderous Yowl, which gives AoE Curse and Plague.\n   - Seed Goblin- THF, likes to teleport behind random people and do weaponskills.\n     - Has an ability called Saucepan, which gives all players in range a new food effect that gives -10 to all attributes.\n     - This food effect seems to wear off in about 30 minutes.\n     - Will randomly teleport around the arena during the fight.\n     - Stacks Sneak Attack and Trick Attack when using both Goblin Rush and Bomb Toss.\n3. When the battle is completed, there will be a cutscene and you will receive [Key Item] Ivory Key (Level 70).',
        notes = nil,
    },
}
