-- Mission data for asa — extracted from BG Wiki (https://www.bg-wiki.com)
-- Generated: 2026-03-30
-- Total missions: 15
--
-- Fields: start_npc, start_zone, start_pos, description, reward, fame,
--         fame_level, title, repeatable, previous, next, requirements,
--         walkthrough, notes
-- Auto-generated from BG Wiki data.
-- Do not edit manually.

return {
    ['A Shantotto Ascension'] = {
        id = 0,
        start_npc = 'Windurst Walls',
        start_zone = 'Windurst Waters',
        start_pos = nil,
        description = 'Doctor Shantotto returned to Windurst one day after a mysterious, unexplained absence, shocking her colleagues by proclaiming herself ruler of her own empire. What could have possibly triggered this intensification of her inimical urges? The shocking truth awaits adventurers who would seek it!',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = nil,
        next = {'Burgeoning Dread'},
        requirements = nil,
        walkthrough = '1. Zone into Windurst Walls from Windurst Woods or Windurst Waters while level 10 or above.\n   - Entering via any other means (including the Mog House) will not trigger the starting cutscene.',
        notes = nil,
    },
    ['A Shantotto Ascension (Fin)'] = {
        id = 14,
        start_npc = nil,
        start_zone = 'Lower Jeuno',
        start_pos = nil,
        description = nil,
        reward = 'Ability to purchase [Key Item] Atma of Ambition\n:One of the following:\nBlitzer Poleyn \nDesultor Tassets \nTatsu. Sitagoromo',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'An Uneasy Peace'},
        next = nil,
        requirements = nil,
        walkthrough = '1. Redeem the [Key Item] Behemoth key at the Tenshodo in Lower Jeuno for your reward.',
        notes = nil,
    },
    ['An Uneasy Peace'] = {
        id = 13,
        start_npc = nil,
        start_zone = 'Windurst Waters',
        start_pos = nil,
        description = 'Mission Orders: Disaster has been averted thanks to your relentless efforts, each denizen of Vana\'diel returning to the life they used to know. But how long can this period of tranquility be expected to endure? Professor Yoran-Oran cannot help but be pessimistic...',
        reward = '[Key Item] Behemoth key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Project: Shantottofication'},
        next = {'A Shantotto Ascension (Fin)'},
        requirements = nil,
        walkthrough = '1. Zone into Windurst Walls from Windurst Woods or Windurst Waters for a cutscene.\n   - Entering via any other means (including the Mog House or HP Warp) will not trigger the final cutscene.\n2. You will be awarded a [Key Item] Behemoth key, which can be redeemed at the Treasure Coffer in Tenshodo Headquarters in Lower Jeuno for Blitzer Poleyn , Desultor Tassets  or Tatsu. Sitagoromo .',
        notes = nil,
    },
    ['Battaru Royale'] = {
        id = 9,
        start_npc = 'Full Moon Fountain',
        start_zone = nil,
        start_pos = nil,
        description = 'Mission Orders: Determined to enact her odious plot to conquer all of Vana\'diel, Domina Shantotto has unleashed her army of clones upon you. Defeat them all lest you and your companions be reduced to bones!',
        reward = '[Key Item] Chocobo key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'Yes',
        previous = {'Fountain of Trouble'},
        next = {'Romancing the Clone'},
        requirements = nil,
        walkthrough = '1. After the initial cutscene from the Moon Spiral, click it again while possessing at least one elemental sap Key Item to receive the option to enter the Battaru Royale battlefield.\n2. The battle is against 8 Tarutaru Fomor mobs, one for each element. (Clone of Boulders, Clone of Torrents, Clone of Gusts, Clone of Flames, Clone of Glaciers, Clone of Sparks, Clone of Lights, Clone of Shadows)\n   - Each Fomor will cast elemental and enfeebling spells of their corresponding element.\n   - Each Fomor will summon an avatar of their corresponding element when they reach about 50% HP, and the avatar will use its associated Astral Flow ability before despawing.\n   - The Fomors have access to all their usual TP abilities.\n3. Successfully completing the battle will result in the awarding of a [Key Item] Chocobo key, which can be redeemed at the Treasure Coffer in Tenshodo Headquarters in Lower Jeuno.',
        notes = nil,
    },
    ['Burgeoning Dread'] = {
        id = 1,
        start_npc = 'East Sarutabaruta or West Sarutabaruta',
        start_zone = 'West Sarutabaruta',
        start_pos = nil,
        description = 'Mission Orders: Does this feeling of disquiet welling up within portend the coming of catastrophe, or is it simply something to be ignored? You can only hope that it is all in your mind...',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'A Shantotto Ascension'},
        next = {'That Which Curdles Blood'},
        requirements = nil,
        walkthrough = '1. Zone into either East Sarutabaruta or West Sarutabaruta via one of Windurst\'s gates for a cutscene.\n   - Take note of which Enfeeblement Kit you are asked for in the cutscene. It will be required to complete the next mission.',
        notes = nil,
    },
    ['Enemy of the Empire (I)'] = {
        id = 4,
        start_npc = 'Andrause',
        start_zone = 'Norg',
        start_pos = 'I-8',
        description = 'Mission Orders: Seeking to usurp the Tenshodo as the underworld\'s foremost supplier of contraband, Domina Shantotto requires that you remove its leader, Aldo, from the picture. A clandestine meeting between you and the target has been arranged in the Gustav Tunnel. All that is needed to initiate contact is a black book, acquirable from Andrause in Norg.',
        reward = '[Key Item] Black book',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Sugar-coated Directive'},
        next = {'Enemy of the Empire (II)'},
        requirements = nil,
        walkthrough = ' Composite Map\n1. Talk to Andrause at (I-8) in Norg.\n2. You will be given 3 specific monsters from which you must acquire a Soul Plate  using a Soultrapper .\n   - Andrause will offer to sell you a Soultrapper and 12 Blank Soul Plates for 800 Gil.\n   - You can buy another 12 Blank Soul Plates from him each day (after JP Midnight).\n   - Note: he will only accept Soul Plates of monsters found in Sea Serpent Grotto.\n3. How to take pictures:\n   - Equip the Soultrapper into your Ranged slot, and the Blank Soul Plates into your Ammo slot.\n   - You can then use the Soultrapper via the Inventory onto a target, or alternatively, use a macro line /item "Soultrapper"  or any equivalent.\n   - The Soultrapper cannot be used while under the effect of Sneak or Invisible.\n   - Sometimes you\'ll fail taking a picture. Just try again!\n4. Andrause will mention which monsters he\'s "investigating", and depending on the monsters chosen, you may need a Silver Beastcoin , Mtl. Beastcoin  or Gold Beastcoin  to gain access to them:\n   - Monsters found in the open area: Bigclaw (M-14), Brook Sahagin, Riparian Sahagin, Rivulet Sahagin, Royal Leech, Undead Bats and Grotto Pugil.\n   - Monsters found behind the Silver Beastcoin door:  Grotto Pugil, Sea Bonze.\n   - Monsters found behind the Mythril Beastcoin door: Blubber Eyes, Bog Sahagin, Marsh Sahagin, Rock Crab, Razorjaw Pugil, Sahagin Parasite, Swamp Sahagin.\n   - Monsters found behind the Gold Beastcoin door: Coastal Sahagin, Devil Manta, Delta Sahagin, Dire Bat, Lagoon Sahagin,  Mousse, Robber Crab, Shore Sahagin.\n     - Unity Warp (125) puts you past the Gold Beastcoin door.\n     - Delta Sahagin\'s can sometimes be pulled down into the open area at (J-12, K-12 Map 1) off the ledge from behind the Ornamental Door with magic.\n5. Trade the required Soul Plates to him one at a time and he will give you a [Key Item] Black book Key Item.\n   - Should you require another, he will give you one in exchange for 3 more Soul Plates of his choosing.\n6. Once you have the book, click on the Outcropping at (F-10) in Gustav Tunnel for a cutscene.\n7. Clicking it a second time will immediately start the next mission and initiate a fight against 3 Tenshodo agents.\n   - The Black book is taken once the fight starts, so if you should lose, you will need to acquire another.',
        notes = nil,
    },
    ['Enemy of the Empire (II)'] = {
        id = 5,
        start_npc = nil,
        start_zone = 'Cape Teriggan',
        start_pos = 'I-8',
        description = 'Mission Orders: The overzealous young Tenshodo agents are not interested in listening to reason. In the name of your empress, you have no choice but to flex your adventurer muscles and pound some sense into them.',
        reward = '[Key Item] Cactuar key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Enemy of the Empire (I)'},
        next = {'Sugar-coated Subterfuge'},
        requirements = nil,
        walkthrough = '1. Interact with the Outcropping at (F-10) in Gustav Tunnel for a cutscene.\n   - Unity Warp 128 from Cape Teriggan can be faster for those without movement speed bonuses.\n   - Survival Guide in Gustav Tunnel (K-7) puts you on the opposite end of the tunnel. You will not need Sneak at level 75.\n2. The following fight is trivial at level cap, but if you\'re at a lower level, prepare to battle:\n3. Interacting with the Outcropping again will start a fight against 3 Tenshodo agents named Renfred, Bompupu and Gorattz and consume the [Key Item] Black book Key Item.\n   - Trust Magic can not be used in this fight.\n   - You will keep your buffs: Phalanx will negate all damage from this fight except Bompupu\'s nukes.\n4. The 3 agents start off untargetable and cast Utsusemi: Ni a few times, then 4 clones of each will spawn.\n   - The clones aren\'t very strong, having low HP, accuracy, attack and defense, and cast elemental and enfeebling Ninjutsu.\n5. At some point (either time elapsed or number of clones defeated), the 3 agents will join the fight, at which time they can be attacked, and must be defeated in order to win the encounter.\n   - They can be differentiated from the clones because they have higher HP and will continue to cast Utsusemi as well as other Ninjutsu.\n   - Once in the fight, they will still continue to spawn clones as the clones are dispatched.\n   - Once an agent is defeated, any of his or her remaining clones will despawn after a couple of seconds.\n6. When all 3 agents are down, you will be rewarded a [Key Item] Cactuar key, which can be redeemed at the Treasure Coffer in Tenshodo Headquarters in Lower Jeuno.\n7. Interact with the Outcropping again for a cutscene.',
        notes = nil,
    },
    ['Fountain of Trouble'] = {
        id = 8,
        start_npc = nil,
        start_zone = 'Full Moon Fountain',
        start_pos = 'F-10',
        description = 'Mission Orders: Original Shantotto has revealed that her corrupted counterpart concocts her plan for world domination from her Full Moon Fountain lair. In the defense of Vana\'diel, make your way there without delay.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Shantotto in Chains'},
        next = {'Battaru Royale'},
        requirements = nil,
        walkthrough = 'In order to receive the cutscene from the Moon Spiral in Full Moon Fountain, you have to have at least 1 sap Key Item in your possession:\n1. The 8 elemental saps can be found at various locations throughout Toraimarai Canal and have the effect of weakening the Astral Flow ability of the corresponding Fomor\'s avatar in the battlefield awaiting you in the next mission.\n   - At max level, it is possible to skip most of the mission by warping to Home Point #1, getting the [Key Item] Dark sap crystal near the Home Point, then backtracking to Full Moon Fountain to continue the questline.\n   - If you\'re attempting the upcoming battle below level 99, collecting all the saps will make the fight easier.\n2. The elemental saps appear as glowing ???s at the following locations:\n   - [Key Item] Dark sap crystal: (F-8) Map 1\n   - [Key Item] Earth sap crystal: (J-8) or (H-7) Map 1\n   - [Key Item] Water sap crystal: (H-7) or (J-9) Map 1\n   - [Key Item] Fire sap crystal: (J-9)  Map 1; (F-10) or (J-8) Map 2\n   - [Key Item] Ice sap crystal: (I-8) or (H-7) Map 2\n   - [Key Item] Light sap crystal: (G-8) Map 2 (one of two places)\n   - [Key Item] Lightning sap crystal: (H-7) Map 1; (G-10/11) Map 2\n   - [Key Item] Wind sap crystal: (H-9) or (J-9) Map 2\n3. Once one or more saps are collected, check the Moon Spiral in Full Moon Fountain to watch the cutscene and complete the mission.',
        notes = nil,
    },
    ['Project: Shantottofication'] = {
        id = 12,
        start_npc = 'Sacrificial Chamber',
        start_zone = 'Sacrificial Chamber',
        start_pos = nil,
        description = 'Mission Orders: The inimitably fiendish Shantottofication curse, if allowed to wreak havoc on the land, would spell the end of the world as we know it. Only you can prevent an unimaginable fate from befalling Vana\'diel!',
        reward = '[Key Item] Tonberry key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Sisters in Arms'},
        next = {'An Uneasy Peace'},
        requirements = nil,
        walkthrough = '1. After the initial cutscene, click the Mahogany Door in the Sacrificial Chamber again for the option to the enter the Project: Shantottofication battlefield.\n   - The tablet Key Items are consumed upon entry and each one grants a buff. Possessing a full set will grant a +150 resistance to  Earth,  Water,  Wind,  Fire,  Ice and  Thunder magic, +150 to STR, VIT, DEX, AGI, MND, INT and CHR, a 3x multiplier to HP and MP, and a special Reraise that does not confer Weakness upon use.\n   - The tablets are not necessary to begin the fight, and it is soloable by most Jobs in 119 gear with Trusts.\n2. The fight is against D. Shantotto and Shantotto:\n   - D. Shantotto casts high level magic spells and uses Scythe weaponskills, including Salvation Scythe, which does AoE damage and inflicts poison and paralysis.\n   - Shantotto casts high level magic spells and uses staff weaponskills, including Divine Malison, which does AoE damage and inflicts stun, slow, silence and plague.\n3. Once one or the other reaches 50% HP, she will enter a kind of rage mode where she calls the other over to perform skillchains using their signature weaponskills on the current target.\n   - They cannot be drawn apart at this time.\n   - While in this mode, the "raged" Shantotto cannot be killed. Damage can still be done to her, but she will not drop below 1% HP until it ends.\n   - If the party wipes after the rage mode is triggered, it will not be repeated if a second attempt is made without exiting the battlefield.\n4. Successful completion of the fight will award a [Key Item] Tonberry key, which can be redeemed at the Treasure Coffer in Tenshodo Headquarters in Lower Jeuno.',
        notes = nil,
    },
    ['Romancing the Clone'] = {
        id = 10,
        start_npc = 'Aldo',
        start_zone = 'Lower Jeuno',
        start_pos = 'J-8',
        description = 'Mission Orders: To your dismay but not complete surprise, Original Shantotto has chosen to side with her heinous alter ego. Best you return at once to Tenshodo Headquarters to plan your next move.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Battaru Royale'},
        next = {'Sisters in Arms'},
        requirements = nil,
        walkthrough = '1. Talk to Aldo at (J-8) in Tenshodo Headquarters in Lower Jeuno for a cutscene.',
        notes = nil,
    },
    ['Shantotto in Chains'] = {
        id = 7,
        start_npc = 'Ro\'Maeve',
        start_zone = 'Ro\'Maeve',
        start_pos = 'B-10',
        description = 'Mission Orders: You have learned that the original Doctor Shantotto is being held captive somewhere in Ro\'Maeve. Realizing that only Shantotto can stand against Shantotto, Professor Yoran-Oran has proposed a rescue mission.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Sugar-coated Subterfuge'},
        next = {'Fountain of Trouble'},
        requirements = nil,
        walkthrough = '1. Click the Ensorcelled Door at (B-10) south-west corner in Ro\'Maeve.\n   - There is no cutscene, but you will be told about a "hexagonal depression" on the door.\n2. You must collect 6 Key Item fragments from various monsters:\n   - Note: If you are in a party/alliance, everyone in the group will obtain the Key Item if it drops.\n   - The fragments are not a guaranteed drop, but have a high drop rate.\n   - The NMs will despawn 5 minutes after being engaged and will respawn 2 minutes after either despawning or successfully being killed.\n3. When soloing with Trust, refer to the Damage Type table to select the appropriate Trust for each NM.',
        notes = nil,
    },
    ['Sisters in Arms'] = {
        id = 11,
        start_npc = nil,
        start_zone = 'Temple of Uggalepih',
        start_pos = 'H-9',
        description = 'Mission Orders: The two Shantottos have relocated their base of operation to the Sacrificial Chamber within the Temple of Uggalepih. Accompany Aldo and Professor Yoran-Oran there and put an end to this menace once and for all!',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Romancing the Clone'},
        next = {'Project: Shantottofication'},
        requirements = nil,
        walkthrough = '1. Your goal is to get to the Mahogany Door in the Sacrificial Chamber for a cutscene. Along the way, there will be glowing ???s in the Temple of Uggalepih and Den of Rancor that give tablet Key Items which will be helpful in the upcoming battlefield. Each tablet will grant a specific buff.\n   - At max level, you only need 1 tablet to get the cutscene from the Mahogany Door: one possible way is to warp to Den of Rancor Home Point #1, exit south via the switch, grab the [Key Item] Tablet of Hexes: Blight at (H-9), warp back to Den of Rancor Home Point #1, and continue to the Sacrificial Chamber.\n   - If you\'re attempting the upcoming battle below level 99, collecting all the tablets will make the fight easier.\nTablets can be found at the following locations:\n2. Tablets found in Temple of Uggalepih:\n   - Tablet of Hexes: Malice: (F-10) Map 1\n   - Tablet of Hexes: Deceit: (F-8) Map 1\n   - Tablet of Hexes: Envy: (F-8) Map 2\n   - Tablet of Hexes: Greed: (G-10) Map 2\n   - Tablet of Hexes: Pride: (J-11) Map 2\n   - Tablet of Hexes: Bale: (I-8) Map 2\n3. Tablets found in Den of Rancor:\n   - Tablet of Hexes: Regret: (E-5) Map 1\n   - Tablet of Hexes: Strife: (H-6) Map 1\n   - Tablet of Hexes: Dolor: (J-9) Map 1\n   - Tablet of Hexes: Agony: (E-10) Map 1\n   - Tablet of Hexes: Rancor: (F-11) Map 1\n   - Tablet of Hexes: Rage: (K-11) Map 1\n   - Tablet of Hexes: Despair: (J-13) Map 1\n   - Tablet of Hexes: Penury: (F-9) Map 3\n   - Tablet of Hexes: Death: (L-13) Map 2\n   - Tablet of Hexes: Blight: (H-9) Map 2\n4. In the Sacrificial Chamber, check the Mahogany Door and then check again to begin the fight for the next mission: Project: Shantottofication.',
        notes = nil,
    },
    ['Sugar-coated Directive'] = {
        id = 3,
        start_npc = 'Trodden Snow',
        start_zone = 'Qufim Island',
        start_pos = 'H-7',
        description = 'Mission Orders: Your inaugural mission as special operative of the Shantotto Empire requires you to attach enchanted seals to the protocrystals scattered across Vana\'diel. Your new empress has stressed that she takes failure poorly.',
        reward = '3,000-50,000 Gil',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'That Which Curdles Blood'},
        next = {'Enemy of the Empire (I)'},
        requirements = nil,
        walkthrough = '1. You are given 6 Key Item seals ([Key Item] Domina\'s scarlet seal, [Key Item] Domina\'s cerulean seal, [Key Item] Domina\'s emerald seal, [Key Item] Domina\'s amber seal, [Key Item] Domina\'s violet seal, [Key Item] Domina\'s azure seal) and instructed to attach at least 3 of them to the Protocrystals found around Vana\'diel.\n   - Protocrystals are found in the Cloister of Storms, Cloister of Frost, Cloister of Flames, Cloister of Tremors, Cloister of Tides and Cloister of Gales.\n2. Click each Protocrystal once, then click again for the option to enter a Battlefield entitled Sugar-coated Directive.\n   - Enter the battlefield and defeat a weakened version of the corresponding Prime Avatar.\n   - The Avatar will not die until it has tried to use its Astral Flow ability 5 times.\n3. After the battle, click the crystal again to attach the seal and receive a counterseal Key Item ([Key Item] Scarlet counterseal, [Key Item] Cerulean counterseal, [Key Item] Emerald counterseal, [Key Item] Amber counterseal, [Key Item] Violet counterseal, [Key Item] Azure counterseal).\n   - Note: If you leave the area before receiving the counterseal Key Item, you can simply return in order to obtain it; the battle is not repeated.\n4. Once at least 3 counterseals are obtained, return to the Trodden Snow at (H-7) in Qufim Island for a cutscene.\n5. You will receive a Gil reward that is dependent on the number of counterseals obtained:\n   - 3 seals: 3,000 Gil\n   - 4 seals: 10,000 Gil\n   - 5 seals: 30,000 Gil\n   - 6 seals: 50,000 Gil',
        notes = nil,
    },
    ['Sugar-coated Subterfuge'] = {
        id = 6,
        start_npc = 'Aldo',
        start_zone = 'Lower Jeuno',
        start_pos = 'J-8',
        description = 'Mission Orders: A candid conversation has cleared things up between you and Aldo. He bids you come to Tenshodo Headquarters in Jeuno in order to further discuss Shantotto\'s diabolical designs.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Enemy of the Empire (II)'},
        next = {'Shantotto in Chains'},
        requirements = nil,
        walkthrough = '1. Talk to Aldo at (J-8) inside Tenshodo Headquarters in Lower Jeuno for a cutscene.',
        notes = nil,
    },
    ['That Which Curdles Blood'] = {
        id = 2,
        start_npc = nil,
        start_zone = 'Southern San d\'Oria',
        start_pos = 'H-9',
        description = 'Mission Orders: You have been served what appears to be a draft card inducting you into the Shantotto Empire as a special operative. Report to provisional headquarters located on Qufim Island with extreme haste...and the specified gifts of tribute in hand.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Burgeoning Dread'},
        next = {'Sugar-coated Directive'},
        requirements = nil,
        walkthrough = '1. You are tasked with creating an Enfeeblement Kit of Silence, Enfeeblement Kit of Sleep, Enfeeblement Kit of Poison, or Enfeeblement Kit of Blindness.\n   - If you do not recall which item you have been tasked with creating, speak with one of the NPCs listed below. They will give you the recipes for making the components, but you do not have to talk to them at any point in the gathering of ingredients or the synthing of items.\n     - Kuroido-Moido at (E-7) in Port Windurst.\n     - Faulpie at (E-8) in Southern San d\'Oria.\n     - Abd-al-Raziq at (L-7) in Bastok Mines.\n2. For the kit, you will need:\n   - Padded Box: Earth Crystal, Bast Parchment x2, Inferior Cocoon (Can also be made from a Woodworking Kit 5 from guild NPC)\n   - Fine Parchment: Dark Crystal, Parchment, Pumice Stone (You will need to make two of these)\n   - Enchanted Ink: Dark Crystal, Black Ink, Magicked Blood (You will need to make two of these}\n   - A Silencing Potion, Sleeping Potion, Poison Potion, or Blinding Potion (It will depend on which enfeeblement kit you are told to make)\n3. Once you have obtained all the components, combine them together with an Earth Crystal.\n   - As a note, all of the components can be traded, but the enfeeblement kit itself cannot, and therefore must be synthed by the player doing the mission.\n   - Synths can fail, so it may be wise to have access to extra ingredients.\n   - An Alchemy level of 10 is recommended to synth the Enfeeblement Kit to increase the chances of success.\n4. Trade the kit to the Trodden Snow at (H-7) in Qufim Island for a cutscene.',
        notes = nil,
    },
}
