-- Mission data for mkd — extracted from BG Wiki (https://www.bg-wiki.com)
-- Generated: 2026-03-30
-- Total missions: 15
--
-- Fields: start_npc, start_zone, start_pos, description, reward, fame,
--         fame_level, title, repeatable, previous, next, requirements,
--         walkthrough, notes
-- Auto-generated from BG Wiki data.
-- Do not edit manually.

return {
    ['A Challenge! You Could Be a Winner'] = {
        id = 12,
        start_npc = nil,
        start_zone = 'Castle Zvahl Baileys',
        start_pos = 'J-8',
        description = 'A series of heart-stirring festival games, culminating in the purportedly profitable "Mega Mog Bonanza-Rama-Palooza"! Will our hero go home a champ, or a chump!?',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Joy! Summoned to a Fabulous Fete'},
        next = {'Smash! A Malevolent Menace'},
        requirements = nil,
        walkthrough = '1. Examine the Shadowy Pillar at Castle Zvahl Baileys (J-8), you will then be directed to Beaucedine Glacier.\n   - The fastest way is to teleport with the Survival Guide.\n2. Examine the Lonely Evergreen at the center of Beaucedine Glacier (G-7) for a cutscene.\n3. Go to the Tower at (H-8) to speak to Goblin Grenadier.\n   - You need a Map of the Northlands area to advance through this part of the mission.\n4. You will need to enter a combination to a chest.\n   - Hints are given by touching the 6 Pips in the area to spawn elemental NPCs.\n     - Make sure as the goblin says to not leave the zone or this will reset! The markers can be found in the green markers option of the map\n   - The elementals form a pattern following the days of the Vana\'diel week, so pay attention to the days which are directly next to each other.\n     - Firesday > Earthsday > Watersday > Windsday > Iceday > Lightningday > Lightsday > Darksday\n   - If you "connect the dots" following the pattern of the days of the week, it should form the number that you need. Imagine you are writing a number like an old alarm or clock.\n     - Days can loop around, so you can connect Fire - Dark.\n     - "Connecting the dots" only applies straight-across, and up or down. Connections cannot be made diagonally.\n     - The order of the pips themselves does not matter (north/south/clockwise/counter-clockwise/left/right/top/bottom/etc.).\n     - Recommend grabbing a piece of paper, drawing 6 dots, and drawing connecting lines between each pair of pips that are next to each-other in the Vana\'diel week. Do this pair by pair. (Can draw x\'s between each pair that are not next to each-other.) Then look at the number you have drawn.\n     - For example if the dots are in the order of Water > Earth > Dark > Fire > Light > Lightning from top left to right, top to bottom, the number would be 2.\n5. Speak to the Goblin Grenadier to guess the password, a number between 0-9. You may accept up to 2 additional hints before guessing.\n6. You will get a [Key Item] pocket mogbomb for opening the chest, as well as a Flee status effect (+60% movement speed) that lasts for 5 minutes if you did not use any hints.\n7. Return to the Lonely Evergreen at (G-7) to receive the [Key Item] Trivia Challenge Kupon.\n8. In Xarcabard you will find three Option spots.  Option One is at (G/H-8), Option Two is at (G-9), and Option Three is at (G-8).\n9. You must answer three questions correctly in order to win.  It does not matter which Option spot you select first.\n   - You will be asked 3 among the following trivia questions:\n     - HP+MP\n     - Job level sum\n     - Crafting skill sum (Synergy Excluded)\n     - Elemental resistance sum\n     - Total kills\n     - Attack x Defense\n     - Mog house entrances\n     - Total deaths\n     - Joined party\n     - Joined alliance\n10. You are given 2 options, each a number.  Do the following:\n   - Divide bigger number by smaller number.\n     - If value is  ~2, then the answer is the bigger number option\n     - If the value is ~1.5, then the answer is the smaller number option.\n   - One of the options may even be a 0 (crafting, for example); in this case it will be the 0 option.\n11. Upon winning, you will receive [Key Item] Gauntlet Challenge Kupon.\n12. Zone into Castle Zvahl Baileys and speak to the Shadowy Pillar by the zoneline.\n   - Your level will then be lowered to 1, and you will be granted Sneak, Invisible (Status) and Deodorize effects.\n     - The effect durations are random. They can be 3-7 minutes long.\n     - Prism Powder and Silent Oil is recommended in case you\'re unlucky with the amount of time you have the effect.\n   - You must reach the Flames of Fate before 8 minutes have passed since your level cap.\n   - The Flames of Fate are located right before the Castle Zvahl Keep zoneline. Completing this nets you a [Key Item] Festival Souvenir Kupon.\n     - Follow these directions if you are not familiar: from the Shadowy Pillar, follow the path into the Baileys until the first intersection. Take a right, then at the end of that path, turn and go down the stairs, take a quick left then right, then continue to stay to the right towards the map change at A on Map 1. This leads to Map 2.\n     - On Map 2, follow the path straight north (ignoring the option to turn left/west early on) and go up the stairs on the left when you see them. Do not go down any holes on the upper level, nor the the other set of stairs nearby. Instead, head southwest around the first hole and across the bridge leading west, to another section with a hole, where you will be able to turn right/north to go down completely different stairs. Take a right, staying on the lower floor, then another right crossing under the bridge you just passed. Take the first right past the bridge, then a left and another left that will lead you to some stairs back up to the upper level. Turn right and continue forward toward the exit to Castle Zvahl Keep. The flame is still within the Baileys, on the floor below the last torch on the left at (G-8) (you may wish to press toward the left when targeting). As you are presumably still Invisible, you will naturally need to drop Invis to click the flame.\n     - Make sure not to go past the flame/torches and up the huge stairs that zone into the next area, or you\'ll have to do a walk of shame back to the pillar!\n13. Upon zoning into Castle Zvahl Keep following the previous challenge, speak to the Ominous Pillar by the zone line (before you enter the large room ahead).\n   - You will be asked to find a slacking moogle. This can be done by examining Craggy Pillars located along the way to the Throne Room. Make sure you inspect a pillar after each teleport. Completing this nets you a [Key Item] Mega Bonanza Kupon.\n14. Craggy Pillars are pillars located somewhere in each room directly after taking one of the beastmen beacon teleporters. Remember, to get to the teleporter room, take either exit A or B (passing through Iron Gates and Ore Doors), then take exit C into Map 3. You\'ll be taking the teleporters up to 4 times, depending on which room your target is in.\n   - The 4th warp is the exception; the Craggy Pillar is in the next room to the south.\n   - Make sure not to accidentally zone into the next area, or you\'ll have to do a walk of shame back to the Ominous Pillar!\n15. After obtaining the [Key Item] Mega Bonanza Kupon, continue teleporting if need be to approach, then walk through, the Throne Room.\n16. Examine the Throne Room door for a cutscene.\n   - Watching the cutscene completes the mission.',
        notes = nil,
    },
    ['A Moogle Kupo d\'Etat'] = {
        id = 0,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'It all began with a raindrop, or so the legend says... Little did anyone suspect that this would prove to be only the beginning of a harrowing nightmare unheard of in the annals of mooglekind.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = nil,
        next = {'Drenched! It Began with a Raindrop'},
        requirements = nil,
        walkthrough = '1. Zone into your Mog House and speak to your Moogle while at level 10 or above for a cutscene.\n   - Must be your home nation Mog House. The cutscene will not trigger in a rent-a-room.',
        notes = nil,
    },
    ['A Moogle Kupo d\'Etat (Fin.)'] = {
        id = 14,
        start_npc = nil,
        start_zone = 'Throne Room',
        start_pos = nil,
        description = nil,
        reward = 'Ability to purchase [Key Item] Atma of Dread\n:One of the following:\nAnwig Salade \nChampion\'s Galea \nSelenian Cap',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Smash! A Malevolent Menace'},
        next = nil,
        requirements = nil,
        walkthrough = '1. Head to Tenshodo in Lower Jeuno and examine the Treasure Chest for your reward.\n   - The easiest way to repeat the fight to change your augmented item is to first toss it, then purchase the [Key Item] Mega Bonanza Kupon from Squintrox Dryeyes in Port Jeuno for 2,000 gil and 20 Beastmen Seals.\n     - This will allow you to quickly re-enter the BCNM in the Throne Room. Even with a [Key Item] Mega Bonanza Kupon, you will not be able to re-enter the BCNM if you still have the Angel skin key. You must first exchange it with the red chest in the Lower Jeuno Tenshodo.\n   - There is a Japanese Midnight wait on immediately repeating the fight. Otherwise you will receive the message: "Mega Bonanza Kupon has no effect. You cannot enter battlefield at present. Please wait a little longer".\n2. After the fight, you will immediately receive your key rewards.',
        notes = nil,
    },
    ['An Errand! The Professor\'s Price'] = {
        id = 5,
        start_npc = nil,
        start_zone = 'Outer Horutoto Ruins',
        start_pos = 'F-11',
        description = 'The Professor consents to lend you her aid, but as expected, there\'s a price to be paid. Within a Cardian in the Outer Horutoto Ruins lies the reagent she does seek; return it to her, that you might avert a fate most bleak!',
        reward = '[Key Item] Peach coral key\n[Key Item] Ripe starfruit',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Curses! A Horrifically Harrowing Hex'},
        next = {'Shock! Arrant Abuse of Authority'},
        requirements = nil,
        walkthrough = '1. Enter the Outer Horutoto Ruins from West Sarutabaruta (F-11).\n2. Kill Cardians in the area to get one (or more) of the following Key Items:\n   - [Key Item] Orb of Swords\n   - [Key Item] Orb of Cups\n   - [Key Item] Orb of Batons\n   - [Key Item] Orb of Coins\n3. After receiving the Orbs you want, zone into Outer Horutoto Ruins from East Sarutabaruta (H-3).\n4. Examine the ??? on top of the platform a (H-6) (it\'ll be right in front of you when you enter the zone) to begin a battlefield.\n   - Trust Magic can not be used in this battlefield.\n   - Up to 15 Custom Cardians will spawn and begin to attack.\n   - The player starting the battle will lose all of their possessed Orbs.\n   - The number and types of Orb key items in the possession of the player starting the battle will affect the number of Custom Cardians that spawn and damage type immunity:\n     - [Key Item] Orb of Swords removes slashing damage immunity.\n     - [Key Item] Orb of Batons removes blunt damage immunity\n     - [Key Item] Orb of Cups removes piercing damage immunity.\n     - [Key Item] Orb of Coins removes magic damage immunity.\n     - With 1 or 2 Orbs, 15 Cardians will appear.\n     - With 3 Orbs, 10 Cardians will appear.\n     - With all 4 Orbs, 5 Cardians will appear.\n   - Anyone else in the party with different Orbs, will lose them and not have their bonus granted.\n     - You receive 500 experience points, a [Key Item] Ripe starfruit, and a [Key Item] Peach coral key upon winning.\n5. Return to Shantotto. She will require you give her 5000 gil.\n6. Return to the Inconspicuous Door in Upper Jeuno (H-8) (across from Durable Shields) for a cutscene.',
        notes = nil,
    },
    ['Curses! A Horrifically Harrowing Hex'] = {
        id = 4,
        start_npc = 'Shantotto',
        start_zone = 'Windurst Walls',
        start_pos = 'K-7',
        description = 'When a missive from Boss Kupeliaure unexpectedly unleashes a calamitous curse, our hard-luck heroes seek out the aid of the esteemed yet eccentric exorcist Professor Shantotto.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Welcome! To My Decrepit Domicile'},
        next = {'An Errand! The Professor\'s Price'},
        requirements = nil,
        walkthrough = '1. Speak to Shantotto in Windurst Walls (K-7) for a cutscene. She will ask you for a [Key Item] Ripe starfruit.  This automatically starts the next mission.',
        notes = nil,
    },
    ['Drenched! It Began with a Raindrop'] = {
        id = 1,
        start_npc = nil,
        start_zone = 'Palborough Mines',
        start_pos = nil,
        description = 'With the ramshackle roof of your Mog House unable to withstand the elements, your moogle cohort entreats you to find three materials required for some much-needed renovations: an Orcish armor plate, a Quadav backscale, and a block of Yagudo caulk.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'A Moogle Kupo d\'Etat'},
        next = {'Hasten! In a Jam in Jeuno?'},
        requirements = nil,
        walkthrough = '1. Trade the following three items to your Moogle:\n   - Orc. Armor Plate dropped from Orcs in Yughott Grotto.\n   - Quadav Backscale dropped from Quadavs from Palborough Mines.\n   - Yagudo Caulk dropped from Yagudos in Giddeus.\nNOTE: They must be traded in the mog house of your current nation of allegiance, and all at once.',
        notes = nil,
    },
    ['Hasten! In a Jam in Jeuno?'] = {
        id = 2,
        start_npc = nil,
        start_zone = 'Upper Jeuno',
        start_pos = 'H-8',
        description = 'Word has it that the Rent-a-Room in Jeuno is also showing signs of spoilage. Unable to resist your moogle companion\'s earnest plea, you reluctantly agree to investigate the premises...',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Drenched! It Began with a Raindrop'},
        next = {'Welcome! To My Decrepit Domicile'},
        requirements = nil,
        walkthrough = '1. Examine the Inconspicuous Door in Upper Jeuno (H-8) (across from Durable Shields) for a cutscene.',
        notes = nil,
    },
    ['Joy! Summoned to a Fabulous Fete'] = {
        id = 11,
        start_npc = nil,
        start_zone = 'Castle Zvahl Baileys',
        start_pos = nil,
        description = 'What a thrilling turn of events! Toto has cleaned up his act and, as a sign of his newfound sincerity, has invited you and your bat-winged buddy to a magnificent Moogle Festival at Castle Zvahl!',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Relief! A Triumphant Return'},
        next = {'A Challenge! You Could Be a Winner'},
        requirements = nil,
        walkthrough = '1. Zone into Castle Zvahl Baileys for a cutscene that completes the mission and starts the next one.\n   - The fastest way is to teleport with a Survival Guide',
        notes = nil,
    },
    ['Lender Beware! Read the Fine Print'] = {
        id = 7,
        start_npc = nil,
        start_zone = 'Sea Serpent Grotto',
        start_pos = 'C-5',
        description = 'Oh, woe! Having exhausted all other options, your star-crossed moogle associate is forced to seek aid from the shadiest of scoundrels. You have an appointment with the underworld moneylender Riko Kupenreich at his office in Sea Serpent Grotto.',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Shock! Arrant Abuse of Authority'},
        next = {'Rescue! A Moogle\'s Labor of Love'},
        requirements = nil,
        walkthrough = '1. Travel to Sea Serpent Grotto and examine the Shady Sconce at (C-5) for a cutscene. You may need to do this twice to make sure it registers.\n   - Norg is the closest teleport.\n2. Use a Sahagin Key to enter the Ornamental Door at (J-11) in Sea Serpent Grotto.\n3. Continue to Sea Serpent Grotto map 5, then examine the Waterfall Basin at (H-6) for a cutscene.\n4. Return to the Inconspicuous Door in Upper Jeuno (H-8) (across from Durable Shields).',
        notes = nil,
    },
    ['Relief! A Triumphant Return'] = {
        id = 10,
        start_npc = nil,
        start_zone = 'Upper Jeuno',
        start_pos = 'H-8',
        description = 'The battle won and the fair maiden rescued, all is well for our plucky protagonists. What better time to return to the newly renovated Rent-a-Room for some much-deserved rest and relaxation...?',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Roar! A Cat Burglar Bares Her Fangs'},
        next = {'Joy! Summoned to a Fabulous Fete'},
        requirements = nil,
        walkthrough = '1. Return to the Inconspicuous Door in Upper Jeuno (H-8) (across from Durable Shields) for a cutscene that will complete this mission and start the next one.',
        notes = nil,
    },
    ['Rescue! A Moogle\'s Labor of Love'] = {
        id = 8,
        start_npc = nil,
        start_zone = 'Quicksand Caves',
        start_pos = nil,
        description = 'A dire development! Your moogle partner\'s betrothed, the fair Kupiruru, has been kidnapped by Toto\'s band of hoodlums! Make haste for the Chamber of Oracles to save the moogle maiden from a frightening fate!',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Lender Beware! Read the Fine Print'},
        next = {'Roar! A Cat Burglar Bares Her Fangs'},
        requirements = nil,
        walkthrough = '1. Make sure you possess the Map of the Quicksand Caves before you start! This is required.\n2. Head to Western Altepa Desert (D-12) or use Geomagnetic Fount Waypoint to get to Quicksand Caves map 5.\n   - Alternatively use Quicksand Caves Home Point #1 for the Chamber of Oracles and exit out from exit 5 of map 5 at (H-4) to Western Altepa Desert. Once out go south towards the hidden area of (D-12) that will bring you straight to the goblin at entrance 4.\n3. Speak to the Goblin Geologist at (J-11), he will ask you to gather 9 Key Items from ??? spots scattered around the Quicksand Caves.\n   - [Key Item] Stone of Surya\n   - [Key Item] Stone of Chandra\n   - [Key Item] Stone of Mangala\n   - [Key Item] Stone of Budha\n   - [Key Item] Stone of Brihaspati\n   - [Key Item] Stone of Shukra\n   - [Key Item] Stone of Shani\n   - [Key Item] Stone of Rahu\n   - [Key Item] Stone of Ketu\n4. The Goblin will mark the locations on your map, so if you do not possess a [Key Item] Map of the Quicksand Caves you will be unable to proceed with the mission. The markers will appear in the green Markers section.\n   - Due to the markers being saved locally and being random from a select pool of options it is advisable to finish the mission on the same PC you started this step in, in one go, or to make a backup/upload of the data.\n   - The markers do not clear after being collected so make sure to remember the ones you already got or you\'ll have to check them all again.\n   - You can use the "Change Map" option to check the green Markers in other maps and plan which entrances you may need to use.\n5. The following entrances can contain the needed ???:\nWestern Altepa Desert:\n6. (G-5) Entrance 6 to Quicksand Caves Map 5\n7. (J-9) Entrance 2 to Quicksand Caves Map 3,x Map 4\n   - Map 4 can be reached by going to (D-11) on Map 3, exit C.\nEastern Altepa Desert:\n8. (K-7) Entrance 1 to Quicksand Caves Map 1\n9. (H-10) Entrance 4 to Quicksand Caves Map 2\n10. These can require multiple one-way drops to reach, you should consider having an easy way to return to Eastern Altepa Desert such as Teleport-Altep and Instant Warp to get out of the maps/fix mistakes as needed, unless you want to walk through the maps.\n   - The Quicksand Caves Home Point #2 can be useful for some of these, as it brings you on Map 1 just outside of the Cloister of Tremors, also conveniently near Exit 3. Consider grabbing it on the way if you don\'t have it.\n11. Once you return to the Goblin Geologist with all nine stones, you will receive a [Key Item] Navaratna talisman.\n12. Enter the Chamber of Oracles and examine the Shimmering Circle for the cutscene that completes this mission.\n   - Home Point #1 just outside the Chamber of Oracles. It\'s a great time to unlock it if you don\'t have it already.\n   - If you have completed the Open Sesame quest for the [Key Item] Loadstone or you\'re a Galka, you can use the pressure pads to make your way to the Chamber of Oracles solo. Otherwise, you would need to stand on the pressure pads with other players (Trusts do not count): 3 Tarutaru or any combination of 2 of Hume/Elvaan/Mithra.\n   - Path from Goblin Geologist to Chamber of Oracles:\n     - Go to (I-9) and step on the weight pad and go through the door.\n     - Go west to (H-7) and use another weight pad to pass through a door.\n     - In the next room, drop down the hole to a hidden area.\n     - Head to (D-4) to zone in to the Chamber of Oracles.',
        notes = '1. None of the ??? require using the weight switches to open any door, but it is recommended you do the Open Sesame quest for the [Key Item] Loadstone if you haven\'t attuned to Quicksand Caves Home Point #1 and #2 as it a convenient time to do this.',
    },
    ['Roar! A Cat Burglar Bares Her Fangs'] = {
        id = 9,
        start_npc = nil,
        start_zone = 'Chamber of Oracles',
        start_pos = nil,
        description = 'What\'s this!? Toto has enlisted the services of the formidable feline filcher Nanaa Mihgo to guard his prize catch! Can you declaw the Cat Burglar, or will you end up as cat food?',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Rescue! A Moogle\'s Labor of Love'},
        next = {'Relief! A Triumphant Return'},
        requirements = nil,
        walkthrough = '1. In the Chamber of Oracles, examine the Shimmering Circle to enter the battlefield with the same name as the mission.\n   - Home Point #1 is the fastest way.\n2. In the battlefield, you will fight the following mobs:\n   - Nanaa Mihgo\n     - Nanaa Mihgo\'s normal melee attacks have the chance to give additional effect Paralyze, Stun, or Poison.\n     - Nanna Mihgo has access to normal Dagger weapon skills, such as Viper Bite, Wasp Sting, Dancing Edge, and Evisceration.  She also has access to a special weapon skill called: King Cobra Clamp that does conal damage and has an additional effect of Paralyze, Stun, and Poison.\n     - Twice during the fight Nanna Mihgo will summon either Bopa Greso or Cha Lebagta.\n   - Goblin Repossessor (THF)\n   - Goblin Intimidator (WAR)\n   - Goblin Enforcer (RDM)\n3. All of the mobs in the battlefield are susceptible to Sleep and Repose.  As Nanaa Mihgo is much stronger than the Goblins, it would be a wise strategy to sleep her while taking out the lesser threats.\n   - You only need to defeat Nanaa Mihgo to complete the battlefield\n   - Trust Magic can be used in this battlefield.\n4. Once completed you will receive a [Key Item] Red coral key and a cutscene and the next mission will begin.',
        notes = nil,
    },
    ['Shock! Arrant Abuse of Authority'] = {
        id = 6,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'When the linguistically challenged toady Toto Kupeliaure demands a ridiculous sum in unpaid rent, your moogle comrade chooses to make the ultimate sacrifice. Venture forth and unearth the moggy bank that contains his hard-earned wedding funds!',
        reward = nil,
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'An Errand! The Professor\'s Price'},
        next = {'Lender Beware! Read the Fine Print'},
        requirements = nil,
        walkthrough = '1. For this mission, you will be asked to go Chocobo Digging in a random zone.\n2. Head to the zone mentioned by your moogle and attempt to dig up its treasure, a [Key Item] Moldy, worm-eaten chest.\n   - You will need Gysahl Greens to make your chocobo dig.\n   - This may take multiple tries, so be sure to plan with a proper amount of Gysahl Greens.  (A stack, more in some cases.)\n   - Each time you dig you are given a general direction the treasure is as well as a hint about how close it is to your current location.\n     - When you get the message "You are convinced that your moogle friend has been digging in the immediate vicinity.", it means you are almost right on top of the treasure.\n3. Return to the Inconspicuous Door in Upper Jeuno (H-8) (across from Durable Shields) for a CS.',
        notes = '1. The digging hints are as follows.\n   - You have a hunch that this area would be favored by moogles : freezing cold\n   - You have a vague feeling that a moogle would enjoy traversing this terrain : very cold\n   - You suspect that the scenery around here would be to a moogle\'s liking : cold\n   - You have a feeling that your moogle friend has been through this way : warm\n   - You get the distinct sense that your moogle friend frequents this spot : hot\n   - You are convinced that your moogle friend has been digging in the immediate vicinity : very hot',
    },
    ['Smash! A Malevolent Menace'] = {
        id = 13,
        start_npc = nil,
        start_zone = 'Throne Room',
        start_pos = nil,
        description = 'Lying in wait in the castle\'s innermost chambers was not a generous jackpot, but a chilling confrontation! With a malevolent moogle poised to unravel not merely Mog House tradition but the very fabric of the universe, only our heroes can stand in his way!',
        reward = '[Key Item] Oxblood key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'A Challenge! You Could Be a Winner'},
        next = {'A Moogle Kupo d\'Etat (Fin.)'},
        requirements = nil,
        walkthrough = '1. Examine the Throne Room door to enter the BC.\n2. Once you enter the BC, you begin the fight against Riko Kupenreich.\n   - His basic attacks are special moves where he throws out bombs dealing conal AoE damage with knockback. Barfira seems to reduce the damage taken. Slow debuffs and Spikes will have no effect.\n   - Riko Kupenreich uses the following weapon skills.\n     - Washtub: AoE 200~400DMG, absorbed by 3 Shadows.\n     - Bill Toss: Terror\n     - Crystalline Flare: Draw-in and AoE 300~600 DMG with additional effect of Blind and Stun (~15 seconds).\n   - He has the ability to teleport within the arena.\n3. Upon taking 50% of his max HP in damage, Riko Kupenreich will summon 5 Henchmen Moogle Black Mages at his location and 2 Henchmen Moogle White Mages on top of the throne dias where he will retreat.\n   - The Black Mages are susceptible to sleep or lullaby, and can be killed.  They cast Tier III -ga and Tier IV spells.\n   - The White Mages cannot be damaged or slept and will repeatedly cast Cure V on Riko Kupenreich.\n   - Moogle Henchmen have the following weaponskills:\n     - Mog Shrapnel: Conal "Gil Toss" TP move, Does about 20~200DMG, Really Weak\n     - Mog Bomb: 200~400 DMG, Pretty Weak. Fire based of course.\n     - Flowerpot: single-target Amnesia, Bind, and Stun.\n   - After Riko Kupenreich is fully healed or the Black Mages are dead and despawned, he will return to the battle.\n   - He will do the Black Mage / White Mage adds phase a 2nd time after losing another 50% health.\n   - During the 3rd and final adds phase, Riko Kupenreich will spawn the Black Mages and does not retreat.\n     - This is the most dangerous part of the fight, as you\'ll be dealing with Crystalline Flare and the Black Mages at the same time.\n   - Riko Kupenreich fully resists Sleep spells. Is susceptible to Stun.\n4. Riko Kupenreich and his henchmen take increased damage from all sources, but also have very high HP.\n5. Once you win you will receive an [Key Item] Angel skin key and an [Key Item] Oxblood key.\n   - It possible to skip phase 2 by killing Riko extremely fast at 119 gear levels. (You can summon Trusts in this fight, if doing it before item level 119.)\n   - Should you fail during this fight, you will have to restart the process at Kupo Mission 13. (Note: you may start repeating the mission by returning to the Lonely Evergreen in Beaucedine Glacier. You do not need to start from checking the initial pillar back in Castle Zvahl Baileys.)',
        notes = nil,
    },
    ['Welcome! To My Decrepit Domicile'] = {
        id = 3,
        start_npc = nil,
        start_zone = 'Palborough Mines',
        start_pos = nil,
        description = 'Rotting roofboards, crumbling walls... Yes, this Rent-a-Room is a mess. Your moogle associate has the handyman skills; all he needs are a few essential items to make the requisite repairs.',
        reward = '[Key Item] Blue coral key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'Yes',
        previous = {'Hasten! In a Jam in Jeuno?'},
        next = {'Curses! A Horrifically Harrowing Hex'},
        requirements = nil,
        walkthrough = 'To streamline this walkthrough, collect all three key items in advance and complete all three cutscenes in one trip to save time.\n1. Go to Gusgen Mines or Palborough Mines or Ifrit\'s Cauldron and mine for the [Key Item] sturdy metal strip, return to Upper Jeuno and examine the Inconspicuous Door for a cutscene.\n2. Go to Jugner Forest or Ghelsba Outpost and log for the [Key Item] piece of rugged tree bark, return to Upper Jeuno and examine the Inconspicuous Door for a cutscene.\n3. Go to Giddeus or West Sarutabaruta and harvest the [Key Item] savory lamb roast, return to Upper Jeuno and examine the Inconspicuous Door (H-8) (across from Durable Shields) for a cutscene.\n4. These key items can be obtained in any order, even before the moogle even asks for them.\n5. Ensure your inventory is full before attempting to gather at a node, allowing repeated attempts to obtain the Key Item, as the node persists even if the gathered item can\'t be received, saving you the hassle of chasing new nodes when your sole goal is completing the quest.\n6. It can take anywhere from 3-5 attempts to even 50+ attempts.  Breaks are uncommon but can happen.  Bring at least 1 stack of each tool to avoid having to run back to town.',
        notes = nil,
    },
}
