-- Mission data for windurst — extracted from BG Wiki (https://www.bg-wiki.com)
-- Generated: 2026-03-30
-- Total missions: 22
--
-- Fields: start_npc, start_zone, start_pos, description, reward, fame,
--         fame_level, title, repeatable, previous, next, requirements,
--         walkthrough, notes
-- Auto-generated from BG Wiki data.
-- Do not edit manually.

return {
    ['A New Journey'] = {
        id = 12,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Heavens Tower',
        start_pos = nil,
        description = 'As requested by the Star Sibyl, you are to render service at the Embassy of Windurst in Jeuno. Great responsibility and tact are required.',
        reward = 'Rank 4\n5,000 Gil',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'Written in the Stars'},
        next = {'Magicite'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals (3+ if you skipped the previous mission) to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Check the Vestal Chamber door at the top of Heavens Tower for a cutscene with the Star Sibyl. You will receive [Key Item] Letter to the ambassador.\n2. Speak with Pakh Jatalfih at the Windurstian Embassy in Ru\'Lude Gardens (I-9) for a cutscene.\n   - If you already possess the Delkfutt Key  (trade it to the door) or the [Key Item] Delkfutt key (no trading needed) then you may skip this climb:\n     - Head to Lower Delkfutt\'s Tower (E-8) Map 1 and enter the Basement by clicking the Cermet Door.  Once you go through the door, proceed to (L-7) and click the Cermet Door for a cutscene. (Note: Another player using a key does not work.)\n     - Return to the Windurstian Embassy in Ru\'Lude Gardens and click the Door: Windurstian Emb. for a cutscene to complete the Mission.\n     - This is the 3rd door inside the embassy building. There are multiple doors with the same name.\n   - If you do not possess the Key, start the climb process detailed below:\n     - You may be Tractored through this Basement door without the Key. If you decide to go this route, proceed to the "Obtaining Delkfutt Key Short Way" section.\n     - Otherwise, read the "Obtaining Delkfutt Key Long Way" section.\n3. Head to Lower Delkfutt\'s Tower using the Survival Guide teleportation, Outpost warp, or Home Point warp.\n4. You will now likely need to climb to the 10th floor of Delkfutt\'s Tower in order to gain a Delkfutt Key  in order to access the Basement of the Tower:',
        notes = '1. You do not have to be on this Mission to receive a Delkfutt Key  from Porphyrion.',
    },
    ['A Testing Time'] = {
        id = 4,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Waters',
        start_pos = nil,
        description = 'Assist the Aurastery\'s School of Magic in the selection of the venue for their next skills test. They want to record the number of monsters you can hunt at a specific area, in a set number of days, to fairly standardize their skills test.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'Yes',
        previous = {'Lost for Words'},
        next = {'The Three Kingdoms'},
        requirements = nil,
        walkthrough = '1. Accept the mission from the Gate Guard.\n   - (Optional): As usual, you can speak to the gate guards for additional dialogue.\n2. Head to (L-6) in Windurst Waters and speak to Moreno-Toeno (inside the Aurastery), who gives you the [Key Item] "Creature Counter" magic doll to keep track of your objective.\n   - (Optional): You can talk to the students on the roof and the other NPCs in the same room as Moreno-Toeno for additional dialogue.\n   - You can save some time by setting your Home Point in Windurst Waters and bringing a Warp item.\n\nFirst-Time:\n\n3. Head to Tahrongi Canyon and start killing monsters.\n   - You have exactly 24 game hours (1 Earth time hour) to kill at least 30 monsters in the Canyon and return to Moreno-Toeno.\n4. Upon defeating 30 monsters, return to Moreno-Toeno.\n\nRepeating:\n\n5. Head to Buburimu Peninsula and start killing monsters.\n   - You have exactly 48 game hours (2 Earth time hours) to kill at least 30 monsters in the Peninsula and return to Moreno-Toeno.\n6. Upon defeating 30 monsters, return to Moreno-Toeno.\n\nGetting Assessed:\n\n7. Return to Moreno-Toeno in Windurst Waters and speak to him in the final game hour of the time limit. Speaking to him any sooner won\'t trigger the completion cutscene and speaking to him later will fail the Mission.\n   - This has lead to a lot of confusion over the years. If you are doing the Mission for the first time and accepted it at 06:00 game hour, he will only complete the Mission if the current time is between 05:00 and 06:00 on the next game day.\n8. You will fail this Mission if you do not return on time or defeat enough monsters. You will, however, be allowed to progress to the next Mission if you fill your Rank bar via other means.',
        notes = nil,
    },
    ['Awakening of the Gods'] = {
        id = 19,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Woods',
        start_pos = nil,
        description = 'Rhinostery minister Rukususu has traveled to Elshimo to investigate the facts concerning Iru-Kuiru, a researcher from thirty years past. The Rhinostery has asked you to bring Minister Rukususu back for her own safety.',
        reward = 'Rank 8\n60,000 Gil',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'The Sixth Ministry'},
        next = {'Vain'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Talk to Leepe-Hoppe on the roof of the Rhinostery, located in the southern half of Windurst Waters near Home Point #3.\n   - The correct dialogue involves Rukususu and Kerutoto.\n2. Talk to Kerutoto in the Rhinostery northern building for a cutscene.\n   - You may need to talk to her over 3 times.\n   - The correct cutscene is the one where she talks about Leepe-Hoppe and Rukususu, not the Diabolos one.\n     - If she continues to give you the cutscene for Diabolos, accept the Quest and talk to her twice to activate the cutscene needed for this Mission.\n   - Optional: Talk to Vanono in Kazham at (G-7) for a brief message.\n     - Before minister Rukususu returned to the mainly-mainlands, I was able to giver her my report on my findings here in Elshimo. She was very pleased with all the lovely-wuvly discoveries that we had made. But we couldn\'t have done it without the help of adventurers like you!\n3. Talk to Romaa Mihgo in Kazham at (H-11) in Mihgo\'s Residence.\n4. Travel to the Temple of Uggalepih. You will have to kill Bonze Marberry for a Cursed Key  ().\n   - If you\'re in a party, each player will require one.\n   - The key won\'t drop if you already have one. Check your storage.\n   - Bonze Marberry is located on Map 3 near (J-9). It will drop 2 keys per kill, and respawns every 5 minutes. This NM uses Everyone\'s Rancor, therefore it is recommended to reset your Tonberry Hate if your Hate is high and you\'re fighting him at a low level.\n   - Quick travel options: Use the Yhoator Jungle Outpost Warp, Unity Warp or Survival Guide. → Run to the Bloodlet Spring Den of Rancor entrance at (J-7) → From this entrance of Den of Rancor, follow the right wall until you zone in Temple of Uggalepih. This will directly lead you on Map 3. → Go upstairs and follow the left wall. The NM will be in the room at (J-9).\n5. After obtaining your Cursed Key, trade it to the Granite Door at (J-6) on the same map for a cutscene. You will receive [Key Item] Book of the Gods.\n   - Optional: Inspect three Tome of Magic.\n     - A workbook written by Iru-Kuiru. "That place was most definitely cursed. It was as if each of us were having our strings pulled by some unseen force..." "The Goddess only knows what that power was. I knew fear like I had never known before, and was struck mindless with panic before the terror that lurked within these walls."\n     - A diary written by Iru-Kuiru. "A letter has arrived from the homeland. The San d\'Orian member of the Allied Expedition, Francmage M Mistalle, has lost his life to the curse..." "And then yesterday, my friend and fellow Allied explorer, Yow Rabntah, was taken from this world..." "I can feel the shadow closing in on me. I believe the darkness will claim me before I am able to finish this research. And I was so close to putting all the pieces of this legend together..."\n     - A tome written on the subject of Fei\'Yin. "I would like to bring attention to the many small chambers that exist in the subterranean levels of the ruins of Fei\'Yin." "In each of these chambers stands an automaton. A golem, or giant, if you will. Were these golems given the task of sentry, or simply employed as servants?" "It is possible to conclude from the artifacts discovered in these ruins that it was once the abode of ancient people. One can further deduce from the evidence that this civilization was wiped out by some sudden calamity."\n6. Return to Leepe-Hoppe to complete the Mission.',
        notes = nil,
    },
    ['Doll of the Dead'] = {
        id = 22,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Woods',
        start_pos = 'H-9',
        description = 'The Orastery Minister has awoken and the Bearer of Darkness once again terrorizes Heavens Tower. At the request of the Manustery you are to speak with a person imprisoned within the Boyahda Tree and discover the truth behind the doll of the dead.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = 'Guiding Star',
        repeatable = 'No',
        previous = {'The Jester Who\'d Be King'},
        next = {'Moon Reading'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Talk to Apururu in Windurst Woods HP #1 inside the northern Manustery building (H-9) for a cutscene.\n2. Zone into Heavens Tower for a cutscene.\n   - Optional: Every NPC upstairs (past the Starway Stairway door) has unique dialogue to this mission. Now is your chance to hear what they have to say!\n3. Click the Door: Vestal Chamber on the top floor of the tower for a cutscene with the Star Sibyl.\n4. Return to Apururu for a cutscene.\n5. Trade Goobbue Humus  to the single Mandragora Warden in The Boyahda Tree at (F-4) in the hidden area of Map 1 for a cutscene. You will receive a [Key Item] Letter from Zonpa-Zippa.\n   - The pair of Mandragora Warden are the wrong ones.\n   - Goobbue Humus  is a drop from the Goobbue Gardeners () found in The Sanctuary of Zi\'Tah and Old Goobbues () found in The Boyahda Tree.\n   - Recommended to farm it with Treasure Hunter 8 (or any TH) in The Sanctuary of Zi\'Tah which has 13 spawns and 5 minutes respawn. All the Goobbue Gardener spawns are in the north-east and south-east section of the map.\n     - Easiest transportation option is the Level 122 The Sanctuary of Zi\'Tah Unity warp.\n6. Return to Apururu for a cutscene.\n7. Zone into Full Moon Fountain for a cutscene that completes the Mission.\n   - Home Point #1 to Toraimarai Canal is the fastest way.',
        notes = nil,
    },
    ['Full Moon Fountain'] = {
        id = 16,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Port Windurst',
        start_pos = nil,
        description = 'At the request of the Orastery, you are to go to the southwestern magic tower of the Horutoto Ruins. Deep within you will find a laboratory, where you are ordered to switch on the magical gizmo.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'The Shadow Awaits'},
        next = {'Saintly Invitation'},
        requirements = {
            {name = '[Key Item] Southwestern star charm', count = 1},
        },
        walkthrough = '1. Trade Crystals to a Conquest NPC to raise your Rank bar and unlock the mission. Accept it from any Gate Guard.\n2. Speak with Hakkuru-Rinkuru at the Orastery in Port Windurst to receive the Key Item "Southwestern star charm".\n3. Travel to West Sarutabaruta and enter the Dahlia Tower at (F-11) to reach Outer Horutoto Ruins.\n4. Navigate to Map 4 and interact with the Cracked Walls at (I-8) and (J-8).\n5. Examine the Gate to spawn four Jack Cardian NMs (magic-aggressive).\n   - Mages should keep distance as they aggro magic.\n   - They do not need to be defeated simultaneously.\n6. After defeating the Cardians, examine the door for a cutscene.\n   - If you get a "mysterious force" message, keep trying.\n7. Enter Full Moon Fountain in Toraimarai Canal (Map 1) to complete the mission.',
        notes = nil,
    },
    ['Lost for Words'] = {
        id = 3,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Waters',
        start_pos = 'G-8',
        description = 'There are reports that the Cat Burglar has her paws on a "Book of the Gods," a restricted book that was lost twenty years ago. Assist the Optistery in investigating the reports, and attempt to retrieve the priceless, but dangerous, tome.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'The Price of Peace'},
        next = {'A Testing Time'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals to the Conquest NPC (one crystal is enough) to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n(Optional): As usual for Windurst Missions, the Gate Guards and their adjacent NPCs will all have optional dialogue after accepting and at end of the Mission.\n1. Head for the Optistery on the northern map of Windurst Waters (near Home Point #1). Speak to Tosuka-Porika at (G-8) (East door).\n   - (Optional): The other NPCs and Tosuka-Porika inside the same room have additional dialogue.\n2. Head to (J-3) in Windurst Woods and speak to Nanaa Mihgo. She will lend you her [Key Item] Lapis monocle.\n   - You may need to talk to her twice or more if you have a [Key Item] Windurst Trust permit and Aht Urhgan Lure of the Wildcat Quests started.\n   - (Optional): Nanaa\'s cronies nearby have additional dialogue.\n\nMaze of Shakrami:\n\n3. Now make your way to the Maze of Shakhrami, which is in at (K-5) in the northeast corner of Tahrongi Canyon.\n   - The Survival Guide places you at the entrance of Maze of Shakhrami so long as you have it unlocked.\n   - The Unity Warp to Tahrongi Canyon, Kulshushu Outpost, or Mea crag warps can otherwise save some time.\n4. Inside, head for (G-6) on Map 1, where you can transition to Map 2 (the lower map). Then, head to (H-5) on Map 2.\n5. Check each Fossil Rock until you receive the [Key Item] Lapis coral.\n   - There are about 12 Fossil Rocks on Map 2.\n   - There are Fossil Rocks at (H-5),(I-7),(H-7),(G-7),(G-8),(I-8).\n   - Many mobs aggro  sound, while s will aggro to  sight, so keep Sneak (Status) and Invisible (Status) up if you are a lower-level player. You can use Circumspection from the Grounds Tome if necessary.\n6. Make your way back to Nanaa Mihgo, who will give you the [Key Item] Hideout key.\n   - (Optional): Nanaa\'s cronies have new additional dialogue.\n\nInner Horutoto Ruins:\n\n7. Head to East Sarutabaruta, and enter the Lily Tower at (J-7) to reach Inner Horutoto Ruins.\n   - The Inner Horutoto Ruins Survival Guide warp places you in the right tower if you have it unlocked already.\n8. Head to the Southwest room containing an Ancient Magical Gizmo. At (G-9), there is a Cracked Wall. Open it to proceed to Inner Horutoto Ruins Map 2. Now head for (G-8). There are a few ways to get there, but ultimately that is your destination.\n   - You will need Sneak and Invisible due to high level (90+) monsters in the area.\n     - Silent Oil and Prism Powder are alternatives to Sneak and Invisible.\n   - This also includes potential  blood aggro, so be sure you are above 75% HP.\n     - Without Sneak and Invisible: Beetles and Bats do not aggro here. There is a path to the door without Goblins and Skeletons, allowing you to pass safely.\n9. Check the Mahogany Door for a cutscene.\n   - (Optional): Nanaa and her cronies back in Windurst Woods have new additional dialogue after this cutscene.\n\nWindurst:\n\n10. Head to the House of the Hero at Windurst Walls (G-3). Check the door for a cutscene.\n11. Make your way back to Windurst Waters Home Point #1 and speak to Tosuka-Porika to complete the Mission.\n   - (Optional): Some of the NPCs in the same room have new additional dialogue.',
        notes = nil,
    },
    ['Magicite'] = {
        id = 13,
        start_npc = 'Pakh Jatalfih',
        start_zone = 'Ru\'Lude Gardens',
        start_pos = 'I-9',
        description = 'You must obtain three magicite items from different dungeons to prevent the Shadow Lord\'s resurrection.',
        reward = 'Rank 5\n10,000 Gil\nAirship Pass (or 20,000 Gil if already owned)',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'A New Journey'},
        next = {'The Final Seal'},
        requirements = {
            {name = '[Key Item] Tenshodo membership card', count = 1},
        },
        walkthrough = '1. Visit the Windurstian Embassy in Ru\'Lude Gardens and speak with Pakh Jatalfih (I-9) for a cutscene.\n2. Go to the Audience Chamber in Ru\'Lude Gardens (H-6) for another cutscene.\n3. Speak with Aldo in Neptune\'s Spire in Lower Jeuno.\n   - Requires Tenshodo membership (from the "Tenshodo Membership" quest in Lower Jeuno).\n4. Obtain the three magicites from separate dungeons:\n   - Magicite: Optistone — Monastic Cavern in Davoi\n   - Magicite: Orastone — Altar Room in Castle Oztroja\n   - Magicite: Aurastone — Qulun Dome in Beadeaux\n   - Each dungeon requires specific key items to access the magicite rooms.\n5. After collecting all three, return to the Audience Chamber (H-5) in Ru\'Lude Gardens for a cutscene.\n6. Speak with Pakh Jatalfih to complete the mission.',
        notes = 'This mission is identical across all three nations. Prerequisite quests for dungeon access do not need to be repeated if completed on a different nation.',
    },
    ['Moon Reading'] = {
        id = 23,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Walls',
        start_pos = nil,
        description = 'To lure the Bearer of Darkness to the Full Moon Fountain, you must collect the three verses of the ancient people. As her guiding star, the Star Sibyl is counting on you to help her decide the path for Windurst\'s future. The fate of Windurst rests upon your shoulders!',
        reward = 'Rank 10\n100,000 Gil\nWindurstian Flag\nAbility to buy [Key Item] Atma of the Full Moon',
        fame = nil,
        fame_level = nil,
        title = 'Vestal Chamberlain',
        repeatable = 'No',
        previous = {'Doll of the Dead'},
        next = nil,
        requirements = nil,
        walkthrough = 'Trade enough Crystals to the Conquest NPC to raise the Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Optional: Talk to everyone from Kupipi and beyond for unique dialogue to this part of the mission within Heavens Tower. The guards just before the teleporter in Windurst Walls will also vary at different points in these missions.\n   - After the upcoming cutscene on the top floor, the dialogue will also be changed for 3 of the 4 Mithra on the top floor closest to the chamber (Shaz Norem\'s does not change).\n   - All this dialogue will change yet again after the BCNM of this mission, so before then is your only opportunity to experience it.\n2. Click the Door: Vestal Chamber on the top floor of Heavens Tower for a cutscene about the Star Sibyl.\n3. Collect the following 3 Key Items in any order:\n4. Interact with the Qu\'Hua Spring in Ro\'Maeve at (H-6).\n   - Survival Guide warp is recommended.\n5. Zone into Chamber of Oracles.\n   - Quicksand Caves Home Point #1 is the quickest way to this location.\n   - Alternatively: use the Western Altepa Desert (D-12) entrance of Quicksand Caves. You will need Sneak. You will need to open the pressure switch door at (I-9).\n     - This can be done solo if you posses a [Key Item] Loadstone from the Quest Open Sesame or with the required amount of people.\n     - Requires 3 points to open the doors: Galka = 3 points; Hume/Elvaan/Mithra = 2 points; Tarutaru = 1 point.\n   - Keep left to enter Chamber of Oracles.\n6. Interact with the ??? in Temple of Uggalepih (E-8) Map 2.\n   - An Uggalepih Key  (), dropped from Tonberry Cutters on Map 2, is needed to open the Granite Door to get to the ???.\n   - Unity Warp Level 125 Temple of Uggalepih is the quickest route to this location.\n   - Alternatively: use the Temple of Uggalepih Survival Guide to Map 1, go north to Yhoator Jungle then head west to re-enter and reach Map 2 of the Temple.\n   - Players 75+ do not aggro.\n7. Return to the Door: Vestal Chamber in Heavens Tower for a cutscene.\n8. Go to Full Moon Fountain and clear a two-part BCNM.\n   - Fastest path to this location is through Toraimarai Canal Home Point #1.\n   - Alternatively, you can use the Survival Guide to reach Toraimarai Canal.\n\nBCNM:\n\n9. Commands to unload them: //lua u enternity - /addon unload enternity - //lua unload fastcs - //config FrameRateDivisor 2\n10. If you crash the game after completing the BCNM, the top door will not provide a cutscene. The remedy is to click the blank, glowing spot right outside of Heavens Tower to complete Rank 10.\n11. Not everyone has this issue but if you do the above should work for you.\n----\nThe BCNM fight is trivial at 99. Trusts can be summoned.\n12. The first part is against four Ace Cardians:\n   - A good strategy is to cast Sleepga on them and and kill Ace of Batons (BLM) → Ace of Swords (PLD) → Ace of Coins (RDM). Sleep Ace of Cups (WHM) and rest to full.\n   - The Cardians will eventually start resisting Sleep. However, unless you take a long time to kill the first three it should not be a problem.\n   - The Cardians will aggro from outside casting player casting range. The Ace of Swords will move to melee range while the other three will cast before moving.\n   - As soon as the last Cardian dies you will get a cutscene.\n13. The next fight is with a  and a .\n   - You will be assisted by Ajido-Marujido. If he dies, you lose the fight, so be sure to cure him. Kill what Ajido-Marujido decides to fight first.\n   - Letting Ajido-Marujido choose will aggro both NMs. Be prepared to pull both off of him.\n14. Optional: Talk to Kupipi for optional dialogue which will change once you\'ve reached Rank 10.\n   - Everyone else upstairs has new lines again, but they won\'t change after completion of the mission.\n15. Return to the Door: Vestal Chamber in Heavens Tower for a cutscene.\n16. Click the Door: Vestal Chamber again for the final cutscene with the Star Sibyl and to end the Windurst story line.',
        notes = nil,
    },
    ['Saintly Invitation'] = {
        id = 17,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Heavens Tower',
        start_pos = nil,
        description = 'A mission issued by Heavens Tower. In reply to the Yagudo Holy One\'s invitation, you are to compete and triumph at the contest held at Balga\'s Dais deep within Giddeus.',
        reward = 'Rank 7\n40,000 Gil\nAshura Necklace',
        fame = nil,
        fame_level = nil,
        title = 'Hero on Behalf of Windurst, Victor of the Balga Contest',
        repeatable = 'No',
        previous = {'Full Moon Fountain'},
        next = {'The Sixth Ministry'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Select the Door: Vestal Chamber at the top of Heavens Tower for a cutscene.\n   - You will receive [Key Item] Holy One\'s invitation and the title: "Hero on Behalf of Windurst".\n2. You will have to proceed to Balga\'s Dais located in Giddeus, and clear the BCNM "Saintly Invitation". You will receive the [Key Item] Balga champion certificate.\n   - Home Point #1 to Giddeus is the fastest way.\n\nBCNM:\n\nNote: If you\'re in a party with other players, only players that are on this Mission or have completed it may enter the BCNM.\n3. Inside are 4 NM Yagudo. They can use their respective 2-hours.\n   - Nuu Kofu the Gentle (WHM)\n   - Chaa Paqa the Profound (SMN)\n   - Buu Xolo the Bloodfaced (SAM)\n   - Juu Zeni the Poisonmist (NIN)\n4. The Yagudo may be slept.\n5. It is recommended to fight in the order of WHM → SMN → SAM → NIN.\n6. It may be useful to pull the WHM out of AoE range, so that it does not wake the others up with Benediction.\n7. Trio of 75WHM/NIN 75RDM/BLM 75BLM/WHM can win with relative ease. Fought in order of SMN → WHM → SAM → NIN to remove the elemental for sleep reasons.\n\nCastle Oztroja:\n\n8. Once you win the BCNM, proceed to Castle Oztroja located in Meriphataud Mountains.\n   - The Survival Guide will teleport you at the main entrance.\n9. You will need to reach the Brass Door located on the top floor of the Castle (Map 4, H-5). The door requires a   which drops from Yagudo Flagellants in the same map.\n\nMaps:\n\n10. Starting from the main entrance on Map 1, go through the first Brass Door (I-8) by turning the correct lever and go upstairs at point A.\n   - Note: While standing in between the two levers, pull one and move away immediately. It will either open the Brass Door, or a trapdoor which can cause you to fall. If the trapdoor opens, wait for it to close and try the other lever. Which lever controls which door changes every day.\n11. You\'ll now be on Map 2. Proceed west towards the next Brass Door (G-8). This particular door requires a combination of 4 levers to be opened. While you can find the solution, you can also easily brute force by turning the levers until it opens.\n12. Go upstairs at point G and you\'ll be on Map 3. Go straight to point H and you\'ll be on Map 4.\n   - Kill Yagudo Flagellants on Map 4 until you drop the required Judgment Key.\n13. Open the the large Brass Door by interacting with the unlit Torch in one of the four corner rooms.\n   - A second person may help with this and can just run in after this and open it from the inside.\n14. Next, you will need to crack the passwords to the Brass Statue to unlock the trapdoor.\n   - Visit the Brass Statue page to see possible combinations and further details.\n15. After the fall, proceed to a smaller Brass Door on the platform, which is past one Yagudo High Priest in this area. The priest is true sight.\n16. Trade the Judgment Key to the Brass Door. The Key has one use only, if you\'re in a party make sure your party/alliance members are ready to enter.\n   - If someone does not make it through the door before it closes, there are two options: get another Key, or have the person die outside the door, then use tractor and raise.\n17. Speak to Kaa Toru the Just inside the door to obtain the [Key Item] Holy One\'s oath and an Ashura Necklace.\nReturn to the Door: Vestal Chamber at the top of Heavens Tower to complete the Mission.',
        notes = nil,
    },
    ['The Final Seal'] = {
        id = 14,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Walls',
        start_pos = nil,
        description = 'On the Star Sibyl\'s command, you are to head north to the ruins of Fei\'Yin, somewhere on the Beaucedine Glacier. There, you are to confirm whether the final seal is doing its job.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = 'Archmage Assassin',
        repeatable = 'No',
        previous = {'Magicite'},
        next = {'The Shadow Awaits'},
        requirements = nil,
        walkthrough = 'Head to Heavens Tower in Windurst Walls HP #1.\n1. Click the Door: Vestal Chamber at the top of the Tower to start the Mission and to receive [Key Item] New Fei\'Yin seal.\n   - If you are low level, you might want to use Trusts or form a party of lvl 50+ players.\n2. Go to Fei\'Yin (located in the northeast corner of Beaucedine Glacier) for a cutscene with Zeid. You will have to reach the Qu\'Bia Arena and clear the BCNM "The Rank 5 Mission".\n   - The majority of enemies in Fei\'Yin detect by  sound, however there are several that detect  spellcasting.\n   - Quick Travel options:\n     - Home Point #1 to Fei\'Yin is the fastest way, it puts you right at the zone to Qu\'Bia Arena.\n     - Unity Warp (Level 128) will place you at the entrance of Fei\'Yin.\n     - Unity Warp (Level 125) will place you in the central area of Beaucedine Glacier.\n   - From the entrance of Fei\'Yin:\n     - Go east to (K-8). There are 2 Dolls in front of a door named Cermet Portal, open it and you\'ll be able to enter Qu\'Bia Arena.\nYou will be able to prepare outside of the BC, however all buffs will wear upon entering. Plan accordingly and click the Burning Circle when ready.\n3. You only need to kill the Archlich to win.\n4. You will be facing Archlich Taber\'quoan. The Archlich will spawn with 2 Ancient Sorcerers. Ancient Warriors will also spawn in the hallway and run into the arena to help the Archlich during the fight.\n   - The Archlich is a BLM, and will cast spells like Sleepga II and Freeze, he may also use Manafont.\n   - The lesser skeletons have very little HP and can be easily taken out by an AoE spell.\n   - Focus attacks on the Archlich, a Paladin with Invincible is useful for managing the many extra mobs. A Monk using Hundred Fists also shines in this fight, due to the skeleton blunt penalty.\n5. When you win, you\'ll be given another cutscene and receive [Key Item] Burnt seal.\nYou can head back to the Heavens Tower.\n6. Check the Door: Vestal Chamber at the top to complete the Mission.',
        notes = nil,
    },
    ['The Heart of the Matter'] = {
        id = 1,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Waters',
        start_pos = 'F-5',
        description = 'Assist the Manustery in the creation of Cardians. You must go to the southeastern magic tower of the Horutoto Ruins in East Sarutabaruta, and energize the Mana Orbs that serve as the hearts of the Cardians. Inquire at the Manustery first for details.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'The Horutoto Ruins Experiment'},
        next = {'The Price of Peace'},
        requirements = nil,
        walkthrough = '1. Accept the Mission from any Gate Guard.\n   - Mokyokyo - Windurst Waters (F-5)\n   - Janshura-Rashura - Port Windurst (B-5)\n   - Rakoh Buuma - Windurst Woods (K-10)\n   - Zokima-Rokima - Windurst Walls (H-7)\n2. Then make your way to the Manustery in Windurst Woods, Speak to Apururu who is at (H-9).\n   - You may need to talk to her twice if you have a [Key Item] Windurst Trust permit as she will mention talking to her brother, Ajido-Marujido.\n3. You will receive the following Mana Orbs Key Items:\n   - [Key Item] First dark Mana Orb\n   - [Key Item] Second dark Mana Orb\n   - [Key Item] Third dark Mana Orb\n   - [Key Item] Fourth dark Mana Orb\n   - [Key Item] Fifth dark Mana Orb\n   - [Key Item] Sixth dark Mana Orb\n4. You are now instructed to go to the Outer Horutoto Ruins.\n5. Head to (J-11) in East Sarutabaruta and speak to Pore-Ohre at the entrance to Marguerite Tower, they will give you the [Key Item] Southeastern star charm.\n   - Make sure you get this, or you will be unable to energize the orbs later on.\n6. Check the six pedestals to place a Mana Orb.\n   - Examine the Cracked Walls along the north and south sides to find hidden rooms, which contain 2 more pedestals for your Mana Orbs.\n7. After all orbs have been set, pass through the Cracked Wall on the east side and then examine the Gate: Magical Gizmo behind it for a cutscene.\n8. After the cutscene, check each pedestal again to retrieve the 6 Glowing Mana Orb Key Items:\n   - [Key Item] First glowing Mana Orb\n   - [Key Item] Second glowing Mana Orb\n   - [Key Item] Third glowing Mana Orb\n   - [Key Item] Fourth glowing Mana Orb\n   - [Key Item] Fifth glowing Mana Orb\n   - [Key Item] Sixth glowing Mana Orb\n9. When you\'ve collected all 6, head back out of the tower. When you zone, you\'ll receive another cutscene.\n   - (Optional): You can speak to Quh Berhuja nearby for some dialogue.\n   - Alternatively, you can use any means of leaving the zone that will not lead you to East Sarutabaruta. Doing this will allow you to skip the cutscene and go straight back to Apururu will which lead to a slightly different cutscene upon finishing the Mission.\n10. Head back to the Manustery and speak to Apururu to complete the Mission.',
        notes = nil,
    },
    ['The Horutoto Ruins Experiment'] = {
        id = 0,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Waters',
        start_pos = 'F-5',
        description = 'The minister of the Orastery in conducting an experiment in the eastern magic tower of the Horutoto Ruins, located in East Sarutabaruta. Inquire at the Orastery first, then go assist him.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = 'Title based on :Category:Gate Guard',
        repeatable = 'No',
        previous = nil,
        next = {'The Heart of the Matter'},
        requirements = nil,
        walkthrough = '1. Speak to any Windurstian Gate Guard, and accept the Mission.\n   - Mokyokyo - Windurst Waters (F-5)\n   - Janshura-Rashura - Port Windurst (B-5)\n   - Rakoh Buuma - Windurst Woods (K-10)\n   - Zokima-Rokima - Windurst Walls (H-7)\n2. Head for the Orastery in Port Windurst. Speak to Hakkuru-Rinkuru at (E-7) for a cutscene.\n3. Make your way to (J-7) in East Sarutabaruta. You\'re looking for a large stone tower.\n   - The Inner Horutoto Ruins Survival Guide places you at the right tower if you have it unlocked already.\n4. (Optional): Speak to Sama Gohjima near the entrance for some dialogue.\n5. Head down the stairs to the Inner Horutoto Ruins.\n6. Inside, you\'ll be in the Lily Tower on Map 1. Go down the stairs in to the main room.\n7. Run to the other side, and look for the Cracked Wall, around (H-9). Pass through it and go left.\n8. Check the Gate: Magical Gizmo at (I-9) for a cutscene with the Minister.\n9. Now, head back out and check the six different Ancient Magical Gizmos until you are given the [Key Item] Cracked Mana Orb. It will be at a random Gizmo.\n10. Head back to Hakkuru-Rinkuru and speak with him to finish the Mission.',
        notes = nil,
    },
    ['The Jester Who\'d Be King'] = {
        id = 21,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Woods',
        start_pos = nil,
        description = 'The time for the Dark Dungeon jailbreak is at hand! At the request of the Manustery, you are to collect the ministry rings from all five ministers.',
        reward = 'Rank 9\n80,000 Gil',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'Vain'},
        next = {'Doll of the Dead'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals to the Conquest NPC to raise the Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Talk to Apururu in Windurst Woods HP #1 inside the northern Manustery building for a cutscene. You will obtain the [Key Item] Manustery ring.\n2. Talk to the following NPCs, in any order, to receive the [Key Item] Rhinostery ring, [Key Item] Aurastery ring, and [Key Item] Optistery ring:\n   - Rukususu in Fei\'Yin at (F-6) on Map #2. Click the Cermet Door of the north-western small room for a cutscene with her.\n     - Home Point #2 to Fei\'Yin is the fastest way.\n   - Sedal-Godjal in Davoi (J-8). He can only be reached by going through Monastic Cavern. Enter Monastic Cavern from entrance 2 at (H-11) in Davoi. Once you\'re in, hug the right wall and exit at (H/I-8). Once you\'re back in Davoi, you can reach Sedal-Godjal by going east.\n     - Proto-Waypoint to Davoi is the fastest way. Drop into the water, follow the water south-east to (J-10) to get back on land, then hug left until you reach entrance 2.\n     - Survival Guide to Davoi is almost as fast.\n   - Tosuka-Porika in Windurst Waters North HP #1, inside the eastern Optistery building.\n3. Return to Apururu for dialogue regarding the final ring.\n----\n4. Talk to Kupipi in Heavens Tower for a cutscene.\n5. Go to the tower in West Sarutabaruta (F-4) and enter Outer Horutoto Ruins.\n   - Outer Horutoto Ruins Voidwatch warp or West Sarutabaruta\'s Geomagnetic Fount puts you right in front of this tower.\n   - Warping to the outpost/Survival Guide for West Sarutabaruta or warping to Giddeus and using Escape are the next best options.\n6. Go through the Cracked Wall at (I-6).\n7. Find the Cracked Wall at (G-8) on the second map. Touch it and pop Queen of Coins (RDM) and Queen of Swords (PLD).\n8. Click the Cracked Wall again (multiple times if needed) after defeating them for a cutscene and to obtain the [Key Item] Orastery ring.\n9. Return to Apururu for a cutscene.\n10. Talk to Shantotto in Windurst Walls at (K-7) for a cutscene and to obtain the [Key Item] Glove of perpetual twilight.\n   - You may need to speak to Shantotto multiple times for the correct cutscene.\n11. Return to Apururu for a cutscene.\n12. Go to Inner Horutoto Ruins and examine the Gate of Darkness at (I-7, south-eastern door) on Map 4 for a cutscene.\n   - Fastest way is using the Toraimarai Canal Survival Guide and then back tracking to Horutoto ruins.\n   - Alternatively, travel though Toraimarai Canal using the Priming Gate in Windurst Walls (H-3).\n   - You need to pass through the Three Mage Gate if you do not enter via the Toraimarai Canal.\n13. Return to Apururu for a cutscene that completes the Mission.\n   - (Optional) Return to Shantotto for dialogue regarding the [Key Item] Glove of perpetual twilight.\n     - Ohohohoho! It looks like my glove of perpetual twilight had the desired effect! Ajido-Marujido\'s failure tor egain consciousness is the only slight complication I was able to detect... But you don\'t need to go and start worrying. Why, it would take mor than that to finish of fa mage that had survived my tutelage and training! ...Now, about the glove of perpetual twilight. Due to a slight miscalculation on my part, the rings have become fused to the glove, I see. But don\'t worry. With a few twists, I\'ll soon have them free. I\'ll just hold on to the ministry rings for a little while longer. Ohohoho!\n   - (Optional) Return to Tosuka-Porika to report about the Book of the Gods as promised.\n     - Where have you been? Did Ajido-Marujido get the book open!? ...Hrmm, he\'s fallen into a coma, has he...? He must\'ve been drawn into the "World of the Book." If he manages to return to consciousness, he will have all the knowledge contained within the Book of the Gods. ...If he makes it back, that is.',
        notes = nil,
    },
    ['The Price of Peace'] = {
        id = 2,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Waters',
        start_pos = 'F-5',
        description = 'Recieve two bags of food offerings from the Rhinostery, and deliver one bag to each of the Yagudo who stand by the altars of offerings in Giddeus. Don\'t forget to report back to the Rhinostery after completing the mission.',
        reward = 'Rank 2\n1,000 Gil',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'The Heart of the Matter'},
        next = {'Lost for Words'},
        requirements = nil,
        walkthrough = '1. Accept the Mission from any Gate Guard.\n   - Mokyokyo - Windurst Waters (F-5)\n   - Janshura-Rashura - Port Windurst (B-5)\n   - Rakoh Buuma - Windurst Woods (K-10)\n   - Zokima-Rokima - Windurst Walls (H-7)\n2. Then make your way to the roof of the Rhinostery in Windurst Waters (J-8) (near Home Point #3), it is located in the southern half of the zone.\n   - Speak with Leepe-Hoppe at (J-9) on the roof of the Rhinostery. He will give you the [Key Item] Food offering and [Key Item] Drink offering.\n3. Head out for Giddeus, which is located at (F-8) in West Sarutabaruta.\n   - If you previously unlocked it, you can teleport directly to (G-12) with Home Point #1 and make your way north from there.\n4. Make your way to (H-7) and speak to a Yagudo NPC named Laa Mozi to hand over the [Key Item] Food offering.\n   - You can reach this NPC by taking all left turns from the Sarutabaruta entrance.\n5. Next, head to (G-7) and speak to a Yagudo NPC called Ghoo Pakya to hand over the [Key Item] Drink offering.\n   - Return to the Sarutabaruta entrance and take all right turns to reach this NPC.\n6. Head back to the Rhinostery. As you climb the stairs to the roof, you\'ll receive another cutscene.\n7. Return to the Gate Guard to complete the Mission.',
        notes = nil,
    },
    ['The Shadow Awaits'] = {
        id = 15,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Castle Zvahl Keep',
        start_pos = nil,
        description = 'As written in the stars and interpreted by the Star Sibyl, you are to destined to journey to Castle Zvahl, which towers over Xarcabard, the end of the known lands. There, you are to witness what fate has in store for our world.',
        reward = 'Rank 6\nUnlock Zilart Missions\nUnlock Dynamis\n20,000 Gil\nTrust: Ajido-Marujido',
        fame = nil,
        fame_level = nil,
        title = 'Star-ordained Warrior, Shadow Banisher',
        repeatable = 'No',
        previous = {'The Final Seal'},
        next = {'Full Moon Fountain'},
        requirements = nil,
        walkthrough = 'Trade 2+ Crystals to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard. You will receive [Key Item] Star crested summons.\n1. Head to the top of the Heavens Tower in Windurst Walls HP #1 and click the Door: Vestal Chamber.\n   - If you\'re not using Trusts and are level 55-60, form a full party of players.\nYou will have to reach the Throne Room in Castle Zvahl Keep and clear the BCNM "The Shadow Lord Battle".\n2. Castle Zvahl Keep Home Point #1 is fastest way. If you don\'t have the HP unlocked already, check the instructions below.\n3. After you clear the BCNM, you\'ll get another cutscene. At the end, you\'ll be returned to the entrance of Castle Zvahl Baileys. You will also receive the [Key Item] Shadow fragment.\n   - You can start the Zilart Missions and continue with Rhapsodies of Vanadiel Mission 1-12 from this point on, ranking up is optional.\n4. Zone into Heavens Tower for a brief cutscene.\n5. Click the Door: Vestal Chamber for a final cutscene and your reward: Rank 6 and 20,000 Gil.\n   - Don\'t forget to speak to Apururu in Windurst Woods at (H-9) to learn Trust: Ajido-Marujido.\n   - Also if you\'ve obtained the trust permits (the Red and Blue) from the other 2 nations you can acquire Trion and Volker as trusts now by visiting their respective starting NPC\'s.',
        notes = nil,
    },
    ['The Sixth Ministry'] = {
        id = 18,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Waters',
        start_pos = 'G-8',
        description = 'At the request of the Optistery,\nyou are to find former minister\nKaraha-Baruha\'s laboratory in\nToraimarai Canal, and delve deeper\ninto the mystery of the Book of\nthe Gods.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'Saintly Invitation'},
        next = {'Awakening of the Gods'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Talk to Tosuka-Porika in the Optistery eastern building in Windurst Waters HP #1 (G-8) for a cutscene and to receive the [Key Item] Optistery ring.\n2. Head to Toraimarai Canal (G-8) Map 2 and defeat the 4 Hinge Oils in the room.\n   - Quickest way to get there is to enter through the Windurst Walls (I-3) Priming Gate using the [Key Item] Rhinostery certificate, take a right at the bottom of the stairs, get into the water and keep turning left until you reach some stairs, which you should go up. From here, head south → east → north to reach the Slimes in (G-8).\n   - Alternatively if you have the Home Point #1 of Toraimarai Canal, go south from it entering a big room, continue towards your left to exit the room and begin walking through the canals. On Map 1 of the canals stay on the above path and walk towards point B. Once you reach point B on the above section keep going north on the only path and go down in the water section of the canals, go back to B and cross into Map 2, take a first right and go south, at the first stairs go up to the raised path and go towards (G-8) where you will find the oozes and door.\n3. After defeating the 4 Slimes, head northeast to the stairs at (H-8) and examine the Marble Door at the top.\n   - All four Hinge Oils must be defeated before you can enter The Animastery. Hinge Oils will repop after 16 minutes.\n4. Examine the Tome of Magic lying on the ground to begin a cutscene.\n   - This is near the desk and a skull resting on a chair.\nReturn to Tosuka-Porika to complete the Mission. You will receive the [Key Item] Blank Book of the Gods.',
        notes = nil,
    },
    ['The Three Kingdoms'] = {
        id = 5,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Heavens Tower',
        start_pos = nil,
        description = 'Determine the state of affairs in San d\'Oria and Bastok, and render assistance on behalf of Heavens Tower. Inquire at our consulate in each country for more information. Traveling by ship from Mhaura to Selbina is recommended.',
        reward = 'Rank 3\n3,000 Gil\n[Key Item] Adventurer\'s Certificate',
        fame = nil,
        fame_level = nil,
        title = 'Dread Dragon Slayer or Dark Dragon Slayer, Warchief Wrecker, Certified Adventurer',
        repeatable = 'No',
        previous = {'A Testing Time'},
        next = {'To Each His Own Right'},
        requirements = nil,
        walkthrough = 'Trade three Crystals (3+ if you skipped the previous mission) to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. This Mission can be long if you do not have Home Points, and is broken down in to two legs. Whichever Nation you choose first determines how the next plays out. Option 2, the San d\'Oria path progression, is typically easier and faster.\n2. Speak with Kupipi in Heavens Tower. She is inside the Clerical Chamber. She will give you a [Key Item] Letter to the consuls.\n   - You may receive Cipher: Semih if you don\'t already have it and are participating in Trust.\n\nWindurst to Bastok:\n\n1. Speak to Patt-Pott in Bastok Metalworks HP#1. He is inside the Windurstian Consulate top floor (I-7).\n2. Speak to Pius in the President\'s Office Department of Industry (J-8).\n3. Speak to Grohm at (H-9) in the Craftsmen\'s Eatery. He will give you 3 Pickaxes. Consider buying more, as they can break.\n4. Make your way to Palborough Mines in North Gustaberg, at the very north of the zone. You will need to mine Mine Gravel from the Mythril Seams located throughout the zone. There is one on the first floor at (I-8), and one on the top floor at (I-9). Trade the Pickaxe to the Seam until you receive some Mine Gravel.\n   - You CAN purchase Mine Gravel from the Auction House. ( ➞ Others ➞ Misc. 1)\n   - If you care about the  ultimately used for the Omega Mount, set that objective before you do the next step - it requires 10 Mine Gravel turned into Mythril Sand.\n5. Once you receive the Mine Gravel, head to the second floor, and make your way to (I-7). Trade the gravel to the refiner and then pull the lever. Drop off the ledge to the level below and pull another lever. You will receive Mythril Sand.\n6. Trade the Mythril Sand to Patt-Pott. Talk to him once more. This is the end of the Bastok leg.\n\nBastok to San d\'Oria:\n\n7. Speak to Kasaroro in the Windurstian Consulate in Northern San d\'Oria (H-9).\n8. Speak to Halver in Chateau d\'Oraguille.\n   - You will receive Cipher: Halver if you don\'t already have it. If not received, it may be received later.\n9. Go to Horlais Peak and clear the BCNM "The Rank 2 Final Mission".\n   - If you are low level consider forming a party (and/or use Trusts) of level 25 or higher, but make sure everyone has gear for a level 25 fight. A BLM or RDM is ideal for this fight, as you\'ll want sleep.\n   - To get to Horlais Peak use the Homepoint to Yughott Grotto or make your way to Ghelsba Outpost from West Ronfaure, it is in the northwestern corner. Inside, follow the left wall until you zone in to Yughott Grotto. Follow it all the way to the end, around (K-5). You should exit to Fort Ghelsba.\n   - Outside, head straight and stick to the left wall. You should start going up hill. Follow it around. At the top, there will be a large hut to your right. Enter it and go to the back, there is a hidden entrance here. It returns to Yughott Grotto#4. Head for (J-6) to enter Horlais Peak.\n   - Prepare and enter. Buffs will wear on zone, so buff up inside. Make your way to the top to face off against two NMs, an  called Seeker and a  called Dread Dragon.\n   - Sleep the Dragon and then defeat the Seeker, who is weak. Attack the dragon and take it down. This fight is really easy with a full party.\n   - If you are low level it can easily be defeated with a MNK/WAR and WHM/BLM. Can be soloed by some jobs with a lot of meds, and duoed by almost any melee job with a WHM healer.\n10. Return to Kasaroro at Northern San d\'Oria after clearing the BCNM.\n11. Return to Kupipi in Heavens Tower to complete the Mission.\n\nWindurst to San d\'Oria:\n\n1. Make your way to San d\'Oria and visit the Windurstian Consulate in Northern San d\'Oria.\n2. Speak to Heruze-Moruze and then Kasaroro, both at (H-9).\n3. Head over to Chateau d\'Oraguille and speak to Halver.\n   - This NPC is involved in multiple different Quests and Missions, you may need to speak to him repeatedly until he sends you to Ghelsba Outpost.\n   - Ghelsba Outpost is located to the far northwestern corner of West Ronfaure.\n4. Inside, head for (H-7) and look for the NM Warchief Vatgit and defeat him (its only purpose is for this Mission, and is usually up and wandering around. If not, wait a short time, it doesn\'t take long).\n   - The Survival Guide to Fort Ghelsba will bring you close to the NM. Just zone back out to Ghelsba and across the bridge.\n5. Speak to Kasaroro again. You are now finished with the San d\'Oria half of this Mission.\n\nSan d\'Oria to Bastok:\n\n6. Make your way to Bastok. Enter the Metalworks from Bastok Markets. Make your way to the top and speak with Patt-Pott inside the Windurstian Consulate, around (I-7).\n7. Speak to Pius in the President\'s Office Department of Industry (J-8). He will send you to the Craftsmen\'s Eatery (H-9) to speak to Grohm.\n   - If you\'re low level, form a party (and/or use Trusts) of level 25 or higher, but make sure everyone has gear for a level 25 fight. A BLM or RDM is ideal for this fight, as you\'ll want sleep.\n8. Make your way to Palborough Mines, in the very far north of North Gustaberg.\n   - If you\'ve already been there, take Palborough Mines Home Point #1.\n9. Inside, make your way to (I-8) and head upstairs. Here, make your way to (H-10) and zone in to Waughroon Shrine.\n10. Prepare and enter. Buffs will wear on zone, so buff up inside. Make your way to the top to face off against two NMs, an  called Seeker and a  called Dark Dragon.\n   - This fight is trivial with trusts\n   - Sleep the Dragon and then defeat the Seeker, who is weak. Attack the dragon and take it down. This fight is really easy with a full party.\n   - It can easily be defeated with a MNK/WAR and WHM/BLM. Can be soloed by some jobs with a lot of meds, and duoed by almost any melee job with a WHM healer.\n11. Once cleared, return to Patt-Pott in Metalworks.\n12. Your journey is almost complete, head back to Heavens Tower in Windurst Walls and speak to Kupipi to complete the Mission and receive your rewards.',
        notes = nil,
    },
    ['The Three Kingdoms (Bastok)'] = {
        id = 9,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Waters',
        start_pos = nil,
        description = 'Determine the state of affairs in San d\'Oria and Bastok, and render assistance on behalf of Heavens Tower. Inquire at our consulate in each country for more information. Traveling by ship from Mhaura to Selbina is recommended.',
        reward = 'Rank 3\n3,000 Gil\n[Key Item] Adventurer\'s Certificate',
        fame = nil,
        fame_level = nil,
        title = 'Dread Dragon Slayer or Dark Dragon Slayer, Warchief Wrecker, Certified Adventurer',
        repeatable = 'No',
        previous = {'A Testing Time'},
        next = {'To Each His Own Right'},
        requirements = nil,
        walkthrough = 'Trade three Crystals (3+ if you skipped the previous mission) to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. This Mission can be long if you do not have Home Points, and is broken down in to two legs. Whichever Nation you choose first determines how the next plays out. Option 2, the San d\'Oria path progression, is typically easier and faster.\n2. Speak with Kupipi in Heavens Tower. She is inside the Clerical Chamber. She will give you a [Key Item] Letter to the consuls.\n   - You may receive Cipher: Semih if you don\'t already have it and are participating in Trust.\n\nWindurst to Bastok:\n\n1. Speak to Patt-Pott in Bastok Metalworks HP#1. He is inside the Windurstian Consulate top floor (I-7).\n2. Speak to Pius in the President\'s Office Department of Industry (J-8).\n3. Speak to Grohm at (H-9) in the Craftsmen\'s Eatery. He will give you 3 Pickaxes. Consider buying more, as they can break.\n4. Make your way to Palborough Mines in North Gustaberg, at the very north of the zone. You will need to mine Mine Gravel from the Mythril Seams located throughout the zone. There is one on the first floor at (I-8), and one on the top floor at (I-9). Trade the Pickaxe to the Seam until you receive some Mine Gravel.\n   - You CAN purchase Mine Gravel from the Auction House. ( ➞ Others ➞ Misc. 1)\n   - If you care about the  ultimately used for the Omega Mount, set that objective before you do the next step - it requires 10 Mine Gravel turned into Mythril Sand.\n5. Once you receive the Mine Gravel, head to the second floor, and make your way to (I-7). Trade the gravel to the refiner and then pull the lever. Drop off the ledge to the level below and pull another lever. You will receive Mythril Sand.\n6. Trade the Mythril Sand to Patt-Pott. Talk to him once more. This is the end of the Bastok leg.\n\nBastok to San d\'Oria:\n\n7. Speak to Kasaroro in the Windurstian Consulate in Northern San d\'Oria (H-9).\n8. Speak to Halver in Chateau d\'Oraguille.\n   - You will receive Cipher: Halver if you don\'t already have it. If not received, it may be received later.\n9. Go to Horlais Peak and clear the BCNM "The Rank 2 Final Mission".\n   - If you are low level consider forming a party (and/or use Trusts) of level 25 or higher, but make sure everyone has gear for a level 25 fight. A BLM or RDM is ideal for this fight, as you\'ll want sleep.\n   - To get to Horlais Peak use the Homepoint to Yughott Grotto or make your way to Ghelsba Outpost from West Ronfaure, it is in the northwestern corner. Inside, follow the left wall until you zone in to Yughott Grotto. Follow it all the way to the end, around (K-5). You should exit to Fort Ghelsba.\n   - Outside, head straight and stick to the left wall. You should start going up hill. Follow it around. At the top, there will be a large hut to your right. Enter it and go to the back, there is a hidden entrance here. It returns to Yughott Grotto#4. Head for (J-6) to enter Horlais Peak.\n   - Prepare and enter. Buffs will wear on zone, so buff up inside. Make your way to the top to face off against two NMs, an  called Seeker and a  called Dread Dragon.\n   - Sleep the Dragon and then defeat the Seeker, who is weak. Attack the dragon and take it down. This fight is really easy with a full party.\n   - If you are low level it can easily be defeated with a MNK/WAR and WHM/BLM. Can be soloed by some jobs with a lot of meds, and duoed by almost any melee job with a WHM healer.\n10. Return to Kasaroro at Northern San d\'Oria after clearing the BCNM.\n11. Return to Kupipi in Heavens Tower to complete the Mission.\n\nWindurst to San d\'Oria:\n\n1. Make your way to San d\'Oria and visit the Windurstian Consulate in Northern San d\'Oria.\n2. Speak to Heruze-Moruze and then Kasaroro, both at (H-9).\n3. Head over to Chateau d\'Oraguille and speak to Halver.\n   - This NPC is involved in multiple different Quests and Missions, you may need to speak to him repeatedly until he sends you to Ghelsba Outpost.\n   - Ghelsba Outpost is located to the far northwestern corner of West Ronfaure.\n4. Inside, head for (H-7) and look for the NM Warchief Vatgit and defeat him (its only purpose is for this Mission, and is usually up and wandering around. If not, wait a short time, it doesn\'t take long).\n   - The Survival Guide to Fort Ghelsba will bring you close to the NM. Just zone back out to Ghelsba and across the bridge.\n5. Speak to Kasaroro again. You are now finished with the San d\'Oria half of this Mission.\n\nSan d\'Oria to Bastok:\n\n6. Make your way to Bastok. Enter the Metalworks from Bastok Markets. Make your way to the top and speak with Patt-Pott inside the Windurstian Consulate, around (I-7).\n7. Speak to Pius in the President\'s Office Department of Industry (J-8). He will send you to the Craftsmen\'s Eatery (H-9) to speak to Grohm.\n   - If you\'re low level, form a party (and/or use Trusts) of level 25 or higher, but make sure everyone has gear for a level 25 fight. A BLM or RDM is ideal for this fight, as you\'ll want sleep.\n8. Make your way to Palborough Mines, in the very far north of North Gustaberg.\n   - If you\'ve already been there, take Palborough Mines Home Point #1.\n9. Inside, make your way to (I-8) and head upstairs. Here, make your way to (H-10) and zone in to Waughroon Shrine.\n10. Prepare and enter. Buffs will wear on zone, so buff up inside. Make your way to the top to face off against two NMs, an  called Seeker and a  called Dark Dragon.\n   - This fight is trivial with trusts\n   - Sleep the Dragon and then defeat the Seeker, who is weak. Attack the dragon and take it down. This fight is really easy with a full party.\n   - It can easily be defeated with a MNK/WAR and WHM/BLM. Can be soloed by some jobs with a lot of meds, and duoed by almost any melee job with a WHM healer.\n11. Once cleared, return to Patt-Pott in Metalworks.\n12. Your journey is almost complete, head back to Heavens Tower in Windurst Walls and speak to Kupipi to complete the Mission and receive your rewards.',
        notes = nil,
    },
    ['The Three Kingdoms (San d\'Oria)'] = {
        id = 8,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Heavens Tower',
        start_pos = nil,
        description = 'Determine the state of affairs in San d\'Oria and Bastok, and render assistance on behalf of Heavens Tower. Inquire at our consulate in each country for more information. Traveling by ship from Mhaura to Selbina is recommended.',
        reward = 'Rank 3\n3,000 Gil\n[Key Item] Adventurer\'s Certificate',
        fame = nil,
        fame_level = nil,
        title = 'Dread Dragon Slayer or Dark Dragon Slayer, Warchief Wrecker, Certified Adventurer',
        repeatable = 'No',
        previous = {'A Testing Time'},
        next = {'To Each His Own Right'},
        requirements = nil,
        walkthrough = 'Trade three Crystals (3+ if you skipped the previous mission) to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. This Mission can be long if you do not have Home Points, and is broken down in to two legs. Whichever Nation you choose first determines how the next plays out. Option 2, the San d\'Oria path progression, is typically easier and faster.\n2. Speak with Kupipi in Heavens Tower. She is inside the Clerical Chamber. She will give you a [Key Item] Letter to the consuls.\n   - You may receive Cipher: Semih if you don\'t already have it and are participating in Trust.\n\nWindurst to Bastok:\n\n1. Speak to Patt-Pott in Bastok Metalworks HP#1. He is inside the Windurstian Consulate top floor (I-7).\n2. Speak to Pius in the President\'s Office Department of Industry (J-8).\n3. Speak to Grohm at (H-9) in the Craftsmen\'s Eatery. He will give you 3 Pickaxes. Consider buying more, as they can break.\n4. Make your way to Palborough Mines in North Gustaberg, at the very north of the zone. You will need to mine Mine Gravel from the Mythril Seams located throughout the zone. There is one on the first floor at (I-8), and one on the top floor at (I-9). Trade the Pickaxe to the Seam until you receive some Mine Gravel.\n   - You CAN purchase Mine Gravel from the Auction House. ( ➞ Others ➞ Misc. 1)\n   - If you care about the  ultimately used for the Omega Mount, set that objective before you do the next step - it requires 10 Mine Gravel turned into Mythril Sand.\n5. Once you receive the Mine Gravel, head to the second floor, and make your way to (I-7). Trade the gravel to the refiner and then pull the lever. Drop off the ledge to the level below and pull another lever. You will receive Mythril Sand.\n6. Trade the Mythril Sand to Patt-Pott. Talk to him once more. This is the end of the Bastok leg.\n\nBastok to San d\'Oria:\n\n7. Speak to Kasaroro in the Windurstian Consulate in Northern San d\'Oria (H-9).\n8. Speak to Halver in Chateau d\'Oraguille.\n   - You will receive Cipher: Halver if you don\'t already have it. If not received, it may be received later.\n9. Go to Horlais Peak and clear the BCNM "The Rank 2 Final Mission".\n   - If you are low level consider forming a party (and/or use Trusts) of level 25 or higher, but make sure everyone has gear for a level 25 fight. A BLM or RDM is ideal for this fight, as you\'ll want sleep.\n   - To get to Horlais Peak use the Homepoint to Yughott Grotto or make your way to Ghelsba Outpost from West Ronfaure, it is in the northwestern corner. Inside, follow the left wall until you zone in to Yughott Grotto. Follow it all the way to the end, around (K-5). You should exit to Fort Ghelsba.\n   - Outside, head straight and stick to the left wall. You should start going up hill. Follow it around. At the top, there will be a large hut to your right. Enter it and go to the back, there is a hidden entrance here. It returns to Yughott Grotto#4. Head for (J-6) to enter Horlais Peak.\n   - Prepare and enter. Buffs will wear on zone, so buff up inside. Make your way to the top to face off against two NMs, an  called Seeker and a  called Dread Dragon.\n   - Sleep the Dragon and then defeat the Seeker, who is weak. Attack the dragon and take it down. This fight is really easy with a full party.\n   - If you are low level it can easily be defeated with a MNK/WAR and WHM/BLM. Can be soloed by some jobs with a lot of meds, and duoed by almost any melee job with a WHM healer.\n10. Return to Kasaroro at Northern San d\'Oria after clearing the BCNM.\n11. Return to Kupipi in Heavens Tower to complete the Mission.\n\nWindurst to San d\'Oria:\n\n1. Make your way to San d\'Oria and visit the Windurstian Consulate in Northern San d\'Oria.\n2. Speak to Heruze-Moruze and then Kasaroro, both at (H-9).\n3. Head over to Chateau d\'Oraguille and speak to Halver.\n   - This NPC is involved in multiple different Quests and Missions, you may need to speak to him repeatedly until he sends you to Ghelsba Outpost.\n   - Ghelsba Outpost is located to the far northwestern corner of West Ronfaure.\n4. Inside, head for (H-7) and look for the NM Warchief Vatgit and defeat him (its only purpose is for this Mission, and is usually up and wandering around. If not, wait a short time, it doesn\'t take long).\n   - The Survival Guide to Fort Ghelsba will bring you close to the NM. Just zone back out to Ghelsba and across the bridge.\n5. Speak to Kasaroro again. You are now finished with the San d\'Oria half of this Mission.\n\nSan d\'Oria to Bastok:\n\n6. Make your way to Bastok. Enter the Metalworks from Bastok Markets. Make your way to the top and speak with Patt-Pott inside the Windurstian Consulate, around (I-7).\n7. Speak to Pius in the President\'s Office Department of Industry (J-8). He will send you to the Craftsmen\'s Eatery (H-9) to speak to Grohm.\n   - If you\'re low level, form a party (and/or use Trusts) of level 25 or higher, but make sure everyone has gear for a level 25 fight. A BLM or RDM is ideal for this fight, as you\'ll want sleep.\n8. Make your way to Palborough Mines, in the very far north of North Gustaberg.\n   - If you\'ve already been there, take Palborough Mines Home Point #1.\n9. Inside, make your way to (I-8) and head upstairs. Here, make your way to (H-10) and zone in to Waughroon Shrine.\n10. Prepare and enter. Buffs will wear on zone, so buff up inside. Make your way to the top to face off against two NMs, an  called Seeker and a  called Dark Dragon.\n   - This fight is trivial with trusts\n   - Sleep the Dragon and then defeat the Seeker, who is weak. Attack the dragon and take it down. This fight is really easy with a full party.\n   - It can easily be defeated with a MNK/WAR and WHM/BLM. Can be soloed by some jobs with a lot of meds, and duoed by almost any melee job with a WHM healer.\n11. Once cleared, return to Patt-Pott in Metalworks.\n12. Your journey is almost complete, head back to Heavens Tower in Windurst Walls and speak to Kupipi to complete the Mission and receive your rewards.',
        notes = nil,
    },
    ['To Each His Own Right'] = {
        id = 10,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Heavens Tower',
        start_pos = nil,
        description = 'On the command of Semih Lafihna, captain of the Sibyl Guards, you are requested to track down the Minister of the Orastery, Ajido-Marujido, and discover his true intentions. Inquire at the Orastery if you lose track of him.',
        reward = 'Rank Points\n[Key Item] Starway Stairway bauble',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'The Three Kingdoms'},
        next = {'Written in the Stars'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals (1+) to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Speak to Kupipi in Heavens Tower who will give you the [Key Item] Starway Stairway bauble.\n   - You will be granted access to the upper portion of Heavens Tower. Check the door on the left to go up.\n2. Speak to Rhy Epocan at the top of the Tower for a cutscene.\n   - Use the blue teleporter at the top of the tower to return to the main floor.\n3. Speak to Hakkuru-Rinkuru at the Orastery in Port Windurst (E-7) for hints on Ajido-Marujido\'s whereabouts.\n   - Home Point #1 is closest to Hakkuru-Rinkuru.\n4. Go to Castle Oztroja and fall down the trap door ((I-8) first Map) for a cutscene.\n   - Enter and go to (I-8). There will be two switches (not torches) and a fairly obvious floor panel. One switch will open the door, one will open the floor. Stand in between the two switches and check one. If it opens the door, check the other. They randomly switch, so it will never be the same, day by day.\n   - The person doing the Mission must be the one to pull the lever. Multiple people doing this mission will need to stand back until the trap door closes then individually pull the lever.\n   - In the same room you drop into there is a Blank Target, which is for the Onion Rings quest. You can collect [Key Item] Old ring without having the Quest flagged.\n5. Return to Rhy Epocan to complete the Mission.',
        notes = nil,
    },
    ['Vain'] = {
        id = 20,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Windurst Waters',
        start_pos = 'G-8',
        description = 'At the request of the Aurastery,\nyou are to discover the\nwhereabouts of their former\nminister who fled from his duties\nseveral years ago.',
        reward = 'Rank Points',
        fame = nil,
        fame_level = nil,
        title = 'Fugitive Minister Bounty Hunter',
        repeatable = 'No',
        previous = {'Awakening of the Gods'},
        next = {'The Jester Who\'d Be King'},
        requirements = nil,
        walkthrough = 'Trade enough Crystals to the Conquest NPC to raise your Rank bar and unlock the Mission, then accept it from the Gate Guard.\n1. Talk to Moreno-Toeno in Windurst Waters (L-6) at the Aurastery (northern section, eastern building, HP#2 is closest) for a cutscene and to obtain the [Key Item] "Star Seeker".\n2. Click the Qu\'Hau Spring in Ro\'Maeve (H-6) for a cutscene.\n   - Quick travel options: the Survival Guide to Ro\'Maeve is the fastest way. The Voidwatch warp to Hall of the Gods or Ro\'Maeve are the next best options, respectively.\n3. Go to Davoi and kill Dirtyhanded Gochakzuk NM to obtain a Curse Wand  (). The NM will drop 2 wands per kill, and respawns every 5 minutes.\n   - If you\'re in a party, each player will require one.\n   - The wand won\'t drop if you already have one. Check your storage.\n   - The NM is located on the center island (H-8), so you have to go though Monastic Cavern: Enter Monastic Cavern from entrance 2 at (H-11) in Davoi → Once inside, keep going and take the exit 4 at (I-8) → From here follow the road west around the hill to a wooden elevator, pull the lever to get to the monastery building → Inside, after 2 Oak Doors, the NM will be sitting on a big "throne".\n   - Quick travel options: the Proto-Waypoint to Davoi is the fastest way. Drop into the water, follow the water south-east to (J-10) to get back on land, then hug left until you reach entrance 2. The Survival Guide to Davoi is almost as fast.\n4. Take the elevator back down and walk to the bridge off the center island. Do not drop down in the river or you\'ll have to do the walk of shame back through the cave!\n5. Keep going until you reach Sedal-Godjal at (J-8). Speak to him for a cutscene. He will turn your [Key Item] "Star Seeker" into the [Key Item] Magic-drained "Star Seeker".\n   - You may need to talk multiple times. This can be done before or after obtaining the Curse Wand.\n6. Trade the Curse Wand to Sedal-Godjal for a cutscene.\n   - Optional: Talk to Sedal-Godjal again.\n     - When the refinrocements arrive from San d\'Oria, I\'ll return to Windurst. The professor mustaru have forgotten about Mojiji by now. Huh? He\'s still getting letters. But, I\'m not writing them anymore!\n7. Return to Moreno-Toeno for a cutscene that completes the Mission.\n   - Optional: Talk to Moreno-Toeno again.\n     - In closing, there is the case of Mojiji... With the sudden cessation of Mojiji\'s correspondence, Professor Koru-Moru slid into an unsettling slump. Let me just say that some of us struck on the same solution as sly old Sedal-Godjal...',
        notes = nil,
    },
    ['Written in the Stars'] = {
        id = 11,
        start_npc = 'Any Windurst Gate Guard',
        start_zone = 'Heavens Tower',
        start_pos = nil,
        description = 'On the command of Zubaba, the head lady-in-waiting, you are to journey beneath the central magic tower of the Horutoto Ruins. There, you are to report to the facility managed by Heavens Tower, which protects the talisman that seals Castle Zvahl. Render whatever assistance is necessary.',
        reward = 'Rank Points\n[Key Item] Portal charm',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'Yes',
        previous = {'To Each His Own Right'},
        next = {'A New Journey'},
        requirements = nil,
        walkthrough = 'This Mission is skippable. Should you skip it and obtain a higher rank, completing this mission will be different. See the notes at the end of the page.\nIf you choose not to skip this mission, check the Three Mage Gate page for details on your options.\n1. Accept the mission and make your way to Heavens Tower.\n2. Pass by Kupipi and on to the second floor. Speak to Zubaba who will give you the [Key Item] Charm of light.\n3. Next, you will need to get past the Three Mage Gate in ruins tower at (J-7) in East Sarutabaruta (this is the same tower as the Survival Guide Inner Horutoto Ruins warp).\n4. Pass the Three Mage Gate and continue on to the small room at (G-7).\n5. Check the Gate of Light for a cutscene.\n6. Return to Heavens Tower and speak to Zubaba to finish the mission.\n\nRepeating or Skipping the Mission:\n\nThis Mission will work differently if: you have skipped this Mission and obtained a higher Home Nation Rank after completing The Final Seal, or are simply repeating it.\n7. Accept the mission and speak to Zubaba. She will ask for you to bring her 3 Rusty Daggers. These can be purchased on the Auction House (but may be rare), or obtained from the Wendigos past the Three Mage Gate (the same skeletons that drop Test Answers.)\n8. Trade Zubaba the daggers to complete the mission. Obtaining the [Key Item] Portal charm is done the same way as completing the mission regularly.',
        notes = nil,
    },
}
