-- Mission data for zilart — extracted from BG Wiki (https://www.bg-wiki.com)
-- Generated: 2026-03-30
-- Total missions: 18
--
-- Fields: start_npc, start_zone, start_pos, description, reward, fame,
--         fame_level, title, repeatable, previous, next, requirements,
--         walkthrough, notes
-- Auto-generated from BG Wiki data.
-- Do not edit manually.

return {
    ['Ark Angels'] = {
        id = 26,
        start_npc = nil,
        start_zone = 'Ru\'Aun Gardens',
        start_pos = nil,
        description = 'Apathy, arrogance, cowardice, envy, rage--the darkness that lurks within us all...',
        reward = '[Key Item]Shard of Apathy\n[Key Item]Shard of Arrogance\n[Key Item]Shard of Cowardice\n[Key Item]Shard of Envy\n[Key Item]Shard of Rage',
        fame = nil,
        fame_level = nil,
        title = 'Pentacide Perpetrator (Divine Might only)',
        repeatable = 'Yes',
        previous = {'The Gate of the Gods'},
        next = {'The Sealed Shrine'},
        requirements = nil,
        walkthrough = '1. Zone into Ru\'Aun Gardens for a brief cutscene with Zeid and Aldo.\n   - If you have the quest for Prishe\'s Boots +1 active, a different cutscene will play the first time you enter the zone. Zone out and back in to trigger the proper cutscene.\n2. Proceed straight forward into the teleporter and enter The Shrine of Ru\'Avitau from the (H-8) entrance in Ru\'Aun Gardens.\n   - Survival Guide puts you close if you have it.\n3. Head north a short distance and examine the blank target at (G/H-11) for a cutscene.\n4. After the cutscene, return to Ru\'Aun Gardens.\n5. There are 5 BC fights to complete this mission, each spread out across the entire zone. Take the red portals to get to the appropriate towers that you see around the outside edge of the zone.\n   - Ru\'Aun Gardens is mostly safe from all aggro, except for the dolls which stand on blue pads, set in walls. Stay on the other side of the path from these and you\'ll be entirely safe. Everything detects magic except for birds.\n   - To give a brief description of how the portals work:\n     - The red portals lead to the islands in which you can access the La\'Loff Amphitheater which leads to each of the fights (where the Home Points are set when you view the map).\n     - The red portals are already activated by default.\n     - After each fight you will warp back to the island you were originally on by taking a red portal from the Home Point island. What you have to do to get to the next fight is find the pincerstone (it looks like a pincer pointing to the sky with a blue stone between) on the side of the island in the direction you want to travel (Which will be counter-clockwise in this case, i.e. starting from West to East)\n     - These are marked by blue stars on the map for Ru\'Aun Gardens on this page >>.\n     - On the first island the pincerstone is closer to the centre, but on subsequent islands it will be a small walk to your right once you warp back from the Home Point island.\n     - Activating the pincerstone will turn on the blue warp point which is located on the same side as the red portal but just to the left of it. (Imagine north is always pointing outside the circle, the blue warp point is south of the red one on the lower level).\n     - This will transport you to the next larger island and you can then take the red portal (Which is located on the other side to where you arrived) to the next Home Point island.\n     - Rinse and repeat all the way around.\n     - Basically all the larger and smaller islands are the same (with some minor differences but all points of interest are placed the same) except for the starting island in the south of the map.\n     - Note: there are two of each portal circle (blue and red) on either side of each island. The smaller circle is the warp point, and the larger one is where you land. The warp point has pincers around it.\n6. Visit each of the towers and zone inside, the BC area is called La\'Loff Amphitheater.\n   - You will be facing 5 Ark Angels, who you first saw in the Throne Room, as each of the 5 races wearing black armor and have very pale, ghostly faces. Divine Might combines all 5 Ark Angels in a single fight, fought as an alliance. The mission itself, however, is individual fights, in 6 person BCs.\n   - At each tower, you\'ll have some time to prepare, and then enter to face off against the Ark Angel. Each tower is specific, so you\'ll need to visit them all. Each Ark Angel has 2 jobs, and can use the full abilities of each, as well as their respective weapons weaponskills.',
        notes = nil,
    },
    ['Awakening'] = {
        id = 30,
        start_npc = 'Gilgamesh',
        start_zone = 'Norg',
        start_pos = nil,
        description = 'And so ends another chapter in the neverending tale of Vana\'diel. However, as long as there are those who are lured by the thoughts of Paradise, the wheels of destiny will continue to turn.',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'The Celestial Nexus'},
        next = {'The Last Verse'},
        requirements = nil,
        walkthrough = '1. Enter Norg for a cutscene with Gilgamesh. If you do not get a cutscene, proceed to the Captain\'s Chamber and speak to Gilgamesh there.\n2. Click on the Neptune\'s Spire Inn door in Lower Jeuno for another cutscene with Aldo.\n   - These can be done in any order, but both must be completed before zoning to Ru\'Lude Gardens to trigger Shadows of the Departed.\n     - The Quest will not trigger unless sufficient progress has been made in other questlines, visit the page Shadows of the Departed for more details.',
        notes = nil,
    },
    ['Headstone Pilgrimage'] = {
        id = 10,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'Somewhere on the island of Zepwell lie the remains of an ancient temple.',
        reward = '[Key Item]Earth fragment\n[Key Item]Fire fragment\n[Key Item]Ice fragment\n[Key Item]Light fragment\n[Key Item]Lightning fragment\n[Key Item]Water fragment\n[Key Item]Wind fragment\n[Key Item]Dark fragment',
        fame = nil,
        fame_level = nil,
        title = 'Bearer of the Eight Prayers',
        repeatable = 'No',
        previous = {'The Temple of Uggalepih'},
        next = {'Through the Quicksand Caves'},
        requirements = nil,
        walkthrough = '1. Due to the long nature of this mission, it is recommended that you take precautions to ensure that you have received the key items. This mission can take a while, as it requires travel to a lot of different places, some in the far corners of large and dangerous zones. Always ensure that when checking a headstone you receive the message that you obtained the key item.\n2. If you are too far away the game can give you the message, "You need to move closer to key item" and at a quick glance this can appear the same as you acquiring it. Be sure to double check.\n3. There are two types of headstones, one type only gives the key item, others spawn NMs that you must defeat before you may receive the key item.\n4. Several headstones are close to Cloister home points, it\'s recommended to grab those on the way if you haven\'t unlocked them yet.\n\nNon-fights:\n\n----\nDark Fragment:\n5. Obtained upon completion of The Temple of Uggalepih from Grav\'iton.\n----\n6. Proceed to (J-9) in Western Altepa Desert, and enter the Quicksand Caves (Map 3).\n7. Head to (K-6) and fall down the sandpit.\n8. Follow the pathway until you exit back out to Western Altepa Desert.\n   - Unity warp 125 Western Altepa Desert will land you within this area cutting out the need to go through Quicksand Caves.\n   - From the Unity Warp:\n     - Turn around and walk into the crevasse (this cannot be accessed from the outside but the Unity Warp puts you on top of the stone that you cannot normally walk onto.)\n     - Follow the path, turning right at the fork until you come to a plunger-looking statue (Ruby Column). Press it down if it is up to continue.\n     - Go through the open door near the end of this path and follow it until you exit out at the square shaped crevasse.\n     - Turn left and enter the first open door. When you exit again the headstone is located in this section.\n9. Move in a southwesterly direction towards (H-8)/(H-9) to locate the Cermet Headstone. Examine it to receive the [Key Item]Earth fragment.\n----\n      - Note: the Geomagnetic Fount for La Theine Plateau will let out in the same chasm as the Cermet Headstone.\n10. Proceed to La Theine Plateau and enter Ordelle\'s Caves around (F-7), alternatively you can use Survival Guide to get here. This places you on Map 2.\n   - Follow the path east to (I-6)(exit B) and you\'ll switch to Map 1. (East according to map, so left from where you enter.)\n   - Continue down the tunnel to (G-8).\n   - From there, go east and enter the south tunnel (exit D) around (H-9).\n   - Head up the stairs and south until you reach the hole that is at the southside of (H-11), at the transition between (H-11) and (H-12).\n   - Go east to another tunnel (E, Map 3), taking special care not to fall off the cliffs, and head up.\n   - Once you get to about (I-6), go south.\n   - Continue on until (H-9) and you\'ll see a tunnel going west, the zone is not far ahead, bringing you back out to La Theine Plateau.\n     - If you don\'t have the Geomagnetic-Fount, it will be on the right on a ledge after zoning to the Plateau. Get close to it and interact with it from below to register it.\n   - The Cermet Headstone is at the end of the valley at G-11. Examine it to receive the [Key Item]Water fragment.\n----\n11. Make your way to the Cloister of Frost in the basement of Fei\'Yin. The Cermet Headstone is in the back of the room. Examine it to receive the [Key Item]Ice fragment.\n   - Fei\'Yin Homepoint #2 is right outside the Cloister, if you already have it.\n   - A level 20+ Summoner can start Trial-Size Trial by Ice to be teleported to the Cloister. Don\'t forget to step outside and grab Fei\'Yin Homepoint #2 for later use, especially if you are completing the Trial-Sized quest.\n\nFights:\n\n----\n12. Fire Fragment:\n13. Note: The one way drops make starting from the Cloister of Flames or the Ifrit\'s Cauldron Homepoint (i.e. via Mini Fork of Fire) a longer trip that ends up passing the entrance from Yhoator Jungle / Survival Guide on Map 4 anyway.\n   - All three travel options (Teleport-Yhoat, the Yhoator Jungle Survival Guide, or the Level 122 Unity Warp) place you around the same area and will allow you to enter Ifrit\'s Cauldron as instructed below.\n     - Bring a total of three Ice Clusters to speed up the flame spouts along the way, if you don\'t, you\'ll have to wait up to 3 game hours (around 7 Earth minutes) for them to disappear.\n     - Bring Silent Oil Silent Oils and Prism Powder Prism Powders as bombs will aggro spell casting after removing invisible to trade a cluster.\n14. Consider taking a Garnet with you on this leg of the mission, as you can trade it to the headstone to receive the Opo-opo Necklace .\n   - You need to take the Fire Fragment before doing this.\n----\n15. Enter Ifrit\'s Cauldron from (G-6) in Yhoator Jungle.\n   - Alternatively take the Survival Guide warp if you\'ve unlocked it to get to this entrance.\n   - When you enter, you\'ll be on Map 4. Head for (H-8) and through the middle exit, and you\'ll end up on Map 7.\n   - From Map 7, hug the left wall and head out the exit at (D-12) to continue to Map 5.\n   - On Map 5, head for (J-8), the only other exit, to get to Map 2. There is a style=italic|Flame Spout around (H-6)/(H-7). Either wait it out, or trade an Ice Cluster. Waiting it out is safer, but can take extra time.\n   - On Map 2, run to (E-7) while hugging the left wall, and you\'ll be back on Map 7. Do not accidentally take the drop that is to the north of the tunnel at (G-8).\n   - On Map 7, hug the left wall on your way to (G-7) to enter Map 8. Do not accidentally take the drop slightly to the right.\n   - On Map 8, follow the tunnel to (C-7). This is the exit to Yuhtunga Jungle. There are two style=italic|Flame Spouts on the way.\n16. Near the exit to Yuhtunga Jungle, you may run across the Ash Dragon. Your party is likely not able to take it if you are level 75, so be careful.\n   - During daytime hours (06:00 to 18:00), it\'s only aggressive to sound. During night time, however, it is True Sound.\n     - Take care when passing it, as it will mostly likely spell a wipe for your party.\n17. Once outside, gather everyone up and head for the tunnel under the waterfall at (K-7). The headstone is located around (L-6)/(L-7). Check the Cermet Headstone to spawn two  NMs, Carthi and Tipha.\n   - They will both aggro through sneak and cannot be slept, but are susceptible to gravity and bind.\n   - Defeat both Opos and check the Cermet Headstone again to receive the [Key Item]Fire fragment.\n     - If you get a message saying "Don\'t you have something better to do right now?", keep checking the headstone until you get the KI.\n----\n18. Travel to Behemoth\'s Dominion (G-9).\n   - Unity Warp Level 135 will be the fastest way to get here.\n19. Clear the area of mobs and check the headstone to spawn two  NMs: Legendary Weapon (BLM/RDM) and Ancient Weapon (WAR).\n   - Defeat them both and check the Cermet Headstone again to receive the [Key Item]Lightning fragment.\n20. It is possible to fight only one of the NMs, by using the Sneak-pull method. Sneak one member, pull one of the NMs and wait for the other to de-pop. Defeat the original and proceed.\n   - Both are susceptible to Bind and Gravity, but not sleep or silence.\n   - Both will use their 1-hour abilities around 50%.\n     - Legendary Weapon will use Manafont and begin casting back-to-back.\n     - Casts Diaga 2, Paralyze, Silence, Slow, Gravity, Cure IV, Protect/Shell, etc.\n     - Either can be defeated solo at level 75 with DoT and occasional nukes while kiting it around the King Behemoth spawn area.\n     - Ancient Weapon is not aspirable, but the Legendary Weapon is.\n----\n21. Consider taking a Rain Lily with you on this part of the mission. Trading it to the headstone will earn you a Flagellant\'s Rope .\n   - You need to take the Wind Fragment before doing this.\n22. Start off for Cape Teriggan, both the Home Point and Unity Warp 128 let out close to the Cermet Headstone.\n23. Head for (F-7) and locate the unmarked hidden tunnel (it is in the same general area as the tunnel to get to the Cloister of Gales).\n   - Go north until you come out into another open area, taking another hidden tunnel at (G-5).\n     - Follow it until (H-5), where the headstone is located.\n24. Check the headstone to pop a  NM named Axesarion the Wanderer.\n   - Defeat it and check the Cermet Headstone again to receive the [Key Item]Wind fragment.\n----\n25. Proceed to The Sanctuary of Zi\'Tah. Your goal is to get to (J-9) first.\n   - The Survival Guide/Outpost warp will get you closest to (J-9).\n26. From (J-9), entrance is at the South Eastern (SE) corner of the box, hug left wall till you\'re near the North Eastern corner of (I-7).\n   - This is the same area where Keeper of Halidom can spawn.\n27. Check the headstone to spawn a  NM named Doomed Pilgrims.\n   - This NM hits fairly fast and hard, but should pose little trouble to a well balanced party of 65+.\n28. Defeat the NM and check the Cermet Headstone again to receive the [Key Item]Light fragment.\n29. Note: Come back to this headstone after completing ZM7: The Chamber of Oracles to receive a Bat Earring .\n----\n30. Upon obtaining the final fragment, you will receive the message, "You now have all 8 fragments of light!" and the mission will be complete.',
        notes = nil,
    },
    ['Kazham\'s Chieftainess'] = {
        id = 6,
        start_npc = 'Jakoh Wahcondalo',
        start_zone = 'Kazham',
        start_pos = 'J-9',
        description = 'Before you travel to the Temple of Uggalepih, you are to meet with the Kazham chieftainness, Jakoh Wahcondalo.',
        reward = '[Key Item] Sacrificial Chamber key',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'Welcome t\'Norg'},
        next = {'The Temple of Uggalepih'},
        requirements = nil,
        walkthrough = '1. Go to Kazham (J-9) and speak with Jakoh Wahcondalo. She will give you a [Key Item] Sacrificial Chamber key required to progress further in the Temple of Uggalepih.\n   - Using Elshimo Low > Kazham > Home Point #1 will bring you right next to the house of Jakoh Wahcondalo.',
        notes = nil,
    },
    ['Return to Delkfutt\'s Tower'] = {
        id = 16,
        start_npc = 'Aldo',
        start_zone = 'Lower Jeuno',
        start_pos = nil,
        description = 'Hurry to Delkfutt\'s Tower and stop the Zilartian princes from completing their plan to open the Gate of the Gods.',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'Destroyer of Antiquity',
        repeatable = 'No',
        previous = {'The Chamber of Oracles'},
        next = {'Ro\'Maeve'},
        requirements = nil,
        walkthrough = '1. (Optional) Aldo\'s Decision: At the Tenshodo HQ in Lower Jeuno, speak to Aldo for a cutscene.\n2. \'\' Zone into Lower Delkfutt\'s Tower from Qufim Island or via Survival Guide for a cutscene.\n3. Zone into Stellar Fulcrum for a cutscene.\n   - Home Point # 1 in Upper Delkfutt\'s Tower puts you right at this zone. You can then use the teleporter.\n4. Having a  Delkfutt Key or [Key Item] Delkfutt key will greatly speed this mission up.\n5. If you have a key, proceed to (E-8) on the first floor and go through the cermet door to the basement.\n   - Then proceed to (J-8) for another cermet door.\n   - In the middle of the spiral staircase at (H-8) click the ??? to be teleported to the 10th floor.\n6. If you do not have the key then you will have to climb the tower regularly.\n7. Once you reach Upper Delkfutt\'s Tower by any means, head for (F-8) on the first map and then through the door.\n   - This area is not shown on the map.\n8. Climb the stairs to the 11th floor. You\'ll need Sneak and Invisible to avoid aggro from Bats and Giants. There are also dolls and pots which aggro magic.\n9. Proceed to (J-6) and go to the 12th floor.\n10. Head for (F-10) and go through the teleporter to enter the Stellar Fulcrum.\n11. Walk forward and click the Qe\'lov Gate to enter the battlefield.\n\nBoss Fight:\n\n1. You will enter a BCNM fight against Kam\'lanaut. Buffs wear when entering the BC.\n   - Trusts can be used.\n2. Clearing this BC ends the mission.\n3. Great Wheel: AoE damage (~200) and Hate reset.\n4. Light Blade: Single target heavy damage (~700-1200).\n   - Has a charging time, and can be stunned.\n   - It has high range, and can be blinked by Utsusemi.\n5. Will cast Silencega, Dispelga and Slowga.\n6. Can use an Elemental Blade attack which gives him an en-spell of that element.\n   - It also causes him to be healed by magic of that same element.\n     - Major nukes can heal him for a lot of damage if the wrong spell is used, so be careful. It can be Dispelled.\n7. Immune to Sleep and Silence.\n8. Approximately 10,000 HP.',
        notes = nil,
    },
    ['Ro\'Maeve'] = {
        id = 18,
        start_npc = 'Aldo',
        start_zone = nil,
        start_pos = nil,
        description = 'The Gate of the Gods, Tu\'Lia, has been restored by Eald\'narche. What do his words "Ro\'Maeve" and "blessed by the light" mean? What is Lion\'s next move?',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'Return to Delkfutt\'s Tower'},
        next = {'The Temple of Desolation'},
        requirements = nil,
        walkthrough = '1. (Optional) Head to the Tenshodo and speak to Aldo.\n2. Go to Norg and speak with Gilgamesh, who speaks of ruins north of The Sanctuary of Zi\'Tah, and may be what Eald\'narche is talking about.\n   - Click on the "Oaken Door" at (K-8) in Norg for the option to "Open the door"; Accepting this option starts the cut-scene.\n3. You may be on other missions related to Chains of Promathia or Rhapsodies of Vanadiel.\n   - Make sure you choose to "Open the door" to progress this particular mission.\n4. After the Cut-scene with Lion and Gilgamesh you will be standing outside the Oaken Door again and the next mission will have started.',
        notes = nil,
    },
    ['The Celestial Nexus'] = {
        id = 28,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'The fate of Vana\'diel awaits you in the Celestial Nexus!',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'Burier of the Illusion',
        repeatable = 'No',
        previous = {'The Sealed Shrine'},
        next = {'Awakening'},
        requirements = nil,
        walkthrough = '*The The Shrine of Ru\'Avitau is full of magic aggro, so even mages should bring along Silent Oil and Prism Powder.\n   - Note that Ninjutsu and Spectral Jig are also options for applying Sneak (Status) and Invisible (Status) without potentially aggroing nearby enemies.\n1. You may need someone to operate the Yellow door. The closest Monolith to your location is around I/J-9/10.\n2. Go to (I-6) in Ru\'Aun Gardens and enter the Shrine. You\'ll be on Map 1. Sneak and head south. Go past (J-7) through the first yellow door. Go west from here, to the room with 2 Monoliths in (H-7). You\'ll need Invisible, then go south around the square hallway filled with Aura Statue to another room with 2 Dark Elementals around (H-10).\n3. Go north, down a flight of stairs to the Celestial Nexus at (H-9).\n4. Gather together and get ready for the last BC of the expansion. You\'ll be fighting Eald\'narche, who has two forms.',
        notes = nil,
    },
    ['The Chamber of Oracles'] = {
        id = 14,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'The Chamber of Oracles is said to be located in the deepest area of the Quicksand Caves.',
        reward = '[Key Item]Prismatic fragment',
        fame = nil,
        fame_level = nil,
        title = 'Lightweaver',
        repeatable = 'No',
        previous = {'Through the Quicksand Caves'},
        next = {'Return to Delkfutt\'s Tower'},
        requirements = nil,
        walkthrough = '1. You\'ll be in a room with a large device. Check each of the 8 parts of the device to insert the fragments obtained in a previous mission. You\'ll be given a cutscene, thus starting the next mission.',
        notes = nil,
    },
    ['The Gate of the Gods'] = {
        id = 24,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'The path to Tu\'Lia has opened!',
        reward = 'Access to Tu\'Lia',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'The Mithra and the Crystal'},
        next = {'Ark Angels'},
        requirements = nil,
        walkthrough = '1. After the last cutscene where you teleport up, you will be granted access to Tu\'Lia, otherwise known as "sky". You\'ll be able to use the shimmering circle you found downstairs to return anytime for future reference.\n2. Run forward to zone into Ru\'Aun Gardens and begin the next mission.\n   - Don\'t forget to grab the Survival Guide just up ahead after you zone into Ru\'Aun Gardens.\n   - If you have the quest for Prishe\'s Boots +1 active, a different cutscene will play the first time you enter the zone. Exit the zone and re-enter to receive the correct cutscene.',
        notes = nil,
    },
    ['The Hall of the Gods'] = {
        id = 22,
        start_npc = 'Gilgamesh',
        start_zone = 'Norg',
        start_pos = nil,
        description = 'A strange grate prohibits you from journeying deeper into the Hall of the Gods. The depression in the center may be the key to getting through. You should probably report this find to Gilgamesh.',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'The Temple of Desolation'},
        next = {'The Mithra and the Crystal'},
        requirements = nil,
        walkthrough = '1. Unable to progress any further, head back to Norg, open the door, and speak to Gilgamesh.\n   - He will speak of a Mithra who was once trying to sell a crystal.\n     - You will now be on the next mission.',
        notes = nil,
    },
    ['The Last Verse'] = {
        id = 31,
        start_npc = nil,
        start_zone = nil,
        start_pos = nil,
        description = 'N/A',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'Awakening'},
        next = nil,
        requirements = nil,
        walkthrough = 'This Mission has no description. It is considered the final Mission of both Rise of the Zilart (Zilart Mission 18) and Chains of Promathia (Promathia Mission 8-5). It only displays in your log upon completion of Apocalypse Nigh and simply signifies that you have finished the storylines.',
        notes = nil,
    },
    ['The Mithra and the Crystal'] = {
        id = 23,
        start_npc = 'Maryoh Comyujah',
        start_zone = 'Rabao',
        start_pos = 'G-7',
        description = 'According to Gilgamesh, a Mithra carrying a mysterious crystal she found in The Sanctuary of Zi\'Tah',
        reward = '[Key Item]Cerulean crystal',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'The Hall of the Gods'},
        next = {'The Gate of the Gods'},
        requirements = nil,
        walkthrough = '1. Go to Rabao Home Point #2 and speak to Maryoh Comyujah, who is in (G-7) in front of the windmill.\n   - Chose the top option \'Sounds fair\'. If you spam enter then you won\'t choose this.\n2. She will ask you to go to the Quicksand Caves (again..).\n3. Head for the secret entrance in Western Altepa Desert (C/D-11), (Same hidden zone as ZM6: Through the Quicksand Caves.)\n   - This Mission happens in a similar location in the caves, but on the opposite side of the area where you went before. Check the coordinates below to be sure.\n   - You can use the Proto-Waypoint in Rabao at (G-8) to get to Quicksand Caves and enter into the right map (but not the right hole, you still need to go to the other side of the map).\n4. Inside (on Map 5), go to (K-8) and through the pressure door, this will lead you to Map 6.\n   - On Map 6, head for (G-8) for another pressure door.\n5. Enter and fall down the hole. Near where you fall, there is a ???. Buff up and select "Yes" to dig and spawn a Pot NM Ancient Vessel. You may need to move very close to the ??? to get it to actually spawn.\n   - Once you kill the NM, check the ??? again. You will receive the [Key Item]Scrap of papyrus.\n6. Return to Rabao and speak to Maryoh Comyujah again. She will give you the [Key Item]Cerulean crystal.\n7. Head back to the Hall of the Gods, touch the sealed gate, and watch the cutscene.\n8. Go down the hallway and examine the Shimmering Circle for the last cutscene.',
        notes = nil,
    },
    ['The New Frontier'] = {
        id = 0,
        start_npc = nil,
        start_zone = 'Norg',
        start_pos = nil,
        description = 'Vana\'diel is expanding day by day. What adventures await you in the Outlands?',
        reward = 'Map of Norg (If you do not already own it)',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = nil,
        next = {'Welcome t\'Norg'},
        requirements = nil,
        walkthrough = '1. Entering Norg will trigger a cutscene.\n   - If you previously chose to postpone the cut-scene, use Tales\' Beginning which is located near Home Point #1 in Norg to resume the story.\n\nTraveling to Norg:\n\n1. Norg is located on Elshimo Island, which can be reached one of the following ways:\n   - [Key Item] Kazham Airship Pass to travel from Port Jeuno to Kazham.\n   - If you are on or past Rhapsodies of Vanadiel Mission 1-5, Pacomart and Tonasav can transport you to Norg.\n2. Additional methods become available once either of the above two conditions are met:\n   - Waypoints in  after purchasing the [Key Item] Norg warp rune or [Key Item] Kazham warp rune.\n   - Unity Warp after completion of 10  objectives and joining a Unity.\n     - Sea Serpent Grotto in the CL 125 category is closest.\n3. NOTE:  You must be minimum rank 6 in your home nation in order to continue any further from here.',
        notes = nil,
    },
    ['The Sealed Shrine'] = {
        id = 27,
        start_npc = 'Gilgamesh',
        start_zone = 'Norg',
        start_pos = nil,
        description = 'The door deep within the Shrine of Ru\'Avitau is sealed with some form of supernatural power. Could this be the work of Eald\'narche?',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'Ark Angels'},
        next = {'The Celestial Nexus'},
        requirements = nil,
        walkthrough = '1. Head for Norg and speak to Gilgamesh.\n2. Head back to Ru\'Aun Gardens and go to any entrance to the Shrine of Ru\'Avitau. Enter for a cutscene. Teleporting to the home point will also trigger the cutscene.\n   - You may find entering the shrine from (I-6) (near Ru\'Aun Gardens Home Point #1) to save time approaching the next quest.',
        notes = nil,
    },
    ['The Temple of Desolation'] = {
        id = 20,
        start_npc = nil,
        start_zone = 'Ro\'Maeve',
        start_pos = nil,
        description = 'On the northernmost point of Mindartia and deep within the wilderness known as the The Sanctuary of Zi\'Tah',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'Sealer of the Portal of the Gods',
        repeatable = 'No',
        previous = {'Ro\'Maeve'},
        next = {'The Hall of the Gods'},
        requirements = nil,
        walkthrough = '1. Go to Ro\'Maeve. You will need Sneak and Invisible through this area, but everything in-zone detects magic, so use Silent Oils and Prism Powders or cast Sneak and Invisible at the zone.\n   - You can now also use a mount in this zone.\n2. If you have it, Survival Guide to Ro\'Maeve is the fastest way, it puts you right at the zone to Hall of the Gods.\n   - Unity Warp (125) will put you at the entrance of Ro\'Maeve.\n3. Head for (H-5) and zone in to Hall of the Gods.\n4. Run through the hallway and check the Cermet Grate two times. You will now be on the next mission.',
        notes = nil,
    },
    ['The Temple of Uggalepih'] = {
        id = 8,
        start_npc = nil,
        start_zone = 'Yhoator Jungle',
        start_pos = 'J-11/12',
        description = 'The Temple of Uggalepih is an ancient place where it is said that evil deities were once worshipped. Gilgamesh has ordered you to travel there and search out a strange, old hermit.',
        reward = '[Key Item]Dark fragment',
        fame = nil,
        fame_level = nil,
        title = 'Bearer of the Wisewoman\'s Hope',
        repeatable = 'No',
        previous = {'Kazham\'s Chieftainess'},
        next = {'Headstone Pilgrimage'},
        requirements = nil,
        walkthrough = 'The overall goal of this mission is to reach the Sacrificial Chamber BCNM zone. Before that, your goal is to reach the Den of Rancor.\nReaching the Den of Rancor\nMethod #1\nUse the Den of Rancor Home Point #1 warp.\n:If you have the Home Point already, you can simply warp there and zone into the Sacrificial Chamber area.\nMethod #2\nThe Unity warp to Den of Rancor (under content level 128) allows you to skip the Temple of Uggalepih step of Method #3 without the need for a [Key Item]Paintbrush of souls.\n:Note: You will still need an Unlit Lantern, unless somebody opens the Rancor door for you. Anyone with the Home Point warp can easily do this, saving you a lot of time.\nMethod #3\nThis is the old fashioned way, by obtaining the [Key Item]Paintbrush of souls.\n:See the Mini-Quest page for instructions on obtaining the item, then come back to this page and continue below:\nYou will also need one Unlit Lantern to access the Sacrificial Chamber area. Obtain one via the below methods, and continue on the Temple of Uggalepih steps.\n:Unlit Lanterns are dropped by Tonberry Jinxers in Yhoator Jungle, Tonberry Maledictors and Tonberry Pursuers in Temple of Uggalepih, and slightly higher level Tonberry Imprecators in Den of Rancor.\n::A good area to farm Maledictors would be the map with Sozu Rogberry\'s ??? and where Uggalepih Offering can be found.\nTemple of Uggalepih steps\n1. Enter the Temple from the main entrance in Yhoator Jungle (J-11/12).\n   - The Voidwatch warp brings you to this entrance.\n2. Make your way to the northwestern exit at (F-5). Pick up the Survival Guide on the way.\n   - You will zone out into Yhoator Jungle. Make a left after zoning.\n3. Enter the temple again from (H-11), and work your way down to the Temple Guardian at (I-10).\n   - Kill the guardian if he is up, otherwise the door will be open already.\n4. Go ahead to (I-7). The door is on the far side of the room. Whoever has the [Key Item]Paintbrush of souls needs to stand at the empty frame in the middle of the wall. Everyone else wait by the door.\n   - To use the Paintbrush, check the frame and confirm you wish to continue. You should get a message saying "a new painting begins to appear on the canvas". Wait 30 seconds without moving or entering any commands, and check it again. You should get another message about the Den of Rancor, and the door will open.\n   - The person who is checking the frame cannot be aggro\'d or acted on during these 30 seconds, otherwise you\'ll have to start over.\nDen of Rancor steps\n5. Enter the Den of Rancor. Everyone will need Sneak and Invisible (Status).\n6. Head to (E-5) on map 1. Once clear of the bomb mobs there, drop Invisible and trade your Unlit Lantern to the Altar of Rancor. You will receive a Rancor Flame item instead.\n7. Run to (F-7) and drop down the hole in the northeast corner to map 2. Make your way to (E-5) on this new map.\n8. To access the Sacrificial Chamber the four lanterns outside its gate need to be lit with Rancor Flame by trading the Unlit Lantern to an Altar of Rancor. While it can be done with one Unlit Lantern going back and forth from the Alter of Rancor and the lanterns, it would be suggested to farm multiple. 4 is ideal, but you can only hold one Lantern and one Flame at any time so that will require 4 players.\n   - Consider clearing the room, as it is hard to trade while being attacked.\nAfter arriving at the Home Point in Den of Rancor\n9. Be sure to obtain the Home Point, and then walk further to zone into the Sacrificial Chamber.\n10. Examine the door to progress to the boss fight, see below for details.\n   - The name of the fight is the same as the mission, "The Temple of Uggalepih"\n\nShortcut:\n\n1. If you already have the Den of Rancor Home Point unlocked, you can use it to warp directly to the Den of Rancor, step into the Sacrificial Chamber, and enter the Battlefield for the boss fight.\n2. A player who has already completed this mission can use the home point and open the door for you, allowing you to skip the puzzle entirely. Use the Unity Warp (level 128) to reach the door if you are using this method.\n\nBoss Fight:\n\n1. Inside, gather up and prepare. You will now enter an uncapped BCNM against 3 Tonberry NMs. Buff inside, as they\'ll wear upon entering the BC.\n2. Once you\'ve cleared the BC, you\'ll get a cutscene. Afterwards, you\'ll exit on the other side of the Sacrificial Chamber, that will lead you back out to the Temple.\n3. After winning the BCNM, you may now continue Rhapsodies of Vanadiel Mission 2-24 The Cursed Temple.\n4. Grav\'iton:\n   - Uses both Perfect Dodge and Everyone\'s Rancor.\n5. Molyb\'iton:\n   - Uses Manafont at some point.\n6. Tungs\'iton:\n   - Uses Astral Flow at some point, summoning an avatar to wreak havoc.\n7. Recommended to battle order of Grav\'iton THF → Molyb\'iton BLM → Tungs\'iton SMN\n8. Grav\'iton cannot be slept, and therefore should be defeated first. Silence and Sleep the other two.\n9. Grav\'iton can use Everyone\'s Rancor, which does 10 times the damage of Everyone\'s Grudge. A tank can very easily be KOed by this if they have significant rancor.\n10. The Summoner will have a pet, but that does not indicate what avatar it will use for Astral Flow. Defeat it quickly to try and avoid Astral Flow. It probably won\'t KO you if it does use it, but it will cause you some issues. Make sure everyone has full HP before attacking it.',
        notes = nil,
    },
    ['Through the Quicksand Caves'] = {
        id = 12,
        start_npc = nil,
        start_zone = 'Western Altepa Desert',
        start_pos = 'I-7',
        description = 'You must hurry to Zepwell\'s Island\'s ancient temple.',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'Headstone Pilgrimage'},
        next = {'The Chamber of Oracles'},
        requirements = nil,
        walkthrough = '1. Everything here is aggressive to  sound, so make sure everyone has Sneak.\n   - Using the Unity Warp 125 will locate you in Western Altepa Desert (I-7).\n2. Proceed to Western Altepa Desert and head for the tunnel at (C/D-11) south side.\n   - Following this tunnel will bring you to an unmarked area of the desert.\n3. Head down the ramp to (D-12) and enter Quicksand Caves.\n4. Go to (I-9) and step on the weight pad and go through the door.\n5. Go west to (H-7) and use another weight pad to pass through a door.\n6. In the next room, drop down the hole to a hidden area.\n7. Head to (D-4) to zone in to the Chamber of Oracles.',
        notes = nil,
    },
    ['Welcome t\'Norg'] = {
        id = 4,
        start_npc = nil,
        start_zone = 'Norg',
        start_pos = 'L-8',
        description = 'Lion has someone she wants you to meet. She will be waiting for you at the room at the end of the hallway on the second floor of Norg.',
        reward = 'None',
        fame = nil,
        fame_level = nil,
        title = 'None',
        repeatable = 'No',
        previous = {'The New Frontier'},
        next = {'Kazham\'s Chieftainess'},
        requirements = nil,
        walkthrough = '1. Head for (L-8) in Norg and enter the Oaken Door. You\'ll receive a cutscene with Gilgamesh.',
        notes = nil,
    },
}
