-- Mission names: bastok (extracted from DAT 0xD9A4)
return {
    [0] = 'The Zeruhn Report',
    [1] = 'A Geological Survey',
    [2] = 'Fetichism',
    [3] = 'The Crystal Line',
    [4] = 'Wading Beasts',
    [5] = 'The Emissary',
    [6] = 'The Emissary (San d\'Oria)',
    [7] = 'The Emissary (Windurst)',
    [8] = 'The Emissary (San d\'Oria)',
    [9] = 'The Emissary (Windurst)',
    [10] = 'The Four Musketeers',
    [11] = 'To the Forsaken Mines',
    [12] = 'Jeuno',
    [13] = 'Magicite',
    [14] = 'Darkness Rising',
    [15] = 'Xarcabard, Land of Truths',
    [16] = 'Return of the Talekeeper',
    [17] = 'The Pirates\' Cove',
    [18] = 'The Final Image',
    [19] = 'On My Way',
    [20] = 'The Chains That Bind Us',
    [21] = 'Enter the Talekeeper',
    [22] = 'The Salt of the Earth',
    [23] = 'Where Two Paths Converge',
}
