-- Mission names: windurst (extracted from DAT 0xD9A5)
return {
    [0] = 'The Horutoto Ruins Experiment',
    [1] = 'The Heart of the Matter',
    [2] = 'The Price of Peace',
    [3] = 'Lost for Words',
    [4] = 'A Testing Time',
    [5] = 'The Three Kingdoms',
    [6] = 'The Three Kingdoms (San d\'Oria)',
    [7] = 'The Three Kingdoms (Bastok)',
    [8] = 'The Three Kingdoms (San d\'Oria)',
    [9] = 'The Three Kingdoms (Bastok)',
    [10] = 'To Each His Own Right',
    [11] = 'Written in the Stars',
    [12] = 'A New Journey',
    [13] = 'Magicite',
    [14] = 'The Final Seal',
    [15] = 'The Shadow Awaits',
    [16] = 'Full Moon Fountain',
    [17] = 'Saintly Invitation',
    [18] = 'The Sixth Ministry',
    [19] = 'Awakening of the Gods',
    [20] = 'Vain',
    [21] = 'The Jester Who\'d Be King',
    [22] = 'Doll of the Dead',
    [23] = 'Moon Reading',
}
