-- Quest data for outlands — extracted from BG Wiki (https://www.bg-wiki.com)
-- Generated: 2026-03-29
-- Total quests: 57
--
-- Fields: start_npc, start_zone, start_pos, description, reward, fame,
--         fame_level, title, repeatable, previous, next, requirements,
--         walkthrough, notes
-- Auto-generated from BG Wiki data.

return {
    ['20 in Pirate Years'] = {
        id = 143,
        start_npc = 'Ryoma',
        start_zone = 'Norg',
        start_pos = 'H-8',
        description = 'Norg has begun investigating an ancient scroll that was rediscovered as of late. Speak with Tenshodo member Kagetora in Bastok for more details...',
        reward = 'Anju \nZushio',
        fame = 'Other',
        fame_level = '1',
        title = nil,
        repeatable = nil,
        previous = {'Ayame and Kaede'},
        next = {'I\'ll Take the Big Box'},
        requirements = nil,
        walkthrough = '1. Talk to Ryoma at (H-8) in Norg (Home Point #1) to begin the quest, then head to Port Bastok\n2. Speak to Kagetora inside Warehouse #2 at (F-6) (Port Bastok Home Point #3).\n3. Head to (I-5) in Port Bastok and speak with Ensetsu.\n4. After speaking with Ensetsu, make your way to (H-5)/(H-6) of Eastern Altepa Desert.\n   - At this point you can continue on any job.\n   - The shortest route to the ??? is to take the Survival Guide to Western Altepa Desert then zone to Eastern Altepa Desert\n5. Clear the area and examine the ??? once ready.\n6. Two non-sleepable Spider NMs called Tsuchigumo will spawn.\n7. Clicking the ??? again after defeating the Tsuchigumo will grant the [Key Item]Trick box.\n   - Both NM corpses must disappear before you can obtain the [Key Item]Trick box.\n8. Head back to Norg and speak with Ryoma to complete the quest and receive your reward.',
        notes = nil,
    },
    ['A Discerning Eye (Kazham)'] = {
        id = 14,
        start_npc = 'Swift',
        start_zone = 'Kazham',
        start_pos = 'H-7',
        description = 'You have been asked to return a dropped item to its rightful owner. The passenger should be on the next airship flight.',
        reward = '500 gil',
        fame = 'Kazham',
        fame_level = nil,
        title = '*Discerning Individual',
        repeatable = 'Yes',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Dropped item', count = 1},
        },
        walkthrough = '1. Speak to Swift and accept the quest.\n2. Swift will show you a picture of an NPC, you need to memorize.\n3. Board the next airship.\n4. Several NPCs will spawn on the ship that all look very similar to the one Swift showed you.\n5. Speaking to the NPCs will give you an option to return a Dropped item to them.\n6. You only have one chance to get it right.\n   - If you choose correctly, you are given 500 gil.\n   - If you choose incorrectly, you fail the quest.',
        notes = nil,
    },
    ['A Question of Taste'] = {
        id = 3,
        start_npc = 'Etteh Sulaej',
        start_zone = 'Kazham',
        start_pos = 'J-9',
        description = 'It all started with a letter sent to Kazham\'s chieftainness by the young Windurstian artist, Angelica. Now, no one can stop the budding painter.',
        reward = '3,000 Gil',
        fame = 'Kazham',
        fame_level = '6',
        title = nil,
        repeatable = 'Yes',
        previous = {'A Pose by Any Other Name'},
        next = {'Everyone\'s Grudging'},
        requirements = {
            {name = '[Key Item] Angelica\'s letter', count = 1},
            {name = '[Key Item] Letter to Angelica', count = 1},
            {name = '[Key Item] "Final Fantasy"', count = 1},
            {name = '[Key Item] Ripped "Final Fantasy" painting', count = 1},
        },
        walkthrough = '1. Talk to Etteh Sulaej J-9.  You will receive the [Key Item] Letter to Angelica.\n2. Take the letter to Windurst Waters, and talk to Angelica at the Rarab Tail Hostelry. Then you will receive [Key Item] Angelica\'s letter and a painting [Key Item] "Final Fantasy" that she wants you to hang in Temple of Uggalepih.\n3. Go back to Kazham, talk to Etteh Sulaej.\n4. Go to (G-8) on the first map for the Temple of Uggalepih, and hang the picture at Stone Picture Frame (it is on the south wall of the Paintbrush Room) to spawn the Golem NM, Trompe L\'Oeil .\n   - Temple of Uggalepih Survival Guide warp puts you a short distance from the Stone Frame.\n5. Defeat the NM, then check the frame and you will obtain a [Key Item] Ripped "Final Fantasy" painting.\n   - If in a party, there is a 10 minute wait between being able to respawn the NM.\n6. Return to Etteh Sulaej. As a reward, you will receive 3000 Gil.',
        notes = nil,
    },
    ['A Thief in Norg!?'] = {
        id = 142,
        start_npc = 'Jaucribaix / Gilgamesh',
        start_zone = 'Norg',
        start_pos = 'L-8',
        description = 'At the close of the Great War, Gilgamesh\'s father trapped a terrible spirit within a helm. That helm has been stolen, and it is your job to hunt down the thief and get it back.',
        reward = 'Myochin Kabuto',
        fame = 'Outlands',
        fame_level = nil,
        title = 'Paragon of Samurai Excellence',
        repeatable = nil,
        previous = {'Yomi Okuri'},
        next = nil,
        requirements = {
            {name = 'Gold Thread', count = 1},
        },
        walkthrough = '1. Speak with Jaucribaix in Norg (K-8) to begin the quest.\n2. Speak to Sanosuke in Port Jeuno (H-8). (Inside the Duty Free Shop.)\n3. Speak to Phoochuchu in Mhaura (H-8) (ground level; under the bridge).\n4. Examine the door on the lower level in Bastok Mines (J-6).  (Close to the Alchemy Guild.)\n   - The door must be closed at the time it is examined.  Examining the door while already opened by another player will result in the cutscene not triggering.\n5. Enter the Waughroon Shrine through the Palborough Mines top floor.\n   - You may use Domenic to get the cutscene.\n     - Homepoint warp is the fastest way if you have it unlocked.\n6. Speak to Jaucribaix in Norg to receive a Banishing Charm.\n7. Trade the Banishing Charm to the Burning Circle in Waughroon Shrine to begin a BC fight.\n   - Inside the BC there will be three Demons: Rasetsu (DRK), Gaki (BLM), and Onki (SMN).\n   - Onki will have an elemental summon, and all three demons are able to use their respective two-hour abilities.\n   - There is a 30 minute time limit.\n   - Trust Magic can be used in the BCNM.\n8. After defeating the demons, you will receive the key item Charred helm.\n9. Speak to Jaucribaix, he will request a Gold Thread.\n10. Trade a Gold Thread to Jaucribaix.\n11. Zone out of Norg, then return to Jaucribaix for your reward.\n   - You can toss the Banishing Charm after completing the quest, as it serves no further purpose.',
        notes = nil,
    },
    ['An Undying Pledge'] = {
        id = 149,
        start_npc = 'Stray Cloud',
        start_zone = 'Norg',
        start_pos = 'H-9',
        description = 'Find Stray Cloud\'s friend Gubokka in the Sea Serpent Grotto.',
        reward = 'Light Buckler',
        fame = 'Outlands',
        fame_level = '4',
        title = nil,
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = {
            {name = '[Key Item] Caliginous Blade', count = 1},
        },
        walkthrough = '1. Speak to Stray Cloud for a cutscene.\n2. Head towards Sea Serpent Grotto, you will get another cutscene shortly before you reach the zoneline.\n3. Once inside Sea Serpent Grotto, head to (K-6) where you will find a ???.\n4. Check the ??? to spawn Glyryvilu.\n5. Defeat Glyryvilu, then check the ??? again to receive the [Key Item] Caliginous Blade.\n6. Return to Stray Cloud for your reward.',
        notes = nil,
    },
    ['Black Market'] = {
        id = 130,
        start_npc = 'Muzaffar',
        start_zone = 'Norg',
        start_pos = 'I-8',
        description = 'Bring sets of either four northern furs, four pieces of eastern pottery, or four southern mummies for a hefty reward.',
        reward = '1,500~3,000 Gil',
        fame = 'Outlands',
        fame_level = '1?',
        title = 'Black Marketeer',
        repeatable = 'Yes',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Eastern Pottery x4 OR', count = 1},
            {name = 'Northern Fur x4 OR', count = 1},
            {name = 'Southern Mummy', count = 4},
        },
        walkthrough = '1. Speak to Muzaffar to begin the quest.\n2. Bring him either 4 Eastern Pottery, 4 Northern Fur, or 4 Southern Mummy to complete the quest:\n   - Eastern Pottery x4 -- 2000 gil, drops off Clockwork Pods in Garlaige Citadel or Fei\'Yin.\n   - Northern Fur x4 -- 1500 gil, drops off Giant Hunter in Qufim Island or Giant Lobber in Lower Delkfutt\'s Tower or Middle Delkfutt\'s Tower.\n   - Southern Mummy x4 -- 3000 gil, drops off Liches in Western Altepa Desert.',
        notes = nil,
    },
    ['Bugi Soden'] = {
        id = 147,
        start_npc = 'Ryoma',
        start_zone = 'Norg',
        start_pos = 'H-8',
        description = 'Wield the katana given to you by Ryoma until it has been drained of its power. Only then will you be ready to inherit the knowledge of the ancient ninja masters.',
        reward = 'Blade: Ku weapon skill',
        fame = 'Other',
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. You cannot start this quest if you have another Weapon Skill Quest active. You must return to the person that gave said quest and quit it to start another.\n2. Speaking with Ryoma will grant you the key item Weapons Training Guide as well as the Kodachi of Trials. You will need to break the latent on the Kodachi of Trials before completing the rest of the quest.\n      - Breaking the Latent\n3. Trade the Kodachi of Trials back to Ryoma. This will give you the key item Map to the Annals of Truth. You will be instructed to travel to the Labyrinth of Onzozo.\n4. Take Silent Oil and Prism Powder with you and head to the Labyrinth of Onzozo. Once inside, follow the path to (H-9) and take the eastern tunnel. Continue northeast through the large room and take the tunnel at (J-8). In the next large room, curve around the eastern wall to the tunnel at (H-7); at the next intersection, head north. Continue north to the border of (I-5)/(I-6), where you will find the ??? to spawn the NM.\n   - Use the Survival Guide teleport if available\n5. This fight is against Megapod Megalops, a crab. It is weak to Ice and Lightning attacks. Once you kill it, re-examine the ??? to receive the key item Annals of Truth.\n6. Go back and speak with Ryoma to receive your reward.',
        notes = 'This fight can be carefully soloed by a 71NIN, and easily duoed with one support job - BRD, WHM, or RDM.\nPoses zero threat to a player in 119 gear.',
    },
    ['Chasing Dreams'] = {
        id = 199,
        start_npc = 'Zoriboh',
        start_zone = 'Rabao',
        start_pos = nil,
        description = 'A young cargo hauler named Sanctia has suddenly left Rabao, and Zoriboh wants you to find her. According to Zoriboh, she has probably headed for Norg to board a ship bound for the Tavnazian Marquisate...',
        reward = 'Venerer Ring\n4,000 Gil',
        fame = 'Rabao',
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = nil,
        next = {'The Search for Goldmane'},
        requirements = {
            {name = 'Eastern Gem', count = 5},
            {name = 'Washu\'s flask', count = 1},
            {name = 'Flask of clam water', count = 1},
            {name = 'Storeroom key', count = 1},
        },
        walkthrough = '1. First head to Rabao and talk to Rudolfo (J-7).\n2. Talk to Zoriboh (F-6).\n3. Head to Norg and talk to Sohyon (J-8).\n4. Then talk to Washu to receive the Key Item: Washu\'s flask.\n5. Head to Korroloka Tunnel. You will need to fill the flask by interacting with four different Giant Clam targets.\n   - The first Giant Clam can be found at F-10 on Map 1 as you zone into Korroloka Tunnel from Zeruhn Mines.\n   - The second Giant Clam can be found at K-6 on Map 3.\n   - The third Giant Clam can be found at G-11 on Map 5.\n   - The final Giant Clam can be found at I-10 on Map 2.\n   - After examining all four Giant Clams, your Washu\'s flask will turn into a Flask of clam water.\n6. Head to Norg and talk to Sohyon (J-8) to receive the Storeroom key.\n7. Talk to Gimb (H-9).\n8. Head to Port Bastok and talk to Kagetora (F-6).\n9. Trade 5 Eastern Gems to Patient Wheel (F-5).\n10. Head to Selbina and talk to Abelard at G-9).\n11. Use the Swirling Vortex in Valkurm Dunes in the cave at (I-9) to Lufaise Meadows.\n12. You will get a cut scene when you zone into Lufaise Meadows.\n13. Head to Rabao, talk to Zoriboh (F-6).',
        notes = nil,
    },
    ['Cloak and Dagger'] = {
        id = 13,
        start_npc = 'Jakoh Wahcondalo',
        start_zone = 'Kazham',
        start_pos = 'J-9',
        description = 'The Chieftainess has come up with a deadly new dagger technique, but needs you to help her devise a way of dodging it. However, you must first complete your training.',
        reward = 'Evisceration weapon skill',
        fame = 'Kazham',
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. You cannot start this quest if you have another Weapon Skill Quest active. You must return to the person that gave said quest and quit it to start another.\n2. Speaking with Jakoh Wahcondalo will grant you the [Key Item] Weapons Training Guide as well as the Dagger of Trials. You will need to break the latent on the Dagger of Trials before completing the rest of the quest.\n      - Breaking the Latent\n3. Trade the Dagger of Trials back to Jakoh Wahcondalo. This will give you the [Key Item] Map to the Annals of Truth. You will be instructed to travel to Gustav Tunnel.\n   - The quickest way to the NM is the level 128 unity warp. This will put right inside the tunnel that\'s leading to the NM. You will also find a Grounds Tome close to your spawn point where you can get Sneak and Invisible.\n4. Take Silent Oils and Prism Powders with you and head to Gustav Tunnel. Once inside, follow the path to (G-9) and take the western tunnel. At the fork in this tunnel, head east. In the large room, take the eastern tunnel at (I-8). The ??? to spawn the NM is at (I-9) Map 2.',
        notes = nil,
    },
    ['Divine Might'] = {
        id = 163,
        start_npc = 'Yve\'noile',
        start_zone = 'The Shrine of Ru\'Avitau',
        start_pos = nil,
        description = 'Use the Ark Pentasphere at the La\'Loff Amphitheater to confront and defeat all five Crystal Warriors simultaneously.',
        reward = 'Shard of Apathy\nShard of Arrogance\nShard of Cowardice\nShard of Envy\nShard of Rage\nOne of the following:',
        fame = 'Outlands',
        fame_level = nil,
        title = 'Pentacide Perpetrator',
        repeatable = 'Yes',
        previous = {'Zilart Mission 13'},
        next = {'Zilart Mission 15'},
        requirements = {
            {name = 'Illuminink (Also needed to do the quest a 2nd time)', count = 1},
            {name = 'Parchment (Also needed to do the quest a 2nd time)', count = 1},
            {name = 'Ark Pentasphere', count = 1},
        },
        walkthrough = 'Note: If you complete this quest, Zilart Mission 14, will be considered completed as well.\n!!!NOTE:!!! You must flag this quest at the blank target in The Shrine of Ru\'Avitau or you WILL NOT receive credit and will have to re-aquire another Ark Pentasphere.',
        notes = '1. Prior to the June 2016 Version Update, a player would have to trade their items for an Ark Pentasphere or Moonlight ore on a clear night during the full moon from midnight to 3:00 a.m. This was eased along with a batch of other older quest requirements.',
    },
    ['Don\'t Forget the Antidote'] = {
        id = 192,
        start_npc = 'Edigey',
        start_zone = 'Rabao',
        start_pos = 'F-9',
        description = 'Edigey wants you to bring him some sand scorpion poison so he can make an antidote, an essential item for the desert caravans.',
        reward = 'Dotanuki\n1,800 gil',
        fame = 'Rabao',
        fame_level = '4',
        title = 'Desert Hunter',
        repeatable = 'Yes',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Desert Venom', count = 1},
        },
        walkthrough = '1. Speak to Edigey to begin this quest.\n2. Desert Venom drops off Doom Scorpions in Eastern Altepa Desert, Tulwar Scorpions in Western Altepa Desert, or purchased off the Auction House.\n3. Trade the Desert Venom to Edigey for your reward.\n   - The first time you complete this quest you will get a Dotanuki.  Each time after you will only get gil.',
        notes = nil,
    },
    ['Even More Gullible\'s Travels'] = {
        id = 9,
        start_npc = 'Magriffon',
        start_zone = 'Kazham',
        start_pos = 'I-7',
        description = 'Magriffon has spent all of his (your?) money to save a maiden in distress. Now he needs someone to save him (again) from getting kicked out of the bed & breakfast before he has completed his "top-secret" mission.',
        reward = 'Rafflesia Nectar x3',
        fame = 'Kazham',
        fame_level = '7',
        title = 'Even More Gullible\'s Travels',
        repeatable = 'No',
        previous = {'Gullible\'s Travels'},
        next = {'The Opo-opo and I'},
        requirements = {
            {name = '15,000 - 35,000 gil', count = 1},
            {name = 'Treasure map (Key Item)', count = 1},
        },
        walkthrough = '1. Zone after finishing the previous quest.\n2. Return to Magriffon (I-7) who will give you Treasure map (Key Item) after you trade him more gil.\n3. Go to the three places in Yuhtunga Jungle on the Treasure map: (F-7) (H-10) and (I-12).\n4. At each spot on the map you will find a Blue Rafflesia.\n   - Examining each Blue Rafflesia will give you a Rafflesia Nectar.\n5. Return to Magriffon to finish the quest.',
        notes = nil,
    },
    ['Everyone\'s Grudge'] = {
        id = 134,
        start_npc = 'Magephaud',
        start_zone = 'Norg',
        start_pos = nil,
        description = 'Bring back three gold beastcoins if you want to learn how to rid yourself of the Tonberries\' rancor.',
        reward = '[Key Item] Tonberry key (Zilart)',
        fame = 'Outlands',
        fame_level = '2',
        title = 'Honorary Doctorate, Majoring in Tonberries',
        repeatable = 'Yes',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Gold Beastcoin', count = 3},
            {name = ' Gil (varies with hate)', count = 1},
        },
        walkthrough = '1. Speak to Magephaud in Norg (I-8) to begin the quest.\n   - You must have defeated a Tonberry before being able to start this quest.\n2. Trade him 3 Gold Beastcoins to receive the [Key Item] Tonberry key (Zilart).',
        notes = nil,
    },
    ['Everyone\'s Grudging'] = {
        id = 4,
        start_npc = 'Jakoh Wahcondalo',
        start_zone = 'Kazham',
        start_pos = 'J-9',
        description = 'You have been cursed by the Tonberries\' rancor flames, and Kazham\'s chieftainness has ordered you out of the village.',
        reward = '11,000 gil',
        fame = 'Kazham',
        fame_level = nil,
        title = 'Excommunicate of Kazham',
        repeatable = nil,
        previous = {'A Question of Taste'},
        next = nil,
        requirements = {
            {name = 'Unlit Lantern', count = 1},
            {name = 'Paintbrush of souls', count = 1},
            {name = 'Rancor Flame', count = 1},
        },
        walkthrough = '1. To begin this quest you must have traded an Unlit Lantern to the Altar of Rancor and received the Rancor Flame at some point before. It helps to have a Rancor Flame on you.\n2. Once you have used a Rancor Flame, talk to Jakoh Wahcondalo in Kazham who will tell you to leave her village.  The other NPCs in the room tell you to go the Den of Rancor/Temple of Uggalepih complex to be cleansed and then come back.\n   - You get the title "Excommunicate of Kazham" as soon as this quest becomes active.\n3. You will need to obtain at least 1 Unlit Lantern to cleanse the Rancor.\n   - The lanterns are dropped by Tonberry Maledictors.\n   - Ideally, it is easiest to use 4 players with 4 lanterns, however you just need to light all 4 lamps at the Altar.  You can actually solo this by making 4 trips back and forth between the Rancor Flame and the altar.  The altar seems to stay lit for quite a while.\n4. Once you have the Unlit Lanterns, go back to the main entrance and make all right turns to exit at F-5. Now hug the left wall to re-enter the temple at H-11.\n5. Once in the temple, head to I-10 and defeat the Temple Guardian to open the door.\n6. Past the guardian\'s door, head north to I-7 inside the paintings room. A Paintbrush of souls is needed to proceed into the Den of Rancor.\n7. Once you are in the Den of Rancor, go to the Altar of Rancor at D/E-5. You can easily get there by hugging the right wall from where you enter the Den. Once there, the Unlit Lanterns must be traded to the Altar of Rancor to receive a Rancor Flame.\n8. Once you have your Rancor Flames, you want to visit the other Altar of Rancor at I/J-13. Trade the Rancor Flames to the Altar of Rancor.\n9. After the fourth lantern is lit, a bomb NM called Rancor Torch will appear.\n10. Kill the Rancor Torch and head back to Kazham and talk to the Chieftainess for your reward.',
        notes = nil,
    },
    ['Fish Favors the Bold'] = {
        id = 202,
        start_npc = 'Irmilant',
        start_zone = 'Rabao',
        start_pos = 'G-7',
        description = 'The exalted fisherman has posed to you a challenge. Collect legendary fish from the four corners of Vana\'diel.',
        reward = 'Ebisu F. Rod +1',
        fame = 'Outlands',
        fame_level = nil,
        title = 'Exalted Fisherman',
        repeatable = nil,
        previous = {'Indomitable Spirit'},
        next = nil,
        requirements = {
            {name = 'Ebisu Fishing Rod', count = 1},
        },
        walkthrough = 'Before starting this quest, you must have fished up 100 different fish.\n1. Doing the quest Fisherman\'s Heart, will allow you to see how many unique fish you have caught, by talking to Katsunaga in Mhaura.\nMust have Rise of the Zilart / Chains of Promathia / Treasures of Aht Urhgan / Wings of the Goddess / Seekers of Adoulin / Scars of Abyssea expansions installed.\n2. Talk to Irmilant to start the quest.\n3. You will need to catch, in any order, the following 5 Legendary fish. Afterwards, you must trade them to Irmilant:\n   - Matsya\n   - Dragon\'s Tabernacle\n   - Quicksilver Blade\n   - Phantom Serpent\n   - Lord of Ulbuka\n4. If you have already caught one of these legendary fish prior to activating this quest, (see Katsunaga in Mhaura to check) you may purchase that fish from the Auction House, Bazaar or have someone else fish it up for you and it will still count towards quest completion. Basically, the only trigger to Irmilant accepting a fish is that it is registered under Katsunaga that it has been caught by you.\n   - Example: You fished up Matsya for the Shaper\'s Shawl which caused Matsya to be registered by Katsunaga, you are able to purchase a Matsya off the Auction House and trade into Irmilant for credit.\n5. After you trade in all five, trade your Ebisu Fishing Rod to him in order to upgrade it.',
        notes = nil,
    },
    ['Forge Your Destiny'] = {
        id = 129,
        start_npc = 'Jaucribaix',
        start_zone = 'Norg',
        start_pos = 'K-8',
        description = 'A lump of bomb steel and a sacred branch are required to make a new katana. You will have to ask Jaucribaix\'s pupils to find out where you can get these items.',
        reward = 'Mumeito\nAbility to become a Samurai.',
        fame = 'Outlands',
        fame_level = nil,
        title = 'Bushido Blade',
        repeatable = 'No',
        previous = nil,
        next = {'The Sacred Katana'},
        requirements = {
            {name = 'Bomb Steel', count = 1},
            {name = 'Sacred Branch', count = 1},
            {name = 'Hatchet', count = 1},
        },
        walkthrough = '1. Speak to Jaucribaix in Norg (K-8) to begin the quest.\n2. Speak to Aeka (I-8) to receive Oriental Steel.\n3. Speak to Ranemaud (I-7) to receive a Sacred Sprig.\n4. Travel to Konschtat Highlands (D-8), trade the Oriental Steel to the ??? inside the cave to spawn a Bomb Notorious Monster named Forger, approximately level 33.\n   - The level 99 Unity warp (Sleepy Mabel) will place you close to this point at (G-7).\n5. Once the Forger is defeated, a Bomb Steel will drop.\n   - If you are defeated while fighting the Forger or somehow lose the Bomb Steel before the next part, Aeka can give you another Oriental Steel in exchange for a Darksteel Ore.\n   - If you are doing the quest for multiple people, you must wait 4 minutes to re-spawn the Forger for another Bomb Steel.\n6. Purchase a Hatchet and travel to The Sanctuary of Zi\'Tah. You will find an area off of the map in the northern part of (K-10) that will take you to a block at (L-9).  There you will find a ??? spot you may reach by climbing up a nearby rock.  Use the Hatchet on the ??? spot to spawn a Treant Notorious Monster named Guardian Treant.\n   - The level 122 Unity warp (Keeper of Heiligtum) will place you close to this point at (K-12).\n   - If you are doing the quest for multiple people, you only need to kill the Treant once.\n7. Once the Treant is defeated, trade the Sacred Sprig to the ??? to receive a Sacred Branch.\n8. Trade the Bomb Steel and the Sacred Branch to Jaucribaix.\n9. Return in 72 in-game hours (3 real-life hours) to receive your reward.',
        notes = '1. The Mumeito is required to do the AF1 quest: The Sacred Katana.  If you plan on levelling Samurai, it would be wise to hold on to it, otherwise you will have to pay Ranemaud 30,000 gil for a replacement.',
    },
    ['Greetings to the Guardian'] = {
        id = 2,
        start_npc = 'Hari Pakhroib',
        start_zone = 'Kazham',
        start_pos = 'I-11',
        description = 'Take your offering to the guardian of Kazham to the altar on the crater of Mount Yuhtunga.',
        reward = '5,000 gil',
        fame = 'Kazham',
        fame_level = '7',
        title = 'Kazham Caller',
        repeatable = 'Yes',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Wild Pamamas', count = 1},
            {name = 'Wild Pamamas\n-or-', count = 1},
            {name = 'Wild Melon', count = 1},
        },
        walkthrough = '1. Speak to Hari Pakhroib (I-11), who wants Wild Pamamas.\n   - Wild Pamamas drop off Young Opo-opo in Yuhtunga Jungle.\n   - They can also sometimes be found on the Auction House.\n2. Head to Ifrit\'s Cauldron using the entrance from (G-6) in Yhoator Jungle.\n3. Once inside Ifrit\'s Cauldron, take the left path at the fork and continue on until you find the Altar of Ashes located at (I-9) on map 2.\n   - Alternatively, utilize Unity 125 teleport to travel quickly to Map 3, taking exit G > A > B to quickly reach (I-9) of Map 2.\n4. Trade the Wild Pamamas to the Altar.\n5. Return to Hari Pakhroib for your reward.',
        notes = nil,
    },
    ['Gullible\'s Travels'] = {
        id = 8,
        start_npc = 'Magriffon',
        start_zone = 'Kazham',
        start_pos = 'I-7',
        description = 'Magriffon has given all his worldly possessions to save a pack of poor Opo-opos from starvation. Now he needs someone to save him from getting kicked out of the bed & breakfast before he has completed his "top-secret" mission.',
        reward = nil,
        fame = 'Kazham',
        fame_level = '6',
        title = 'Gullible\'s Travels',
        repeatable = 'No',
        previous = nil,
        next = {'Even More Gullible\'s Travels'},
        requirements = {
            {name = '10,000-30,000 gil', count = 1},
        },
        walkthrough = '1. Speak to Magriffon (I-7) inside Celodekhi\'s B&B.\n2. Trade him the gil he asks for.',
        notes = nil,
    },
    ['I\'ll Take the Big Box'] = {
        id = 144,
        start_npc = 'Ryoma',
        start_zone = 'Norg',
        start_pos = 'H-8',
        description = 'The trick box you brought back to Norg has been identified as a fake. Your assistance is required in finding the real box. Start your search by pressing Ensetsu in Bastok for more information.',
        reward = 'Ninja Hakama',
        fame = 'Other',
        fame_level = '1',
        title = nil,
        repeatable = 'Yes',
        previous = {'20 in Pirate Years'},
        next = {
            'True Will',
            'Borghertz\'s Lurking Hands',
        },
        requirements = {
            {name = 'Oak Pole', count = 1},
        },
        walkthrough = '1. Travel to Norg and speak with Ryoma to receive the quest.\n   - If you just completed 20 in Pirate Years you will need to zone and re-enter Norg for Ryoma to begin this quest\n2. Talk to Ensetsu in Port Bastok at (I-5), who tells you to speak with Leodarion.\n3. Head to Rabao and talk to Leodarion at (F-8) on the west side of the lake near the windmill.\n4. Leodarion will request an Oak Pole, which is purchasable via Sparks from a Records of Eminence NPC:\n   - Rolandienne in Southern San d\'Oria (G-10)\n   - Isakoth in Bastok Markets (E-11)\n   - Fhelm Jobeizat in Windurst Woods (J-10)\n   - Eternal Flame in Western Adoulin (H-11)\n     - Costs 156 Sparks. Can be found under "Equ. Lv. 40 - 50.", on Page 2.\n5. After trading it to him, speak to Leodarion again on the next Vana\'diel day. You will receive the [Key Item]Seance staff with instructions to travel to Mhaura.\n6. Once in Mhaura, take the ferry to Selbina so that you will be traveling at nighttime.\n   - Suitable ferry departure times for this quest leave Mhaura at 16:00 and 0:00.\n7. The NM Enagakure will spawn on the main deck.\n   - On the ferry departing at 0:00, it will already be on the deck and will disappear at 4:00.\n   - On the ferry departing at 16:00, you must wait for night time at 20:00 for it to appear.\n   - Make sure you have unloaded FastCS, as they will cause you to be booted straight to Selbina if zoning into the Mhaura-Selbina Ferry at night.\n8. Once you have defeated Enagakure, make sure you have at least one inventory slot free and wait until the ferry docks in Selbina.\n9. You will receive a cutscene, Ninja Hakama, and the quest will be complete.',
        notes = nil,
    },
    ['Indomitable Spirit'] = {
        id = 201,
        start_npc = 'Irmilant',
        start_zone = 'Rabao',
        start_pos = 'G-7',
        description = 'Irmilant has asked you to bring the two base materials required to craft a legendary fishing rod. These materials seem to have found their way into the bellies of sea creatures that still elude the finest fishermen.',
        reward = 'Ebisu Fishing Rod',
        fame = 'Rabao',
        fame_level = nil,
        title = 'Indomitable Fisher',
        repeatable = nil,
        previous = nil,
        next = {'Fish Favors the Bold'},
        requirements = {
            {name = '[Key Item] Serpent Rumors, Opal Silk, and Saber Shoot', count = 1},
        },
        walkthrough = '1. To begin this quest in your log, you need the Serpent Rumors key item.  It can be purchased from Fennella in Port Windurst (C-8) for 95,000 Guild Points with Fishing rank Adept or higher.\n   - You can still obtain the other items needed for this quest before initiating it.\n2. Turn in Liks and Gugrusaurus to Zaldon to obtain Opal Silk and Saber Shoot, respectively.\n   - About a ~.5% chance to get each.\n3. Speak to Irmilant in Rabao (G-7).\n4. Trade the Opal Silk and Saber Shoot to Irmilant.\n5. Return to Irmilant after conquest tally to receive your reward.',
        notes = '1. The Ebisu Fishing Rod can be re-obtained if dropped by mistake.\n   - You\'ll need to speak with Irmilant who will request you trade him a Takitaro.',
    },
    ['It\'s Not Your Vault'] = {
        id = 137,
        start_npc = 'Keal',
        start_zone = 'Norg',
        start_pos = 'H-8',
        description = 'Bring back a sealed iron box from the Sahagin-infested Norg vault.',
        reward = 'Tonko: Ichi (Scroll)',
        fame = 'Outlands',
        fame_level = '3',
        title = nil,
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Sealed iron box', count = 1},
        },
        walkthrough = '1. Speak to Keal (H-8) to begin this quest. He walks around by the survival guide.\n2. Exit Norg into Sea Serpent Grotto.\n3. Once in Sea Serpent Grotto head South until you reach (H-7), go West from there.\n4. Turn South at (F-7) and continue West, follow the path as it turns North at (B-7).\n5. The ??? you\'re looking for is in the room at (C-5).\n6. Examine the ??? to get the Key Item Sealed iron box.\n7. Return to Keal to complete the quest.',
        notes = nil,
    },
    ['Like a Shining Subligar'] = {
        id = 138,
        start_npc = 'Heiji',
        start_zone = 'Norg',
        start_pos = 'I-7',
        description = 'Ten rusty subligaria are needed for the training of young ninjas. Heiji will accept them one at a time.',
        reward = 'Kurayami: Ichi (Scroll)',
        fame = 'Norg',
        fame_level = '3',
        title = 'Looks Sublime in a Subligar',
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = {
            {name = '10 Rusty Subligar', count = 1},
        },
        walkthrough = nil,
        notes = nil,
    },
    ['Like Shining Leggings'] = {
        id = 139,
        start_npc = 'Heizo',
        start_zone = 'Norg',
        start_pos = 'H-7',
        description = 'Ten pairs of rusty leggings are needed for the training of young ninjas. Heizo will accept them one at a time.',
        reward = 'Dokumori: Ichi (Scroll)',
        fame = 'Norg',
        fame_level = '3',
        title = 'Looks Good in Leggings',
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = {
            {name = '10 Rusty Leggings', count = 1},
        },
        walkthrough = nil,
        notes = nil,
    },
    ['Mama Mia'] = {
        id = 131,
        start_npc = 'Mamaulabion',
        start_zone = 'Norg',
        start_pos = 'G-6',
        description = 'Mamaulabion would like you to bring him any "thuper-dee-duper, overflowing with thpethial power itemth" you happen to come across in your travels. However, he was not able to provide you with any details on their whereabouts.',
        reward = 'Evoker\'s Ring',
        fame = 'Norg',
        fame_level = '4',
        title = nil,
        repeatable = 'Yes',
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. Speak to Mamaulabion at (G-6) in Norg to activate the quest (this does not need to be done before obtaining the seven items).\n2. Obtain the following seven items by selecting them as your reward after defeating the seven avatars below in the battles listed below\n   - Trial by Fire (Ifrit): Egil\'s Torch\n   - Trial by Ice (Shiva): Rust \'B\' Gone\n   - Trial by Wind (Garuda): Bubbly Water\n   - Trial by Earth (Titan): Desert Light\n   - Trial by Lightning (Ramuh): Elder Branch\n   - Trial by Water (Leviathan): Eye of Nept\n   - The Moonlit Path (Fenrir): Ancients\' Key\n3. Return all seven items to Mamaulabion (the items must be traded one at a time and it is not necessary to turn in all seven at once).\n4. Wait until midnight (JST), then speak with Mamaulabion once more to receive the Evoker\'s Ring.\n5. Note that the quest is only repeatable if Evoker\'s Ring is dropped.',
        notes = nil,
    },
    ['Missionary Man'] = {
        id = 7,
        start_npc = 'Rauteinot',
        start_zone = 'Kazham',
        start_pos = 'G-9',
        description = 'First, find a slab of Elshimo marble in the Yuhtunga Jungle to help the young missionary realize his vision.',
        reward = 'Teleport-Yhoat (Scroll)',
        fame = 'Kazham',
        fame_level = '3',
        title = nil,
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. Speak to Rauteinot who asks for a slab of Elshimo Marble.\n   - Elshimo Marble drops off Ivory Lizard in Yuhtunga Jungle.\n2. Trade the Elshimo Marble to Rauteinot. You will receive Rauteinot\'s parcel.\n3. Head to Northern San d\'Oria and speak to Mulaujeant at (E-5) near the Blacksmithing guild on the second floor.\n4. Wait until one Earth minute has passed and speak to Mulaujeant again to be given the Sublime statue of the Goddess.\n5. Return to Rauteinot for your reward.',
        notes = nil,
    },
    ['Open Sesame'] = {
        id = 165,
        start_npc = 'Lokpix',
        start_zone = 'Eastern Altepa Desert',
        start_pos = 'G-7',
        description = 'There\'s supposedly a way to open that troublesome door in the Quicksand Caves by yourself. If you wish to know the secret, bring back a tremorstone and a meteorite. Should you lack a meteroite, either a soil gem or twelve soil geodes will suffice.',
        reward = '[Key Item] Loadstone',
        fame = 'Outlands',
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Tremorstone and one of the following:\n1x Meteorite or 1x Soil Gem or 12x Soil Geode', count = 1},
        },
        walkthrough = '1. Speak to Lokpix in Eastern Altepa Desert at (G-7).  He will request a  Tremorstone in addition to one of the following options:\n   - Meteorite\n     - Dropped by Crawlers in West Sarutabaruta, on Starfall Hillock ().\n     - Awarded in Colonization Reives in Kamihr Drifts (Requires [Key Item] "Fragmenting" from Quest: Breaking the Ice) ().\n     - Awarded in Colonization Reives in Outer Ra\'Kaznar (Requires [Key Item] "Pulverizing" from Quest: Lerene\'s Lament) ().\n     - Gathered in Mog Gardens (Requires Mineral Vein Rank 3).\n   - Soil Gem\n     - Crafted from Goldsmithing.\n   - Soil Geode x12.\n2. You may find Unity Warp 125 to Quicksand Caves helpful to reach the Cloister of Tremors containing the Tremorstone in the west part of the caves.\n3. Trade him the items at the same time to receive your reward.\n   - The [Key Item] Loadstone will allow you to open the weighted doors in Quicksand Caves solo.',
        notes = nil,
    },
    ['Personal Hygiene'] = {
        id = 10,
        start_npc = 'Gatih Mijurabi',
        start_zone = 'Kazham',
        start_pos = 'I-8',
        description = 'The Mithra of Kazham are having a hard time holding in their lunches, thanks to the hideous odor you obtained after getting too close to the blue Rafflesia pollen. The only way to get clean is by taking a long dip in a hot spring located deep beneath the sea.',
        reward = 'Mithran Stone',
        fame = 'Kazham',
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'Even More Gullible\'s Travels'},
        next = nil,
        requirements = nil,
        walkthrough = '1. After completing Even More Gullible\'s Travels you will have a scent of the Rafflesia flowers on you.\n   - This scent will repulse all Mithra in Kazham but is required to start the quest The Opo-opo and I.\n2. Speak to Gatih Mijurabi (I-8) to begin this quest to remove the scent.\n3. The hot springs is located in Korroloka Tunnel (G-9) on map 4.\n4. Stand yourself under the waterfall for approximately 5 minutes.\n   - When you are in the right spot, you will get the message that "The water in this spring is pleasant and tepid. This looks like a nice place to warm yourself up."\n   - When you exit the hot spring after standing under the waterfall for the right amount of time, you will get another message informing you that the smell of the Rafflesia pollen is gone.\n5. The waterfall is guarded by several leeches that aggro to level 99 players.\n6. Return to Gatih Mijurabi to complete the quest.',
        notes = nil,
    },
    ['Secret of the Damp Scroll'] = {
        id = 135,
        start_npc = 'Shivivi',
        start_zone = 'Norg',
        start_pos = 'J-8',
        description = 'Take the damp scroll you have to Horlais Peak and dip it into the hot springs there. Only then will you be able to read it.',
        reward = 'Jubaku: Ichi (Scroll)',
        fame = 'Outlands',
        fame_level = '3',
        title = 'Cracker of the Secret Code',
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Damp Scroll', count = 1},
        },
        walkthrough = '1. To begin this quest you first need a Damp Scroll.\n   - The Damp Scroll can either be fished up in Sea Serpent Grotto or purchased off the Auction House.\n2. You need to have the Damp Scroll in your inventory when you speak to Shivivi to begin this quest.\n3. Take the scroll to Horlais Peak (Hot Springs side) and trade it to the Hot Springs there.\n4. This will transform the scroll into a Jubaku: Ichi (Scroll).',
        notes = nil,
    },
    ['Skyward Ho, Voidwatcher!'] = {
        id = 104,
        start_npc = 'Kieran',
        start_zone = 'Norg',
        start_pos = nil,
        description = 'Planar rifts have been reported in Ru\'Aun Gardens, Ve\'Lugannon Palace, and the Shrine of Ru\'Avitau. Engage the Voidwalkers at each location and obliterate them!',
        reward = nil,
        fame = 'N/A',
        fame_level = 'N/A',
        title = nil,
        repeatable = nil,
        previous = {'VW Op. #115: Li\'Telor Variant'},
        next = nil,
        requirements = nil,
        walkthrough = '1. After completing VW Op. 115: Li\'Telor Variant and receiving the Ashen stratum abyssite III from Kieran, this quest is automatically flagged.\n2. Engage in and complete the 3 Tier III Voidwatch battles in the Tu\'Lia region:\n   - Aello in Ru\'Aun Gardens(G-5), (I-11), (J-6)\n   - Qilin in The Shrine of Ru\'Avitau (map 2)(F-6), (F-9), (J-6)\n   - Uptala in Ve\'Lugannon Palace(D-5), (G-13), (M-8)\n3. After defeating all 3, return to Norg and speak to Kieran at (H-8).\n   - You cannot get the next cutscene if you do not speak to Kieran first. If you speak to Gilgamesh then Kieran, you must zone to get the cutscene from Gilgamesh.\n4. Return to Norg and speak to Gilgamesh to complete the quest.',
        notes = nil,
    },
    ['Soul Searching'] = {
        id = 162,
        start_npc = 'Cermet Headstone',
        start_zone = 'The Sanctuary of Zi\'Tah',
        start_pos = 'I-7',
        description = 'Dispel the troubled souls of those who perished while on their pilgrimages.',
        reward = 'Bat Earring',
        fame = 'Outlands',
        fame_level = nil,
        title = 'Guider of Souls to the Sanctuary',
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Key Item: Prismatic fragment', count = 1},
        },
        walkthrough = '1. Touch the Cermet Headstone with the key item in your posession after completing Zilart Mission 7.',
        notes = nil,
    },
    ['Stop Your Whining'] = {
        id = 132,
        start_npc = 'Washu',
        start_zone = 'Norg',
        start_pos = 'J-8',
        description = 'Fill up an empty barrel with Opo-opo brew found fermenting in trees in Yhoator Jungle, and bring it back to Norg ASAP.',
        reward = 'Hojo: Ichi (Scroll)',
        fame = 'Norg',
        fame_level = '4',
        title = 'Apprentice Sommelier',
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Empty barrel', count = 1},
            {name = 'Barrel of Opo-Opo brew', count = 1},
        },
        walkthrough = '1. Travel to Norg and enter the Buccaneer\'s Quarters at (J-8).\n2. Talk to Washu.\n3. Washu will give you an  Empty Barrel. You will need to fill it with Opo-Opo brew found in a Yhoator Jungle tree.\n4. You will need to examine a ??? that spawns randomly in Yhoator Jungle.\n5. Once you find the ??? the  Empty Barrel will turn into a Barrel of Opo-Opo brew.\n6. Return to Washu to complete the quest.',
        notes = nil,
    },
    ['Thanks for All the Fish'] = {
        id = 203,
        start_npc = 'Jourdenaux',
        start_zone = 'Rabao',
        start_pos = 'F-8',
        description = 'Lu Shang\'s fishing rod has a hidden power deep inside, which Jordenaux has offered to draw forth if he deems you worthy--by collecting 60 types of fish and fulfilling all Records of Eminence objectives in the "Fishing (Tenacity)" category.',
        reward = 'Lu Shang\'s Fishing Rod +1',
        fame = 'Outlands',
        fame_level = nil,
        title = 'Fish Whisperer',
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Lu Shang\'s Fishing Rod', count = 1},
        },
        walkthrough = 'You must first complete the First Step Forward Records of Eminence objective\n1. Speak to Jourdenaux while in possession of a Lu Shang\'s Fishing Rod to flag this quest.\n2. This will unlock a new Records of Eminence category "Fishing > Fishing (Tenacity)"\n3. You must now do the following:\n   - Catch 60 different types of fish\n     - You can use any rod to accomplish this.\n     - Catching the fish can be done in tandem to completing the Fishing (Tenacity) objectives, or the fish can have been caught previously.\n     - Use Katsunaga to tell you how many types of fish you have caught so far.\n   - Complete all Fishing (Tenacity) objectives\n     - You must complete all of the objectives under this category using only your Lu Shang\'s Fishing Rod.\n     - Lures to catch multiple fish at once is effective for certain tasks that require many fish.\n4. After completing all of the objectives, trade your Lu Shang\'s Fishing Rod to Jourdenaux to complete the quest and for your reward.',
        notes = nil,
    },
    ['The Firebloom Tree'] = {
        id = 1,
        start_npc = 'Soun Abralah',
        start_zone = 'Kazham',
        start_pos = 'H-9',
        description = 'Journey to the Yuhtunga Jungle and retrieve a piece of firebloom wood from the most fire-resistant side of the Firebloom Tree. To check the most fire-resistant side, you must take a vine from each side of the tree to Ifrit\'s Cauldron for testing.',
        reward = '5,000 Gil',
        fame = 'Kazham',
        fame_level = '6',
        title = nil,
        repeatable = 'Yes',
        previous = nil,
        next = nil,
        requirements = {
            {name = '[Key Item] Northern vine', count = 1},
            {name = '[Key Item] Eastern vine', count = 1},
            {name = '[Key Item] Southern vine', count = 1},
            {name = '[Key Item] Western vine', count = 1},
            {name = '[Key Item] Firebloom Tree wood', count = 1},
        },
        walkthrough = '1. Soun Abralah needs a piece of unburnable wood from the Firebloom Tree.\n2. Visit the Firebloom Tree Roots at Yuhtunga Jungle (H-9)\n   - Survival Guide or Outpost warp and head northeast\n3. Harvest the Eastern vine, Northern vine, Western vine, and Southern vine by clicking on the trees\n   - No Hatchets required\n   - The Western vine is in the tunnel.\n4. Head to Ifrit\'s Cauldron to test the vines\' fire resistance in the Flame Spouts.\n   - You need to touch 3 Flame Spouts\n   - Recommended to use the Survival Guide warp, then go K -> L -> H -> Ash Dragon area.\n5. Return to the appropriate Firebloom Tree Root (only one will work, and it will match your remaining Key Item) and obtain wood\n   - Again, no Hatchet is required.\n6. Return to Soun Abralah for your reward.',
        notes = nil,
    },
    ['The Immortal Lu Shang'] = {
        id = 196,
        start_npc = 'Irmilant',
        start_zone = 'Rabao',
        start_pos = 'G-7',
        description = 'Irmilant has said he will repair your broken Lu Shang\'s fishing rod. Along with the broken fishing rod, you must bring him a piece of ancient lumber and two light crystals.',
        reward = 'Repaired Lu Shang\'s Fishing Rod',
        fame = 'Rabao',
        fame_level = nil,
        title = 'The Immortal Fisher, Lu Shang',
        repeatable = 'Yes',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Broken Lu Shang\'s Rod', count = 1},
            {name = 'Piece of Ancient Lumber', count = 1},
            {name = 'Light Crystal', count = 2},
        },
        walkthrough = '1. Trade Irmilant in Rabao (G-7) a Broken Lu Shang\'s Rod, a Piece of Ancient Lumber, and Light Crystal x2.\n   - You DO NOT need to have completed The Competition / The Rivalry in order to complete this quest and have your rod fixed.',
        notes = nil,
    },
    ['The Kuftal Tour'] = {
        id = 195,
        start_npc = 'Datta',
        start_zone = 'Rabao',
        start_pos = 'F-7',
        description = 'You have been asked to participate in a tour planned by Datta. Travel to the cliff inside the entrance to the Kuftal Tunnel with a party of two or more people of level forty or less, then meet with Datta\'s partner, Hawk Nose.',
        reward = '8,000 gil',
        fame = 'Rabao',
        fame_level = nil,
        title = 'Kuftal Tourist',
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. Speak to Datta to begin this quest.\n2. Form a party with at least two people who are below level 40.\n   - Alter egos and fellows do not count toward the requirements.\n   - Level sync does work\n3. Head to Kuftal Tunnel and examine the ??? near the entrance for a cutscene.\n   - If you purchase a chocobo in Rabao you can cross the desert without having to worry about aggro.\n   - The Survival Guide also puts you right at the entrance.\n   - The only monsters near the ??? are Lizards who do not aggro at all.\n4. Once you get the cutscene in Kuftal Tunnel, return to Datta for your reward.',
        notes = 'Similar to When Wills Collide and Mercenary Camp, this CS displays fellow party members, a very rare occurrence.\n1. You and your party members overlook the Kuftal tunnel. It\'s not much of a different angle than you\'d see in game.\n2. You can watch this CS again with the Goblin Footprint after returning to Datta\nOriginally this quest required 6 players, but was dropped to 2 with the June 2015 Update',
    },
    ['The Missing Piece'] = {
        id = 193,
        start_npc = 'Alfesar',
        start_zone = 'Rabao',
        start_pos = 'H-7',
        description = 'The friar Alfesar has asked you to find the remaining part of a stone tablet that was found in the Quicksand Caves that lie beneath the Altepa Desert.',
        reward = 'Scroll of Teleport-Altep',
        fame = 'Rabao',
        fame_level = '4',
        title = 'Acquirer of Ancient Arcanum',
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Ancient tablet fragment', count = 1},
        },
        walkthrough = '1. Speak to Alfesar who asks you to help him find an Ancient tablet fragment.\n2. The Ancient tablet fragment is found by checking one of 5 ???s in the Quicksand Caves.\n   - (H-6), (H-10), (E-9) on Map 1\n   - (D-9), (L-11) on Map 2\n   - As soon as the ??? is found, it instantly respawns in one of the 5 locations listed above.\n3. Return to Alfesar who gives you Tablet of ancient magic and Letter from Alfesar.\n4. Speak to Charlaimagnat, Northern San d\'Oria (M-7).\n5. Zone and return to Charlaimagnat after one earth minute for your reward.',
        notes = nil,
    },
    ['The Opo-opo and I'] = {
        id = 11,
        start_npc = 'Lulupp',
        start_zone = 'Kazham',
        start_pos = 'G-7',
        description = 'The Opo-opo in Kazham love your new "fragrance." Bring them what they want--in the correct order-- and they will make you their king!',
        reward = 'Opo-opo Crown',
        fame = 'Kazham',
        fame_level = nil,
        title = 'King of the Opo-opos',
        repeatable = nil,
        previous = {'Even More Gullible\'s Travels'},
        next = {'Personal Hygiene'},
        requirements = {
            {name = 'Broken Mithran Rod', count = 1},
            {name = 'Workbench', count = 1},
            {name = 'Ten of Coins', count = 1},
            {name = 'Sands of Silence', count = 1},
            {name = 'Wandering Bulb', count = 1},
            {name = 'Giant Fish Bones', count = 1},
            {name = 'Blackened Toad', count = 1},
            {name = 'Wyvern Skull', count = 1},
            {name = 'Ancient Salt', count = 1},
            {name = 'Lucky Egg', count = 1},
        },
        walkthrough = '1. Once you have finished Even More Gullible\'s Travels and received the scent, speak to Lulupp (G-7) by the docks for a cutscene.\n2. You must trade these items in order to the following Opo-opo\'s:',
        notes = nil,
    },
    ['The Potential Within'] = {
        id = 146,
        start_npc = 'Jaucribaix',
        start_zone = 'Norg',
        start_pos = 'K-8',
        description = 'Wield the katana given to you by Jaucribaix to find your true potential. When the blade has lost its power, then you will know you have been accepted.',
        reward = 'Tachi: Kasha weapon skill',
        fame = 'Other',
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. You cannot start this quest if you have another Weapon Skill Quest active. You must return to the person that gave said quest and quit it to start another.\n2. Speaking with Jaucribaix will grant you the key item Weapons Training Guide as well as the Tachi of Trials. You will need to break the latent on the Tachi of Trials before completing the rest of the quest.\n      - Breaking the Latent\n3. Trade the Tachi of Trials back to Jaucribaix. This will give you the key item Map to the Annals of Truth. You will be instructed to travel to Kuftal Tunnel.\n4. Unity Warp(125) brings you relatively close, and at item level you will have no issues kiting everything on your way to spawn the NM.\n5. Take Silent Oil and Prism Powder with you and head to Kuftal Tunnel. When you enter the tunnel, follow the path to the first junction and head north. Continue north through the large tunnel until you come to (I-5) and then head southeast. The ??? to spawn the NM is in this tunnel at (L-7).\n6. This fight is against Kettenkaefer, a beetle. It is weak to Ice and Light attacks. Once you kill it, re-examine the ??? to receive the key item Annals of Truth.\n7. Go back and speak with Jaucribaix to receive your reward.',
        notes = nil,
    },
    ['The Sacred Katana'] = {
        id = 140,
        start_npc = 'Jaucribaix',
        start_zone = 'Norg',
        start_pos = 'K-8',
        description = 'Your mumeito and a handful of crystal scales are needed to forge a katana that will be used in a Norg ritual.',
        reward = 'Magoroku',
        fame = 'Outlands',
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'Forge Your Destiny'},
        next = {'Yomi Okuri'},
        requirements = {
            {name = 'Sack of Fish Bait', count = 1},
            {name = 'Mumeito', count = 1},
        },
        walkthrough = '1. Talk to Jaucribaix at (K-8) near the Captain\'s Chamber while on Samurai to initiate the quest.\n   - You may change to a different job to complete the rest of this quest.\n2. Travel to the The Sanctuary of Zi\'Tah.\n   - Kill Goblin Robbers to get a Sack of Fish Bait, a common drop.\n3. Trade the Fish Bait to the ??? at (E-8) to pop Isonade, a fish NM.\n   - Isonade has approximately 6,100 HP.\n4. Re-examine the ??? to obtain the Handful of crystal scales.\n5. Return to Norg and trade your Mumeito to Jaucribaix to complete the quest.\n   - If you do not possess your Mumeito, Ranemaud at (I-7) can give you a new one for 30,000 gil.',
        notes = nil,
    },
    ['The Sahagin\'s Key'] = {
        id = 128,
        start_npc = 'Gimb',
        start_zone = 'Sea Serpent Grotto',
        start_pos = 'H-9',
        description = nil,
        reward = 'Sahagin Key',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Airship pass for Kazham', count = 1},
            {name = 'Gold Beastcoin', count = 1},
            {name = 'Silver Beastcoin', count = 1},
            {name = 'Norg Shell', count = 1},
            {name = 'Mythril Beastcoin', count = 3}            
        },
        walkthrough = 'NOTE: This is not a trackable quest in-game. It is an item obtainment sequence that exists in the game data but does not appear in your quest log and has no completion flag.\n\n1. Speak to Gimb in Norg to learn about obtaining a Sahagin Key.\n2. Travel to Sea Serpent Grotto and go past the Gold Door at (I-11) on the 4th map.\n3. Proceed to (H-11) and run off the cliff. Immediately run off the next cliff.\n4. Turn south and run off the cliff instead of continuing forward.\n5. Follow the left wall past the Cracked Wall to the Charybdis room and speak to Bou the Righteous.\n   - Do NOT leave Sea Serpent Grotto before completing the next step or you will have to speak to Bou again.\n6. Go past the Silver Door at (H-3) on the 2nd map and speak to Hurr the Betrayer.\n7. Trade Hurr 3 Mythril Beastcoins and 1 Norg Shell to receive a Sahagin Key.\n   - Additional keys can be obtained by trading 1 Gold Beastcoin and 1 Norg Shell to Hurr.\n   - The key breaks upon use at the Ornamental Door at (J-11).',
        notes = nil,
    },
    ['The Sahagin\'s Stash'] = {
        id = 136,
        start_npc = 'Laisrean',
        start_zone = 'Norg',
        start_pos = 'H-7',
        description = 'Bring back something from the Sahagins\' storage area in the Sea Serpent Grotto. Anything will do.',
        reward = 'Utsusemi: Ichi (Scroll)',
        fame = 'Norg',
        fame_level = '4',
        title = 'Treasure-House Ransacker',
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Silver Beastcoin', count = 1},
            {name = '[Key Item] Sea serpent statue', count = 1},
        },
        walkthrough = '1. Speak to Laisrean in Norg at (H-7)  to begin this quest.\n2. Exit Norg into Sea Serpent Grotto.\n3. Head South until you reach the fork at (H-6), head East.\n4. Turn South at (J-5).\n5. Head East at (J-10).\n6. Turn East at (K-12)\n7. Go past the Silver Door at (N-14).\n   - Examine the Door three times and trade it a Silver Beastcoin to get past it. You will keep the Silver Beastcoin.\n8. Fall off the path to the one below at (H-8) and continue going North.\n9. Follow this path until you find the ??? at (H-3). Interacting with it will give a [Key Item] Sea serpent statue.\n10. Return to Laisrean for your reward.',
        notes = nil,
    },
    ['The Search for Goldmane'] = {
        id = 200,
        start_npc = 'Zoriboh',
        start_zone = 'Rabao',
        start_pos = 'F-6',
        description = 'How is little Sanctia doing? Zoriboh wants you to take her a present from her father and see that she is keeping out of trouble.',
        reward = 'Deluxe Carbine\n3,000 gil',
        fame = 'Rabao',
        fame_level = nil,
        title = 'Rookie Hero Instructor',
        repeatable = 'No',
        previous = {'Chasing Dreams'},
        next = nil,
        requirements = {
            {name = 'Copper Key', count = 1},
        },
        walkthrough = '1. Talk to Zoriboh and obtain Care package key item.\n2. Speak to Quelveuiat (I-10) in Tavnazian Safehold.\n3. Go to Riverne - Site A01 and go through the portals to the island at I-11. You will receive a cutscene upon reaching the island.\n4. Trade a Copper Key to the Trunk for another cutscene.\n   - Copper Key drops from Riverne Vulture in Riverne - Site A01.\n5. Travel to the Metalworks and talk to Vladinek (H-8).\n6. Go to Bibiki Bay and take the Manaclipper to Purgonorgo Isle.\n   - You can also use the Voidwatch teleport if you have Bismarck access.\n7. Go to F-9 by the Weathered Boat.\n8. Click the boat for a cutscene.  After the cutscene the NM Rohemolipaud will spawn.\n   - He will use Eagle Eye Shot.\n   - Eventually, he will use Camouflage and the fight will end.\n   - If in a party with multiple players that need the quest, there is a 3 minute wait between respawning the NM.\n9. Click the Weathered Boat again to recieve a cutscene and a Deluxe Carbine.\n10. Go back to Rabao and talk to Zoriboh to complete the quest, and for your 3,000 gil reward.',
        notes = nil,
    },
    ['Trial by Fire'] = {
        id = 12,
        start_npc = 'Ronta-Onta',
        start_zone = 'Kazham',
        start_pos = 'J-9',
        description = 'Ring the tuning fork of fire upon the protocrystal in Ifrit\'s Cauldron. A path will open to the trial that awaits.',
        reward = 'Ifrit (Avatar)\n10,000 gil\nIfrit\'s Blade\nFire Belt\nFire Ring\nEgil\'s Torch',
        fame = 'Kazham',
        fame_level = '6',
        title = 'Heir of the Great Fire',
        repeatable = 'Yes',
        previous = nil,
        next = {
            'The Moonlit Path',
            'Mama Mia',
        },
        requirements = nil,
        walkthrough = '1. Speak with Ronta-Onta to obtain quest. If you are positive that you have the required fame but he is not allowing you to undertake this quest, continue speaking with him until his text changes. Once you have received the key item: Tuning fork of fire, you can now safely undertake the quest.\n2. Travel to Yhoator Jungle and look for the entrance to Ifrit\'s Cauldron at (I-6). On the first map of Ifrit\'s Cauldron head to the Flame Spout at (H-6). Trade it an Ice Cluster to make it recede or wait for it to recede on its own, then continue to (F-6).  On the second map (Map B), go to (I-8) to drop down to the seventh map.  When you land (Map C) go to the drop at (H-7), then proceed to (G-6) to find the entrance to the Cloister of Flames.\n   - Preferably, home point to Ifrit\'s Cauldron #1. If you don\'t have it yet, make sure to grab it on the way.\n   - The Unity 125 warp places you within a short run to the home point. Go left to J follow the tunnel and walk off the ledge at the end of it (the north part of the middle area).\n3. Defeat Ifrit Prime and you will receive a key item: Whisper of flames\n4. Return to Ronta-Onta with the whisper and he will provide several reward options including the ability to summon Ifrit.',
        notes = '1. Up to 6 party members can enter the arena.\n2. Each party member must have their own Tuning fork of fire.\n3. Time limit is 30 minutes.\n4. You can only select one of the rewards Ronta-Onta offers at any time.\n5. You may repeat this quest once per Earth day.\n6. You can save yourself a lot of time traveling to the Cloister by using the Mini Fork of Fire given by the quest Trial-Size Trial by Fire. You must be on Summoner as your main job, and obtain the Mini Tuning Fork from Dodmos, trade the fork back to Dodmos, but enter the Protocrystal normally. So long as you do not clear the level 20 version of the BC, you may warp to the Cloister as many times as you wish. (...or you can use Home Point warps, because it\'s the future.)\n7. You may also choose to retain the whisper in order to complete the requirements for this quest: The Moonlit Path.',
    },
    ['Trial by Water'] = {
        id = 133,
        start_npc = 'Edal-Tahdal',
        start_zone = 'Norg',
        start_pos = 'H-9',
        description = 'Ring the tuning fork of water upon the protocrystal in the Den of Rancor. A path will open to the trial that awaits.',
        reward = 'Leviathan (Avatar)\n10,000 Gil\nLeviathan\'s Rod\nWater Ring\nWater Belt\nEye of Nept',
        fame = 'Norg',
        fame_level = '4',
        title = 'Heir of the Great Water',
        repeatable = 'Yes',
        previous = nil,
        next = {
            'The Moonlit Path',
            'Mama Mia',
        },
        requirements = nil,
        walkthrough = '1. Speak with Edal-Tahdal to obtain quest. If you are positive that you have the required fame but he is not allowing you to undertake this quest, continue speaking with him until his text changes. Once you have received the key item: Tuning fork of water, you can now safely undertake the quest.\n2. Travel to Yhoator Jungle and look for the entrance to Temple of Uggalepih at (J-12). Inside, if you do not already have the Paintbrush of souls, be sure to get it as you will need it ahead. Travel to (F-5) of the first map of the Temple of Uggalepih (Map A) to return to Yhoator Jungle.  In Yhoator Jungle, follow the left wall to re-enter Temple of Uggalepih.  In Temple of Uggalepih (Map B), continue to (I-7).  Use the Paintbrush of souls on the empty Picture frame to open the door to the Den of Rancor.  On the first map of Den of Rancor (Map C), drop down the hole at (J-7) to the 6th map (Map D) and enter the Cloister of Tides at (I-7).\n   - Home Point to Den of Rancor #2. If you do not have it yet. you may have HP #1 warp from Zilart missions.\n     - From HP #1:  go to Point A (I-5) on Map 2 to reach Map 1. Once you\'re in Map 1, drop down at (J-7).\n   - The Survival Guide for Temple of Uggalepih is located at the (F-5) exit of the first map.\n   - The Unity warp to Den of Rancor (under content level 128) allows you to bypass the need for a [Key Item] Paintbrush of souls.\n3. Defeat Leviathan Prime and you will receive a [Key Item] Whisper of tides\n4. Return to Edal-Tahdal with the whisper and he will provide several reward options including the ability to summon Leviathan.',
        notes = '1. Up to 6 party members can enter the arena.\n2. Each party member must have their own Tuning fork of water.\n3. Time limit is 30 minutes.\n4. You can only select one of the rewards Edal-Tahdal offers at any time.\n5. You may repeat this quest once per Earth day.\n6. You can save yourself a lot of time traveling to the Cloister by using the Mini Fork of Wtr. given by the quest Trial-Size Trial by Water.  You must be on Summoner as your main job, and obtain the Mini Tuning Fork from Verctissa, trade the fork back to Verctissa, but enter the Protocrystal normally.  So long as you do not clear the level 20 version of the BC, you may warp to the Cloister as many times as you wish.\n7. You may also choose to retain the whisper in order to complete the requirements for this quest: The Moonlit Path.',
    },
    ['Trial by Wind'] = {
        id = 194,
        start_npc = 'Agado-Pugado',
        start_zone = 'Rabao',
        start_pos = 'G-9',
        description = 'Ring the tuning fork of wind upon the protocrystal in Cape Teriggan. A path will open to the trial that awaits.',
        reward = 'Garuda (Avatar)\n10,000 Gil\nGaruda\'s Dagger\nWind Belt\nWind Ring\nBubbly Water',
        fame = 'Rabao',
        fame_level = '6',
        title = 'Heir of the Great Wind',
        repeatable = 'Yes',
        previous = nil,
        next = {
            'The Moonlit Path',
            'Mama Mia',
        },
        requirements = nil,
        walkthrough = '1. Speak with Agado-Pugado to obtain quest. If you are positive that you have the required fame but he is not allowing you to undertake this quest, continue speaking with him until his text changes. Once you have received the [Key Item] Tuning fork of wind, you can now safely undertake the quest.\n2. Travel to Cape Teriggan (F-5) to enter the Cloister of Gales.\n   - Preferably, home point to Cape Teriggan #1. If you don\'t have it yet, make sure to grab it on the way.\n3. Defeat Garuda Prime and you will receive a [Key Item] Whisper of gales.\n4. Return to Agado-Pugado with the whisper and she will provide several reward options including the ability to summon Garuda.',
        notes = '1. Up to 6 party members can enter the arena.\n2. Each party member must have their own [Key Item] Tuning fork of wind.\n3. Time limit is 30 minutes.\n4. You can only select one of the rewards Agado-Pugado offers at any time.\n5. You may repeat this quest once per Earth day.\n6. You can save yourself a lot of time traveling to the Cloister by using the Mini Fork of Wind given by the quest Trial-Size Trial by Wind.  You must be on Summoner as your main job, and obtain the Mini Tuning Fork from Rahi Fohlatti, trade the fork back to Rahi Fohlatti, but enter the Protocrystal normally.  So long as you do not clear the level 20 version of the BC, you may warp to the Cloister as many times as you wish.\n7. You may also choose to retain the whisper in order to complete the requirements for this quest: The Moonlit Path.',
    },
    ['Trial-Size Trial by Fire'] = {
        id = 15,
        start_npc = 'Dodmos',
        start_zone = 'Kazham',
        start_pos = 'J-9',
        description = 'The Rhinostery has developed a new "mini" tuning fork of fire. Ringing it upon the protocrystal in Ifrit\'s Cauldron will open the path to a one-on-one battle with the beast that awaits inside. However, only summoners are allowed to take up this challenge.',
        reward = 'Instant Warp',
        fame = 'Kazham',
        fame_level = '2',
        title = nil,
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. Speak with Dodmos in Kazham (J-9) to begin quest and obtain a Mini Tuning Fork of Fire.\n2. You may prepare for the upcoming battle and whenever you are ready, trade Dodmos the tuning fork to be transported to the arena.\n3. Trade the fork to the Fire Protocrystal to enter the fighting arena.\n4. Defeat Ifrit Prime to complete quest.',
        notes = '1. Only Carbuncle may be used for this battle.\n   - Siren can also be used but it seems unintended.\n2. Use pet food (e.g. Grape Daifuku) and bring along a few Dawn Mulsum and juices if you don\'t want to use Astral Flow\n3. You must face this challenge alone.\n4. You may buff outside of the fight. Level cap will not dispel them.\n5. There is a 15 minutes time limit on the arena.\n6. Warning You may re-obtain the Mini Tuning Fork from the starting NPC at any point if you desire and repeat the fight, but the NPC will no longer teleport you to the Cloister.\n   - These were historically prized for their teleportation abilities, but Home Point warps have largely supplanted them.',
    },
    ['Trial-Size Trial by Water'] = {
        id = 148,
        start_npc = 'Verctissa',
        start_zone = 'Norg',
        start_pos = 'H-9',
        description = 'The Rhinostery has developed a new "mini" tuning fork of water. Ringing it upon the protocrystal in the Den of Rancor will open the path to a one-on-one battle with the beast that awaits inside. However, only summoners are allowed to take up this challenge.',
        reward = 'Instant Warp',
        fame = 'Outlands',
        fame_level = '2',
        title = nil,
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. Speak with Verctissa in Norg (H-9) to begin quest and obtain a Mini Tuning Fork of Water.\n2. You may prepare for the upcoming battle and whenever you are ready, trade Verctissa the tuning fork to be transported to the arena.\n3. Trade the fork to the Water Protocrystal to enter the fighting arena.\n4. Defeat Leviathan Prime to complete quest.',
        notes = '1. Only Carbuncle may be used for this battle.\n   - Siren can also be used but it seems unintended.\n2. Use pet food (e.g. Grape Daifuku) and bring along a few Dawn Mulsum and juices if you don\'t want to use Astral Flow\n3. You must face this challenge alone.\n4. You may buff outside of the fight. Level cap will not dispel them.\n5. There is a 15 minutes time limit on the arena.\n6. Warning You may re-obtain the Mini Tuning Fork from the starting NPC at any point if you desire and repeat the fight, but the NPC will no longer teleport you to the Cloister.\n   - These were historically prized for their teleportation abilities, but Home Point warps have largely supplanted them.',
    },
    ['Trial-Size Trial by Wind'] = {
        id = 197,
        start_npc = 'Rahi Fohlatti',
        start_zone = 'Rabao',
        start_pos = 'G-9',
        description = 'The Rhinostery has developed a new "mini" tuning fork of wind. Ringing it upon the protocrystal in Cape Teriggan will open the path to a one-on-one battle with the beast that awaits inside. However, only summoners are allowed to take up this challenge.',
        reward = 'Instant Warp',
        fame = 'Rabao',
        fame_level = '2',
        title = nil,
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = nil,
        walkthrough = '1. Speak with Rahi Fohlatti in Rabao (G-9) to begin quest and obtain a Mini Tuning Fork of Wind.\n2. You may prepare for the upcoming battle and whenever you are ready, trade Rahi Fohlatti the tuning fork to be transported to the arena.\n3. Trade the fork to the Wind Protocrystal to enter the fighting arena.\n4. Defeat Garuda Prime to complete quest.',
        notes = '1. Only Carbuncle may be used for this battle.\n   - Siren can also be used but it seems unintended. Regardless, she does very well against Garuda. (Except that Clarsach Call is wind-elemental, so it gets absorbed, so don\'t use it.)\n2. Use pet food (e.g. Grape Daifuku) and bring along a few Dawn Mulsum and juices if you don\'t want to use Astral Flow.\n3. You must face this challenge alone.\n4. You may buff outside of the fight. Level cap will not dispel them.\n5. There is a 15 minutes time limit on the arena.\n6. Warning You may re-obtain the Mini Tuning Fork from the starting NPC at any point if you desire and repeat the fight, but the NPC will no longer teleport you to the Cloister.\n   - These were historically prized for their teleportation abilities, but Home Point warps have largely supplanted them.',
    },
    ['True Will'] = {
        id = 145,
        start_npc = 'Ryoma',
        start_zone = 'Norg',
        start_pos = 'H-8',
        description = 'The Sahagin have stolen Mitsunari\'s treasure and hid it somewhere in the jungle on Elshimo Island. It is your job to find it.',
        reward = 'Ninja Chainmail',
        fame = 'Other',
        fame_level = nil,
        title = 'Paragon of Ninja Excellence',
        repeatable = 'Yes',
        previous = {'I\'ll Take the Big Box'},
        next = nil,
        requirements = {
            {name = 'Kuftal Coffer Key', count = 1},
        },
        walkthrough = '1. Speak with Ryoma in Norg to begin the quest.\n2. Travel to (I-7) in Yhoator Jungle.\n      - Survival Guide Teleportation (Elshimo Uplands → Yhoator Jungle) is the quickest way. You can find one east of Home Point #1 in Norg.\n      - Unity Warp (Level 122) will teleport you at (J-7).\n3. Once prepared, examine the ??? at (I-7) (northwest of Bloodlet Spring) to spawn 3 Sahagin NMs.\n4. These mobs are:\n      - Kappa Akuso (Monk)\n      - Kappa Biwa (Bard)\n      - Kappa Bonze (White Mage)\n         - Only one needs to be killed, so zoning to Den of Rancor and fighting one while the others despawn is a recommended strategy.\n5. After the Sahagin are defeated, examine the ??? again to receive the [Key Item]Old trick box. You will not get the KI until the mobs fully despawn, including the corpses.\n6. Return to Ryoma for another cutscene.\n7. Head to Rabao and speak with Leodarion at (F-7) on the west side of the lake near the windmill.\n8. Go to Kuftal Tunnel and obtain a Kuftal Coffer Key.\n   - Alternatively, you can purchase one from the Curio Vendor Moogle.\n      - Fastest route\'s are Survival Guide Teleportation (Vollbow → Kuftal Tunnel) or Unity Warp (Level 125) to Kuftal Tunnel.\n9. Find and open the Treasure Coffer to obtain the [Key Item]Large trick box.\n10. Return to Leodarion to complete the quest.',
        notes = nil,
    },
    ['VW Op. #054: Elshimo List'] = {
        id = 101,
        start_npc = 'Hildegard',
        start_zone = 'Kazham',
        start_pos = 'F-8',
        description = 'Planar rifts have been reported in the Yuhtunga Jungle, Ifrit\'s Cauldron, and the Temple of Uggalepih. Engage the Voidwalkers at each location and obliterate them!',
        reward = nil,
        fame = 'Kazham',
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = {'Voidwatch Ops: Border Crossing'},
        next = nil,
        requirements = nil,
        walkthrough = '1. After starting Voidwatch Ops: Border Crossing and receiving the [Key Item] Ashen stratum abyssite, speak to Hildegard in Kazham to begin the Quest.\n2. Engage in and complete the 3 Tier I Voidwatch battles in the Elshimo region:\n   - Holy Moly - Yuhtunga Jungle - Rift Locations: (F-11), (G-6), (J-7).\n   - Neith - Temple of Uggalepih - Rift Locations: Map 1: (I-9), (K-6) Map 2: (G-8).\n   - Ildebrann - Ifrit\'s Cauldron - Rift Locations: Map 3: (F-9), Map 5: (F-9), (I-6).\n     - Closest teleport is Unity Warp 125 to Map 5.\n3. Return to Hildegard to complete the Quest.',
        notes = nil,
    },
    ['VW Op. #101: Detour to Zepwell'] = {
        id = 102,
        start_npc = 'Gushing Spring',
        start_zone = 'Rabao',
        start_pos = nil,
        description = 'Planar rifts have been reported in the Western Altepa Desert, the Kuftal Tunnel, and the Quicksand Caves. Engage the Voidwalkers at each location and obliterate them!',
        reward = nil,
        fame = 'Rabao',
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'Voidwatch Ops: Border Crossing'},
        next = nil,
        requirements = nil,
        walkthrough = '1. After starting Voidwatch Ops: Border Crossing and receiving the [Key Item] Ashen stratum abyssite, speak to Gushing Spring in Rabao (G-8) to begin the Quest.\n2. Engage in and complete the 3 Tier I Voidwatch battles in the Zepwell region:\n   - Sabotender Campeador - Western Altepa Desert - Rift Locations: (G-10), (H-5), (L-6).\n   - Malleator Maurok - Quicksand Caves - Rift Location: Map 3 (G-9).\n     - Closest teleport is Unity 125 in Western Altepa Desert. Then go to Entrance 2 of Quicksand Caves.\n   - Tangaroa - Kuftal Tunnel - Rift Locations: Map 2: (F-8), (J-9) Map 3: (I-8).\n     - Closest teleport is Unity Warp 125 to Map 2.\n3. Return to Gushing Spring to complete the Quest.',
        notes = nil,
    },
    ['VW Op. #115: Li\'Telor Variant'] = {
        id = 103,
        start_npc = 'Kieran',
        start_zone = 'Norg',
        start_pos = nil,
        description = 'Planar rifts have been reported in the Sanctuary of Zi\'tah, the Boyahda Tree, and Ro\'Maeve. Engage the Voidwalkers at each location and obliterate them!',
        reward = '[Key Item] Ashen stratum abyssite III',
        fame = 'N/A',
        fame_level = 'N/A',
        title = nil,
        repeatable = nil,
        previous = {'Voidwatch Ops: Border Crossing'},
        next = {'Skyward Ho, Voidwatcher!'},
        requirements = nil,
        walkthrough = '1. Talk to Kieran after completing Voidwatch Ops: Border Crossing.\n   - Note: Zilart Mission 14 - Ark Angels must be started before you can receive this cutscene.\n2. Speak to Gilgamesh in Norg for a cutscene.\n3. Return to Kieran for a cutscene and to receive your [Key Item] Ashen stratum abyssite II (the quest is flagged at this point).\n4. Engage in and complete the three Tier II Voidwatch battles in the Li\'Telor region:\n   - Cath Palug in The Sanctuary of Zi\'Tah (E-9), (F-8), (G-10 - Survival Guide is very close by)\n   - Modron in The Boyahda Tree Map 1: (G-5), (K-8) Map 2: (F-7 - Very close to 125 Unity Warp)\n   - Mimic King in Ro\'Maeve (E-7), (I-9), (K-7)\n5. Return to Kieran, which will automatically finish this quest, reward you with [Key Item] Ashen stratum abyssite III, and begin the next quest.',
        notes = nil,
    },
    ['Voidwatch Ops: Border Crossing'] = {
        id = 100,
        start_npc = 'Kieran',
        start_zone = 'Norg',
        start_pos = nil,
        description = 'The Voidwatch has begun conducting secret operations outside of Jeuno and the three nations. Receive briefings from agents in Kazham and Rabao, then join the fight against the Voidwalkers!',
        reward = '[Key Item] Ashen stratum abyssite',
        fame = nil,
        fame_level = nil,
        title = nil,
        repeatable = nil,
        previous = nil,
        next = {'VW Op. #115: Li\'Telor Variant'},
        requirements = nil,
        walkthrough = '1. Speak to Kieran in Norg (I-8) to receive a cutscene and the Key Item [Key Item] Ashen stratum abyssite.\n2. Speak with the following NPCs to begin their respective subquests:\n   - Hildegard in Kazham (F-9) to begin VW Op. 054: Elshimo List.\n   - Gushing Spring in Rabao (G-8) to begin VW Op. 101: Detour to Zepwell.\n     - Make sure to speak to these NPCs and start both their respective subquests prior to killing the Voidwatch NMs, otherwise the kills will not count towards completing the subquests.\n3. Complete both subquests and return to Kieran to complete the quest.',
        notes = nil,
    },
    ['Wandering Souls'] = {
        id = 161,
        start_npc = 'Cermet Headstone',
        start_zone = 'Cape Teriggan',
        start_pos = 'H-5',
        description = 'Is there any way to soothe the spirits that wander about Cape Teriggan?\nPerhaps a rain lily...?',
        reward = 'Flagellant\'s Rope',
        fame = 'Outlands',
        fame_level = nil,
        title = 'Bearer of Bonds Beyond Time',
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Rain Lily', count = 1},
        },
        walkthrough = 'Trade the Rain Lily to the Cermet Headstone while having Zilart Mission 5 activated (or already completed) to receive a Flagellant\'s Rope.',
        notes = nil,
    },
    ['Wrath of the Opo-opos'] = {
        id = 160,
        start_npc = 'Cermet Headstone',
        start_zone = 'Yuhtunga Jungle',
        start_pos = 'L-7',
        description = 'The Opo-opos are not happy that you stole their "red treasure.',
        reward = 'Opo-opo Necklace',
        fame = 'Outlands',
        fame_level = nil,
        title = 'Friend of the Opo-opos',
        repeatable = nil,
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Garnet', count = 1},
        },
        walkthrough = 'Trade the Garnet to the Cermet Headstone in Yuhtunga Jungle (L-7) at any time during or after Zilart Mission 5 to receive an Opo-opo Necklace.',
        notes = nil,
    },
    ['Yomi Okuri'] = {
        id = 141,
        start_npc = 'Gilgamesh',
        start_zone = 'Norg',
        start_pos = 'L-8',
        description = 'Twenty years ago, a small nation was destroyed by the flames of war, and many died without reason. Your assistance is required in holding a ritual to send these troubled souls to their proper resting place in the afterlife.',
        reward = 'Myochin Sune-Ate',
        fame = 'Outlands',
        fame_level = nil,
        title = nil,
        repeatable = 'No',
        previous = {'The Sacred Katana'},
        next = {
            'A Thief in Norg!?',
            'Borghertz\'s Loyal Hands',
        },
        requirements = {
            {name = 'Bastore Sardine', count = 1},
            {name = 'Frost Turnip', count = 1},
            {name = 'G. Sheep Meat', count = 1},
            {name = 'Hecteyes Eye', count = 1},
        },
        walkthrough = '1. Speak to Jaucribaix in Norg (K-8)\n2. Speak to Washu at (J-8)\n3. Trade Washu Bastore Sardine, Frost Turnip,  Giant Sheep Meat,  and Hecteyes Eye to receive the key item Washu\'s tasty wurst.\n4. Examine the ??? in Labyrinth of Onzozo (F-8) to spawn the Notorious Monster Ubume.\n   - Easiest way is through Survival Guide will land you at Labyrinth of Onzozo (G-11), near the zone to Buburimu Peninsula..\n   - Alternate route is through Buburimu Peninsula.\n     - Ubume is a BRD type greater bird that loves to cast Horde Lullaby that is approximately level 60-65.\n5. Examine the ??? after defeating Ubume to receive the key item Yomotsu feather.\n6. Return to Norg and speak to to Jaucribaix.\n7. Exit Norg, re-enter, and speak to Jaucribaix to receive the key item Yomotsu Hirasaka.\n8. Examine the ??? in Valkurm Dunes at (B-7) between 18:00 and 4:00 to spawn the Notorious Monsters Doman and Onryo.\n   - Survival Guide to Gustav Tunnel will land you just outside (B-7)\n   - Doman is a Fomor, Onryo is a Ghost, both are approximately level 52.\n9. Examine the ??? after defeating Doman and Onryo and their corpses dissappear to receive the key item Faded Yomotsu Hirasaka.\n10. Speak to Jaucribaix to receive your reward',
        notes = nil,
    },
    ['You Call That a Knife?'] = {
        id = 6,
        start_npc = 'Mhebi Juhbily',
        start_zone = 'Kazham',
        start_pos = 'I-10',
        description = 'Mhebi wants to set her Tonberry free, but first, someone has to do something about his rusty knife.',
        reward = '7200 gil',
        fame = 'Kazham',
        fame_level = '6',
        title = 'Ya Done Good',
        repeatable = 'No',
        previous = nil,
        next = nil,
        requirements = {
            {name = 'Sandfish', count = 1},
            {name = 'Tonberry Board', count = 1},
        },
        walkthrough = '1. Trade Mhebi Juhbily (I-10) a Sandfish. When asked, tell her you give it to her. Then check the shed behind her for a cutscene.\n2. Speak to Vah Keshura (H-9).\n3. Obtain a Tonberry Board.\n   - Tonberry Board\'s drop off Tonberry Pursuers in the Temple of Uggalepih, Tonberry Shadowers in Yhoator Jungle, and from Tonberry Trailer in Den of Rancor.\n4. Use a Unity Concord NPC warp to Temple of Uggalepih (lv125), or follow the directions below.\n   - Head to (J-12) Yhoator Jungle to enter the Temple of Uggalepih.\n   - Once inside, follow the path and go South at (J-7), then North at (H-9), then North once more at (G-7).  This will lead you back outside to the Yhoator Jungle.\n   - Head left and re-enter the Temple at (H-11).\n     - Be careful not to fall off the ledge here.\n5. Back inside, head west, then south until you reach (H-10).\n6. Turn west once more and pass the Granite Door to reach the Tonberry Kitchen.\n7. Speak to Chef Nonberry, then trade him the Tonberry Board.\n8. He will give you the (Key Item) Nonberry\'s knife.\n9. Return to Mhebi Juhbily for your reward.',
        notes = nil,
    },
}
